// <auto-generated> tools/codegen/gen_dbc_layouts.py; WoWDBDefs e3df370 (definitions CC BY-SA 4.0). </auto-generated>
#nullable enable
namespace ArcaneCore.Data.ClientData;

/// <summary>A WoWDBDefs field in physical record order. ArrayLength counts logical values; locstring has eight strings and a flags slot.</summary>
public sealed record DbdField(string Name, string Type, int ArrayLength, int WidthBits, int Offset, string? ForeignTable, string? ForeignColumn);

/// <summary>One build-5875 DBC definition.</summary>
public sealed record DbdLayout(string File, int Fields, int RecordSize, IReadOnlyList<DbdField> Columns);

public static class ClientDbcDbdLayouts
{
    public static IReadOnlyDictionary<string, DbdLayout> All { get; } = new DbdLayout[]
    {
        new("AnimationData.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("Weaponflags", "int", 1, 32, 8, null, null),
            new("Bodyflags", "int", 1, 32, 12, null, null),
            new("Field_0_7_0_3694_004", "int", 1, 32, 16, null, null),
            new("Flags", "int", 1, 32, 20, null, null),
            new("Fallback", "int", 1, 32, 24, "AnimationData", "ID"),
        }),
        new("AreaPOI.dbc", 29, 116, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Importance", "int", 1, 32, 4, null, null),
            new("Icon", "int", 1, 32, 8, null, null),
            new("FactionID", "int", 1, 32, 12, "FactionTemplate", "ID"),
            new("Pos", "float", 3, 32, 16, null, null),
            new("ContinentID", "int", 1, 32, 28, "Map", "ID"),
            new("Flags", "int", 1, 32, 32, null, null),
            new("AreaID", "int", 1, 32, 36, "AreaTable", "ID"),
            new("Name_lang", "locstring", 1, 32, 40, null, null),
            new("Description_lang", "locstring", 1, 32, 76, null, null),
            new("WorldStateID", "int", 1, 32, 112, "WorldState", "ID"),
        }),
        new("AreaTable.dbc", 25, 100, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ContinentID", "int", 1, 32, 4, "Map", "ID"),
            new("ParentAreaID", "int", 1, 32, 8, "AreaTable", "ID"),
            new("AreaBit", "int", 1, 32, 12, null, null),
            new("Flags", "int", 1, 32, 16, null, null),
            new("SoundProviderPref", "int", 1, 32, 20, "SoundProviderPreferences", "ID"),
            new("SoundProviderPrefUnderwater", "int", 1, 32, 24, "SoundProviderPreferences", "ID"),
            new("AmbienceID", "int", 1, 32, 28, "SoundAmbience", "ID"),
            new("ZoneMusic", "int", 1, 32, 32, "ZoneMusic", "ID"),
            new("IntroSound", "int", 1, 32, 36, "ZoneIntroMusicTable", "ID"),
            new("ExplorationLevel", "int", 1, 32, 40, null, null),
            new("AreaName_lang", "locstring", 1, 32, 44, null, null),
            new("FactionGroupMask", "int", 1, 32, 80, null, null),
            new("LiquidTypeID", "int", 4, 32, 84, "LiquidType", "ID"),
        }),
        new("AreaTrigger.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ContinentID", "int", 1, 32, 4, "Map", "ID"),
            new("Pos", "float", 3, 32, 8, null, null),
            new("Radius", "float", 1, 32, 20, null, null),
            new("Box_length", "float", 1, 32, 24, null, null),
            new("Box_width", "float", 1, 32, 28, null, null),
            new("Box_height", "float", 1, 32, 32, null, null),
            new("Box_yaw", "float", 1, 32, 36, null, null),
        }),
        new("AttackAnimKits.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ItemSubclassID", "int", 1, 32, 4, null, null),
            new("AnimTypeID", "int", 1, 32, 8, "AttackAnimTypes", "AnimID"),
            new("AnimFrequency", "int", 1, 32, 12, null, null),
            new("WhichHand", "int", 1, 32, 16, null, null),
        }),
        new("AttackAnimTypes.dbc", 2, 8, new DbdField[]
        {
            new("AnimID", "int", 1, 32, 0, null, null),
            new("AnimName", "string", 1, 32, 4, null, null),
        }),
        new("AuctionHouse.dbc", 13, 52, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("FactionID", "int", 1, 32, 4, "Faction", "ID"),
            new("DepositRate", "int", 1, 32, 8, null, null),
            new("ConsignmentRate", "int", 1, 32, 12, null, null),
            new("Name_lang", "locstring", 1, 32, 16, null, null),
        }),
        new("BankBagSlotPrices.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Cost", "int", 1, 32, 4, null, null),
        }),
        new("CameraShakes.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ShakeType", "int", 1, 32, 4, null, null),
            new("Direction", "int", 1, 32, 8, null, null),
            new("Amplitude", "float", 1, 32, 12, null, null),
            new("Frequency", "float", 1, 32, 16, null, null),
            new("Duration", "float", 1, 32, 20, null, null),
            new("Phase", "float", 1, 32, 24, null, null),
            new("Coefficient", "float", 1, 32, 28, null, null),
        }),
        new("Cfg_Categories.dbc", 11, 44, new DbdField[]
        {
            new("Field_0_10_0_3892_000", "int", 1, 32, 0, null, null),
            new("Region_ID", "int", 1, 32, 4, null, null),
            new("Name_lang", "locstring", 1, 32, 8, null, null),
        }),
        new("Cfg_Configs.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("RealmType", "int", 1, 32, 4, null, null),
            new("PlayerKillingAllowed", "int", 1, 32, 8, null, null),
            new("Roleplaying", "int", 1, 32, 12, null, null),
        }),
        new("CharacterFacialHairStyles.dbc", 9, 36, new DbdField[]
        {
            new("RaceID", "int", 1, 32, 0, "ChrRaces", "ID"),
            new("SexID", "int", 1, 32, 4, null, null),
            new("VariationID", "int", 1, 32, 8, null, null),
            new("Geoset", "int", 6, 32, 12, null, null),
        }),
        new("CharBaseInfo.dbc", 2, 2, new DbdField[]
        {
            new("RaceID", "int", 1, 8, 0, "ChrRaces", "ID"),
            new("ClassID", "int", 1, 8, 1, "ChrClasses", "ID"),
        }),
        new("CharHairGeosets.dbc", 6, 24, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("RaceID", "int", 1, 32, 4, "ChrRaces", "ID"),
            new("SexID", "int", 1, 32, 8, null, null),
            new("VariationID", "int", 1, 32, 12, null, null),
            new("GeosetID", "int", 1, 32, 16, null, null),
            new("Showscalp", "int", 1, 32, 20, null, null),
        }),
        new("CharHairTextures.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Field_0_5_3_3368_001_race", "int", 1, 32, 4, "ChrRaces", "ID"),
            new("Field_0_5_3_3368_002_gender", "int", 1, 32, 8, null, null),
            new("Field_0_5_3_3368_003", "int", 1, 32, 12, null, null),
            new("Field_0_5_3_3368_004_mayberacemask", "int", 1, 32, 16, null, null),
            new("Field_0_5_3_3368_005_the_x_in_hair_xy_blp", "int", 1, 32, 20, null, null),
            new("Field_0_5_3_3368_006", "int", 1, 32, 24, null, null),
            new("Field_0_5_3_3368_007", "int", 1, 32, 28, null, null),
        }),
        new("CharSections.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("RaceID", "int", 1, 32, 4, "ChrRaces", "ID"),
            new("SexID", "int", 1, 32, 8, null, null),
            new("BaseSection", "int", 1, 32, 12, null, null),
            new("VariationIndex", "int", 1, 32, 16, null, null),
            new("ColorIndex", "int", 1, 32, 20, null, null),
            new("TextureName", "string", 3, 32, 24, null, null),
            new("Flags", "int", 1, 32, 36, null, null),
        }),
        new("CharStartOutfit.dbc", 41, 152, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("RaceID", "int", 1, 8, 4, "ChrRaces", "ID"),
            new("ClassID", "int", 1, 8, 5, "ChrClasses", "ID"),
            new("SexID", "int", 1, 8, 6, null, null),
            new("OutfitID", "int", 1, 8, 7, null, null),
            new("ItemID", "int", 12, 32, 8, "Item", "ID"),
            new("DisplayItemID", "int", 12, 32, 56, "ItemDisplayInfo", "ID"),
            new("InventoryType", "int", 12, 32, 104, null, null),
        }),
        new("CharVariations.dbc", 6, 24, new DbdField[]
        {
            new("RaceID", "int", 1, 32, 0, "ChrRaces", "ID"),
            new("SexID", "int", 1, 32, 4, null, null),
            new("TextureHoldLayer", "int", 4, 32, 8, null, null),
        }),
        new("ChatChannels.dbc", 21, 84, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Flags", "int", 1, 32, 4, null, null),
            new("FactionGroup", "int", 1, 32, 8, null, null),
            new("Name_lang", "locstring", 1, 32, 12, null, null),
            new("Shortcut_lang", "locstring", 1, 32, 48, null, null),
        }),
        new("ChatProfanity.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Text", "string", 1, 32, 4, null, null),
        }),
        new("ChrClasses.dbc", 17, 68, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("PlayerClass", "int", 1, 32, 4, null, null),
            new("DamageBonusStat", "int", 1, 32, 8, null, null),
            new("DisplayPower", "int", 1, 32, 12, "PowerType", "PowerTypeEnum"),
            new("PetNameToken", "string", 1, 32, 16, null, null),
            new("Name_lang", "locstring", 1, 32, 20, null, null),
            new("Filename", "string", 1, 32, 56, null, null),
            new("SpellClassSet", "int", 1, 32, 60, null, null),
            new("Flags", "int", 1, 32, 64, null, null),
        }),
        new("ChrRaces.dbc", 29, 116, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Flags", "int", 1, 32, 4, null, null),
            new("FactionID", "int", 1, 32, 8, "FactionTemplate", "ID"),
            new("ExplorationSoundID", "int", 1, 32, 12, "SoundEntries", "ID"),
            new("MaleDisplayID", "int", 1, 32, 16, "CreatureDisplayInfo", "ID"),
            new("FemaleDisplayID", "int", 1, 32, 20, "CreatureDisplayInfo", "ID"),
            new("ClientPrefix", "string", 1, 32, 24, null, null),
            new("MountScale", "float", 1, 32, 28, null, null),
            new("BaseLanguage", "int", 1, 32, 32, "Languages", "ID"),
            new("CreatureType", "int", 1, 32, 36, "CreatureType", "ID"),
            new("LoginEffectSpellID", "int", 1, 32, 40, "Spell", "ID"),
            new("CombatStunSpellID", "int", 1, 32, 44, "Spell", "ID"),
            new("ResSicknessSpellID", "int", 1, 32, 48, "Spell", "ID"),
            new("SplashSoundID", "int", 1, 32, 52, "SoundEntries", "ID"),
            new("StartingTaxiNodes", "int", 1, 32, 56, null, null),
            new("ClientFileString", "string", 1, 32, 60, null, null),
            new("CinematicSequenceID", "int", 1, 32, 64, "CinematicSequences", "ID"),
            new("Name_lang", "locstring", 1, 32, 68, null, null),
            new("FacialHairCustomization", "string", 2, 32, 104, null, null),
            new("HairCustomization", "string", 1, 32, 112, null, null),
        }),
        new("CinematicCamera.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Model", "string", 1, 32, 4, null, null),
            new("SoundID", "int", 1, 32, 8, "SoundEntries", "ID"),
            new("Origin", "float", 3, 32, 12, null, null),
            new("OriginFacing", "float", 1, 32, 24, null, null),
        }),
        new("CinematicSequences.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundID", "int", 1, 32, 4, "SoundEntries", "ID"),
            new("Camera", "int", 8, 32, 8, "CinematicCamera", "ID"),
        }),
        new("CreatureDisplayInfo.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ModelID", "int", 1, 32, 4, "CreatureModelData", "ID"),
            new("SoundID", "int", 1, 32, 8, "CreatureSoundData", "ID"),
            new("ExtendedDisplayInfoID", "int", 1, 32, 12, "CreatureDisplayInfoExtra", "ID"),
            new("CreatureModelScale", "float", 1, 32, 16, null, null),
            new("CreatureModelAlpha", "int", 1, 32, 20, null, null),
            new("TextureVariation", "string", 3, 32, 24, null, null),
            new("SizeClass", "int", 1, 32, 36, null, null),
            new("BloodID", "int", 1, 32, 40, "UnitBlood", "ID"),
            new("NPCSoundID", "int", 1, 32, 44, "NPCSounds", "ID"),
        }),
        new("CreatureDisplayInfoExtra.dbc", 19, 76, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("DisplayRaceID", "int", 1, 32, 4, "ChrRaces", "ID"),
            new("DisplaySexID", "int", 1, 32, 8, null, null),
            new("SkinID", "int", 1, 32, 12, null, null),
            new("FaceID", "int", 1, 32, 16, null, null),
            new("HairStyleID", "int", 1, 32, 20, null, null),
            new("HairColorID", "int", 1, 32, 24, null, null),
            new("FacialHairID", "int", 1, 32, 28, null, null),
            new("NPCItemDisplay", "int", 10, 32, 32, "ItemDisplayInfo", "ID"),
            new("BakeName", "string", 1, 32, 72, null, null),
        }),
        new("CreatureFamily.dbc", 18, 72, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MinScale", "float", 1, 32, 4, null, null),
            new("MinScaleLevel", "int", 1, 32, 8, null, null),
            new("MaxScale", "float", 1, 32, 12, null, null),
            new("MaxScaleLevel", "int", 1, 32, 16, null, null),
            new("SkillLine", "int", 2, 32, 20, "SkillLine", "ID"),
            new("PetFoodMask", "int", 1, 32, 28, null, null),
            new("Name_lang", "locstring", 1, 32, 32, null, null),
            new("IconFile", "string", 1, 32, 68, null, null),
        }),
        new("CreatureModelData.dbc", 16, 64, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Flags", "int", 1, 32, 4, null, null),
            new("ModelName", "string", 1, 32, 8, null, null),
            new("SizeClass", "int", 1, 32, 12, null, null),
            new("ModelScale", "float", 1, 32, 16, null, null),
            new("BloodID", "int", 1, 32, 20, "UnitBlood", "ID"),
            new("FootprintTextureID", "int", 1, 32, 24, "FootprintTextures", "ID"),
            new("FootprintTextureLength", "float", 1, 32, 28, null, null),
            new("FootprintTextureWidth", "float", 1, 32, 32, null, null),
            new("FootprintParticleScale", "float", 1, 32, 36, null, null),
            new("FoleyMaterialID", "int", 1, 32, 40, "Material", "ID"),
            new("FootstepShakeSize", "int", 1, 32, 44, null, null),
            new("DeathThudShakeSize", "int", 1, 32, 48, null, null),
            new("SoundID", "int", 1, 32, 52, "CreatureSoundData", "ID"),
            new("CollisionWidth", "float", 1, 32, 56, null, null),
            new("CollisionHeight", "float", 1, 32, 60, null, null),
        }),
        new("CreatureSoundData.dbc", 30, 120, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundExertionID", "int", 1, 32, 4, "SoundEntries", "ID"),
            new("SoundExertionCriticalID", "int", 1, 32, 8, "SoundEntries", "ID"),
            new("SoundInjuryID", "int", 1, 32, 12, "SoundEntries", "ID"),
            new("SoundInjuryCriticalID", "int", 1, 32, 16, "SoundEntries", "ID"),
            new("SoundInjuryCrushingBlowID", "int", 1, 32, 20, null, null),
            new("SoundDeathID", "int", 1, 32, 24, "SoundEntries", "ID"),
            new("SoundStunID", "int", 1, 32, 28, "SoundEntries", "ID"),
            new("SoundStandID", "int", 1, 32, 32, "SoundEntries", "ID"),
            new("SoundFootstepID", "int", 1, 32, 36, "FootstepTerrainLookup", "CreatureFootstepID"),
            new("SoundAggroID", "int", 1, 32, 40, "SoundEntries", "ID"),
            new("SoundWingFlapID", "int", 1, 32, 44, "SoundEntries", "ID"),
            new("SoundWingGlideID", "int", 1, 32, 48, "SoundEntries", "ID"),
            new("SoundAlertID", "int", 1, 32, 52, "SoundEntries", "ID"),
            new("SoundFidget", "int", 4, 32, 56, "SoundEntries", "ID"),
            new("CustomAttack", "int", 4, 32, 72, "SoundEntries", "ID"),
            new("NPCSoundID", "int", 1, 32, 88, null, null),
            new("LoopSoundID", "int", 1, 32, 92, "SoundEntries", "ID"),
            new("CreatureImpactType", "int", 1, 32, 96, null, null),
            new("SoundJumpStartID", "int", 1, 32, 100, "SoundEntries", "ID"),
            new("SoundJumpEndID", "int", 1, 32, 104, "SoundEntries", "ID"),
            new("SoundPetAttackID", "int", 1, 32, 108, "SoundEntries", "ID"),
            new("SoundPetOrderID", "int", 1, 32, 112, "SoundEntries", "ID"),
            new("SoundPetDismissID", "int", 1, 32, 116, "SoundEntries", "ID"),
        }),
        new("CreatureSpellData.dbc", 9, 36, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Spells", "int", 4, 32, 4, "Spell", "ID"),
            new("Availability", "int", 4, 32, 20, null, null),
        }),
        new("CreatureType.dbc", 11, 44, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("Flags", "int", 1, 32, 40, null, null),
        }),
        new("DeathThudLookups.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SizeClass", "int", 1, 32, 4, null, null),
            new("TerrainTypeSoundID", "int", 1, 32, 8, "TerrainTypeSounds", "ID"),
            new("SoundEntryID", "int", 1, 32, 12, "SoundEntries", "ID"),
            new("SoundEntryIDWater", "int", 1, 32, 16, "SoundEntries", "ID"),
        }),
        new("DurabilityCosts.dbc", 30, 120, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("WeaponSubClassCost", "int", 21, 32, 4, null, null),
            new("ArmorSubClassCost", "int", 8, 32, 88, null, null),
        }),
        new("DurabilityQuality.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Data", "float", 1, 32, 4, null, null),
        }),
        new("Emotes.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("EmoteSlashCommand", "string", 1, 32, 4, null, null),
            new("AnimID", "int", 1, 32, 8, "AnimationData", "ID"),
            new("EmoteFlags", "int", 1, 32, 12, null, null),
            new("EmoteSpecProc", "int", 1, 32, 16, null, null),
            new("EmoteSpecProcParam", "int", 1, 32, 20, null, null),
            new("EventSoundID", "int", 1, 32, 24, "SoundEntries", "ID"),
        }),
        new("EmotesText.dbc", 19, 76, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("EmoteID", "int", 1, 32, 8, "Emotes", "ID"),
            new("EmoteText", "int", 16, 32, 12, "EmotesTextData", "ID"),
        }),
        new("EmotesTextData.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Text_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("EmotesTextSound.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("EmotesTextID", "int", 1, 32, 4, "EmotesText", "ID"),
            new("RaceID", "int", 1, 32, 8, "ChrRaces", "ID"),
            new("SexID", "int", 1, 32, 12, null, null),
            new("SoundID", "int", 1, 32, 16, "SoundEntries", "ID"),
        }),
        new("EnvironmentalDamage.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("EnumID", "int", 1, 32, 4, null, null),
            new("VisualkitID", "int", 1, 32, 8, "SpellVisualKit", "ID"),
        }),
        new("Exhaustion.dbc", 15, 60, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Xp", "int", 1, 32, 4, null, null),
            new("Factor", "float", 1, 32, 8, null, null),
            new("OutdoorHours", "float", 1, 32, 12, null, null),
            new("InnHours", "float", 1, 32, 16, null, null),
            new("Name_lang", "locstring", 1, 32, 20, null, null),
            new("Threshold", "float", 1, 32, 56, null, null),
        }),
        new("Faction.dbc", 37, 148, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ReputationIndex", "int", 1, 32, 4, null, null),
            new("ReputationRaceMask", "int", 4, 32, 8, null, null),
            new("ReputationClassMask", "int", 4, 32, 24, null, null),
            new("ReputationBase", "int", 4, 32, 40, null, null),
            new("ReputationFlags", "int", 4, 32, 56, null, null),
            new("ParentFactionID", "int", 1, 32, 72, "Faction", "ID"),
            new("Name_lang", "locstring", 1, 32, 76, null, null),
            new("Description_lang", "locstring", 1, 32, 112, null, null),
        }),
        new("FactionGroup.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MaskID", "int", 1, 32, 4, null, null),
            new("InternalName", "string", 1, 32, 8, null, null),
            new("Name_lang", "locstring", 1, 32, 12, null, null),
        }),
        new("FactionTemplate.dbc", 14, 56, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Faction", "int", 1, 32, 4, "Faction", "ID"),
            new("Flags", "int", 1, 32, 8, null, null),
            new("FactionGroup", "int", 1, 32, 12, null, null),
            new("FriendGroup", "int", 1, 32, 16, null, null),
            new("EnemyGroup", "int", 1, 32, 20, null, null),
            new("Enemies", "int", 4, 32, 24, "Faction", "ID"),
            new("Friend", "int", 4, 32, 40, "Faction", "ID"),
        }),
        new("FootprintTextures.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("FootstepFilename", "string", 1, 32, 4, null, null),
        }),
        new("FootstepTerrainLookup.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("CreatureFootstepID", "int", 1, 32, 4, null, null),
            new("TerrainSoundID", "int", 1, 32, 8, "TerrainTypeSounds", "ID"),
            new("SoundID", "int", 1, 32, 12, "SoundEntries", "ID"),
            new("SoundIDSplash", "int", 1, 32, 16, "SoundEntries", "ID"),
        }),
        new("GameObjectArtKit.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("TextureVariation", "string", 3, 32, 4, null, null),
            new("AttachModel", "string", 4, 32, 16, null, null),
        }),
        new("GameObjectDisplayInfo.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ModelName", "string", 1, 32, 4, null, null),
            new("Sound", "int", 10, 32, 8, null, null),
        }),
        new("GameTips.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Text_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("GMSurveyCurrentSurvey.dbc", 2, 8, new DbdField[]
        {
            new("LANGID", "int", 1, 32, 0, null, null),
            new("GMSURVEY_ID", "int", 1, 32, 4, "GMSurveySurveys", "ID"),
        }),
        new("GMSurveyQuestions.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Question_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("GMSurveySurveys.dbc", 11, 44, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Q", "int", 10, 32, 4, "GMSurveyQuestions", "ID"),
        }),
        new("GMTicketCategory.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Category_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("GroundEffectDoodad.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("DoodadIdTag", "int", 1, 32, 4, null, null),
            new("Doodadpath", "string", 1, 32, 8, null, null),
        }),
        new("GroundEffectTexture.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("DoodadID", "int", 4, 32, 4, null, null),
            new("Density", "int", 1, 32, 20, null, null),
            new("Sound", "int", 1, 32, 24, null, null),
        }),
        new("HelmetGeosetVisData.dbc", 6, 24, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("HideGeoset", "int", 5, 32, 4, null, null),
        }),
        new("ItemBagFamily.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("ItemClass.dbc", 12, 48, new DbdField[]
        {
            new("ClassID", "int", 1, 32, 0, null, null),
            new("SubclassMapID", "int", 1, 32, 4, null, null),
            new("Flags", "int", 1, 32, 8, null, null),
            new("ClassName_lang", "locstring", 1, 32, 12, null, null),
        }),
        new("ItemDisplayInfo.dbc", 23, 92, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ModelName", "string", 2, 32, 4, null, null),
            new("ModelTexture", "string", 2, 32, 12, null, null),
            new("InventoryIcon", "string", 1, 32, 20, null, null),
            new("GeosetGroup", "int", 3, 32, 24, null, null),
            new("Flags", "int", 1, 32, 36, null, null),
            new("SpellVisualID", "int", 1, 32, 40, "SpellVisual", "ID"),
            new("GroupSoundIndex", "int", 1, 32, 44, null, null),
            new("HelmetGeosetVisID", "int", 2, 32, 48, null, null),
            new("Texture", "string", 8, 32, 56, null, null),
            new("ItemVisual", "int", 1, 32, 88, null, null),
        }),
        new("ItemGroupSounds.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Sound", "int", 4, 32, 4, null, null),
        }),
        new("ItemPetFood.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("ItemRandomProperties.dbc", 16, 64, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("Enchantment", "int", 5, 32, 8, "SpellItemEnchantment", "ID"),
            new("Name_lang", "locstring", 1, 32, 28, null, null),
        }),
        new("ItemSet.dbc", 45, 180, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("ItemID", "int", 17, 32, 40, "Item", "ID"),
            new("SetSpellID", "int", 8, 32, 108, "Spell", "ID"),
            new("SetThreshold", "int", 8, 32, 140, null, null),
            new("RequiredSkill", "int", 1, 32, 172, "SkillLine", "ID"),
            new("RequiredSkillRank", "int", 1, 32, 176, null, null),
        }),
        new("ItemSubClass.dbc", 28, 112, new DbdField[]
        {
            new("ClassID", "int", 1, 32, 0, "ItemClass", "ClassID"),
            new("SubClassID", "int", 1, 32, 4, null, null),
            new("PrerequisiteProficiency", "int", 1, 32, 8, null, null),
            new("PostrequisiteProficiency", "int", 1, 32, 12, null, null),
            new("Flags", "int", 1, 32, 16, null, null),
            new("DisplayFlags", "int", 1, 32, 20, null, null),
            new("WeaponParrySeq", "int", 1, 32, 24, null, null),
            new("WeaponReadySeq", "int", 1, 32, 28, null, null),
            new("WeaponAttackSeq", "int", 1, 32, 32, null, null),
            new("WeaponSwingSize", "int", 1, 32, 36, null, null),
            new("DisplayName_lang", "locstring", 1, 32, 40, null, null),
            new("VerboseName_lang", "locstring", 1, 32, 76, null, null),
        }),
        new("ItemSubClassMask.dbc", 11, 44, new DbdField[]
        {
            new("ClassID", "int", 1, 32, 0, "ItemClass", "ClassID"),
            new("Mask", "int", 1, 32, 4, null, null),
            new("Name_lang", "locstring", 1, 32, 8, null, null),
        }),
        new("ItemVisualEffects.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Model", "string", 1, 32, 4, null, null),
        }),
        new("ItemVisuals.dbc", 6, 24, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Slot", "int", 5, 32, 4, null, null),
        }),
        new("Languages.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("LanguageWords.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("LanguageID", "int", 1, 32, 4, "Languages", "ID"),
            new("Word", "string", 1, 32, 8, null, null),
        }),
        new("LFGDungeons.dbc", 14, 56, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("MinLevel", "int", 1, 32, 40, null, null),
            new("MaxLevel", "int", 1, 32, 44, null, null),
            new("TypeID", "int", 1, 32, 48, null, null),
            new("Faction", "int", 1, 32, 52, "Faction", "ID"),
        }),
        new("Light.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ContinentID", "int", 1, 32, 4, "Map", "ID"),
            new("GameCoords", "float", 3, 32, 8, null, null),
            new("GameFalloffStart", "float", 1, 32, 20, null, null),
            new("GameFalloffEnd", "float", 1, 32, 24, null, null),
            new("LightParamsID", "int", 5, 32, 28, "LightParams", "ID"),
        }),
        new("LightFloatBand.dbc", 34, 136, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Num", "int", 1, 32, 4, null, null),
            new("Time", "int", 16, 32, 8, null, null),
            new("Data", "float", 16, 32, 72, null, null),
        }),
        new("LightIntBand.dbc", 34, 136, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Num", "int", 1, 32, 4, null, null),
            new("Time", "int", 16, 32, 8, null, null),
            new("Data", "int", 16, 32, 72, null, null),
        }),
        new("LightParams.dbc", 9, 36, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("HighlightSky", "int", 1, 32, 4, null, null),
            new("LightSkyboxID", "int", 1, 32, 8, "LightSkybox", "ID"),
            new("Glow", "float", 1, 32, 12, null, null),
            new("WaterShallowAlpha", "float", 1, 32, 16, null, null),
            new("WaterDeepAlpha", "float", 1, 32, 20, null, null),
            new("OceanShallowAlpha", "float", 1, 32, 24, null, null),
            new("OceanDeepAlpha", "float", 1, 32, 28, null, null),
            new("Flags", "int", 1, 32, 32, null, null),
        }),
        new("LightSkybox.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
        }),
        new("LiquidType.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("Flags", "int", 1, 32, 8, null, null),
            new("SpellID", "int", 1, 32, 12, "Spell", "ID"),
        }),
        new("LoadingScreens.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("FileName", "string", 1, 32, 8, null, null),
        }),
        new("LoadingScreenTaxiSplines.dbc", 19, 76, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("PathID", "int", 1, 32, 4, "TaxiPath", "ID"),
            new("Locx", "float", 8, 32, 8, null, null),
            new("Locy", "float", 8, 32, 40, null, null),
            new("LegIndex", "int", 1, 32, 72, null, null),
        }),
        new("Lock.dbc", 33, 132, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Type", "int", 8, 32, 4, null, null),
            new("Index", "int", 8, 32, 36, null, null),
            new("Skill", "int", 8, 32, 68, null, null),
            new("Action", "int", 8, 32, 100, null, null),
        }),
        new("LockType.dbc", 29, 116, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("ResourceName_lang", "locstring", 1, 32, 40, null, null),
            new("Verb_lang", "locstring", 1, 32, 76, null, null),
            new("CursorName", "string", 1, 32, 112, null, null),
        }),
        new("MailTemplate.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Body_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("Map.dbc", 42, 168, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Directory", "string", 1, 32, 4, null, null),
            new("InstanceType", "int", 1, 32, 8, null, null),
            new("MapType", "int", 1, 32, 12, null, null),
            new("MapName_lang", "locstring", 1, 32, 16, null, null),
            new("MinLevel", "int", 1, 32, 52, null, null),
            new("MaxLevel", "int", 1, 32, 56, null, null),
            new("MaxPlayers", "int", 1, 32, 60, null, null),
            new("Unk0", "int", 1, 32, 64, null, null),
            new("Unk1", "int", 1, 32, 68, null, null),
            new("Unk2", "int", 1, 32, 72, null, null),
            new("ParentMapID", "int", 1, 32, 76, "AreaTable", "ID"),
            new("MapDescription0_lang", "locstring", 1, 32, 80, null, null),
            new("MapDescription1_lang", "locstring", 1, 32, 116, null, null),
            new("LoadingScreenID", "int", 1, 32, 152, "LoadingScreens", "ID"),
            new("RaidOffset", "int", 1, 32, 156, null, null),
            new("Continentname", "int", 1, 32, 160, null, null),
            new("Unk4", "int", 1, 32, 164, null, null),
        }),
        new("Material.dbc", 3, 12, new DbdField[]
        {
            new("MaterialID", "int", 1, 32, 0, "Material", "ID"),
            new("Flags", "int", 1, 32, 4, null, null),
            new("FoleySoundID", "int", 1, 32, 8, "SoundKit", "ID"),
        }),
        new("NameGen.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("RaceID", "int", 1, 32, 8, "ChrRaces", "ID"),
            new("Sex", "int", 1, 32, 12, null, null),
        }),
        new("NamesProfanity.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
        }),
        new("NamesReserved.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
        }),
        new("NPCSounds.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundID", "int", 4, 32, 4, "SoundKit", "ID"),
        }),
        new("Package.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Icon", "string", 1, 32, 4, null, null),
            new("Cost", "int", 1, 32, 8, null, null),
            new("Name_lang", "locstring", 1, 32, 12, null, null),
        }),
        new("PageTextMaterial.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
        }),
        new("PaperDollItemFrame.dbc", 3, 12, new DbdField[]
        {
            new("ItemButtonName", "string", 1, 32, 0, null, null),
            new("SlotIcon", "string", 1, 32, 4, null, null),
            new("SlotNumber", "int", 1, 32, 8, null, null),
        }),
        new("PetLoyalty.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("PetPersonality.dbc", 19, 76, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("HappinessThreshold", "int", 3, 32, 40, null, null),
            new("HappinessDamage", "float", 3, 32, 52, null, null),
            new("DamageModifier", "float", 3, 32, 64, null, null),
        }),
        new("QuestInfo.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("InfoName_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("QuestSort.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SortName_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("Resistances.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Flags", "int", 1, 32, 4, null, null),
            new("FizzleSoundID", "int", 1, 32, 8, "SoundKit", "ID"),
            new("Name_lang", "locstring", 1, 32, 12, null, null),
        }),
        new("ServerMessages.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Text_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("SheatheSoundLookups.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ClassID", "int", 1, 32, 4, "ItemSubClass", "ClassID"),
            new("SubclassID", "int", 1, 32, 8, "ItemSubClass", "SubClassID"),
            new("Material", "int", 1, 32, 12, "Material", "ID"),
            new("CheckMaterial", "int", 1, 32, 16, null, null),
            new("SheatheSound", "int", 1, 32, 20, null, null),
            new("UnsheatheSound", "int", 1, 32, 24, null, null),
        }),
        new("SkillCostsData.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SkillCostsID", "int", 1, 32, 4, null, null),
            new("Cost", "int", 3, 32, 8, null, null),
        }),
        new("SkillLine.dbc", 22, 88, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("CategoryID", "int", 1, 32, 4, "SkillLineCategory", "ID"),
            new("SkillCostsID", "int", 1, 32, 8, null, null),
            new("DisplayName_lang", "locstring", 1, 32, 12, null, null),
            new("Description_lang", "locstring", 1, 32, 48, null, null),
            new("SpellIconID", "int", 1, 32, 84, "SpellIcon", "ID"),
        }),
        new("SkillLineAbility.dbc", 15, 60, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SkillLine", "int", 1, 32, 4, "SkillLine", "ID"),
            new("Spell", "int", 1, 32, 8, "Spell", "ID"),
            new("RaceMask", "int", 1, 32, 12, null, null),
            new("ClassMask", "int", 1, 32, 16, null, null),
            new("ExcludeRace", "int", 1, 32, 20, null, null),
            new("ExcludeClass", "int", 1, 32, 24, null, null),
            new("MinSkillLineRank", "int", 1, 32, 28, null, null),
            new("SupercededBySpell", "int", 1, 32, 32, "Spell", "ID"),
            new("AcquireMethod", "int", 1, 32, 36, null, null),
            new("TrivialSkillLineRankHigh", "int", 1, 32, 40, null, null),
            new("TrivialSkillLineRankLow", "int", 1, 32, 44, null, null),
            new("Abandonable", "int", 1, 32, 48, null, null),
            new("CharacterPoints", "int", 2, 32, 52, null, null),
        }),
        new("SkillLineCategory.dbc", 11, 44, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("SortIndex", "int", 1, 32, 40, null, null),
        }),
        new("SkillRaceClassInfo.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SkillID", "int", 1, 32, 4, "SkillLine", "ID"),
            new("RaceMask", "int", 1, 32, 8, null, null),
            new("ClassMask", "int", 1, 32, 12, null, null),
            new("Flags", "int", 1, 32, 16, null, null),
            new("MinLevel", "int", 1, 32, 20, null, null),
            new("SkillTierID", "int", 1, 32, 24, "SkillTiers", "ID"),
            new("SkillCostIndex", "int", 1, 32, 28, null, null),
        }),
        new("SkillTiers.dbc", 33, 132, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Cost", "int", 16, 32, 4, null, null),
            new("Value", "int", 16, 32, 68, null, null),
        }),
        new("SoundAmbience.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("AmbienceID", "int", 2, 32, 4, "SoundKit", "ID"),
        }),
        new("SoundEntries.dbc", 29, 116, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundType", "int", 1, 32, 4, null, null),
            new("Name", "string", 1, 32, 8, null, null),
            new("File", "string", 10, 32, 12, null, null),
            new("Freq", "int", 10, 32, 52, null, null),
            new("DirectoryBase", "string", 1, 32, 92, null, null),
            new("VolumeFloat", "float", 1, 32, 96, null, null),
            new("Flags", "int", 1, 32, 100, null, null),
            new("MinDistance", "float", 1, 32, 104, null, null),
            new("DistanceCutoff", "float", 1, 32, 108, null, null),
            new("EAXDef", "int", 1, 32, 112, null, null),
        }),
        new("SoundProviderPreferences.dbc", 24, 96, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Description", "string", 1, 32, 4, null, null),
            new("Flags", "int", 1, 32, 8, null, null),
            new("EAXEnvironmentSelection", "int", 1, 32, 12, null, null),
            new("EAXDecayTime", "float", 1, 32, 16, null, null),
            new("EAX2EnvironmentSize", "float", 1, 32, 20, null, null),
            new("EAX2EnvironmentDiffusion", "float", 1, 32, 24, null, null),
            new("EAX2Room", "int", 1, 32, 28, null, null),
            new("EAX2RoomHF", "int", 1, 32, 32, null, null),
            new("EAX2DecayHFRatio", "float", 1, 32, 36, null, null),
            new("EAX2Reflections", "int", 1, 32, 40, null, null),
            new("EAX2ReflectionsDelay", "float", 1, 32, 44, null, null),
            new("EAX2Reverb", "int", 1, 32, 48, null, null),
            new("EAX2ReverbDelay", "float", 1, 32, 52, null, null),
            new("EAX2RoomRolloff", "float", 1, 32, 56, null, null),
            new("EAX2AirAbsorption", "float", 1, 32, 60, null, null),
            new("EAX3RoomLF", "int", 1, 32, 64, null, null),
            new("EAX3DecayLFRatio", "float", 1, 32, 68, null, null),
            new("EAX3EchoTime", "float", 1, 32, 72, null, null),
            new("EAX3EchoDepth", "float", 1, 32, 76, null, null),
            new("EAX3ModulationTime", "float", 1, 32, 80, null, null),
            new("EAX3ModulationDepth", "float", 1, 32, 84, null, null),
            new("EAX3HFReference", "float", 1, 32, 88, null, null),
            new("EAX3LFReference", "float", 1, 32, 92, null, null),
        }),
        new("SoundSamplePreferences.dbc", 17, 68, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Field_0_6_0_3592_001", "int", 1, 32, 4, null, null),
            new("Field_0_6_0_3592_002", "int", 1, 32, 8, null, null),
            new("EAX2SampleRoom", "int", 1, 32, 12, null, null),
            new("Field_0_6_0_3592_004", "int", 1, 32, 16, null, null),
            new("Field_0_6_0_3592_005", "int", 1, 32, 20, null, null),
            new("Field_0_6_0_3592_006", "float", 1, 32, 24, null, null),
            new("Field_0_6_0_3592_007", "int", 1, 32, 28, null, null),
            new("EAX2SampleOcclusionLFRatio", "float", 1, 32, 32, null, null),
            new("EAX2SampleOcclusionRoomRatio", "float", 1, 32, 36, null, null),
            new("Field_0_6_0_3592_010", "int", 1, 32, 40, null, null),
            new("EAX1EffectLevel", "float", 1, 32, 44, null, null),
            new("Field_0_6_0_3592_012", "int", 1, 32, 48, null, null),
            new("Field_0_6_0_3592_013", "float", 1, 32, 52, null, null),
            new("EAX3SampleExclusion", "float", 1, 32, 56, null, null),
            new("Field_0_6_0_3592_015", "float", 1, 32, 60, null, null),
            new("Field_0_6_0_3592_016", "int", 1, 32, 64, null, null),
        }),
        new("SoundWaterType.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundType", "int", 1, 32, 4, null, null),
            new("SoundSubtype", "int", 1, 32, 8, null, null),
            new("SoundID", "int", 1, 32, 12, "SoundEntries", "ID"),
        }),
        new("SpamMessages.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Text", "string", 1, 32, 4, null, null),
        }),
        new("Spell.dbc", 173, 692, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("School", "int", 1, 32, 4, null, null),
            new("Category", "int", 1, 32, 8, "SpellCategory", "ID"),
            new("CastUI", "int", 1, 32, 12, null, null),
            new("DispelType", "int", 1, 32, 16, "SpellDispelType", "ID"),
            new("Mechanic", "int", 1, 32, 20, "SpellMechanic", "ID"),
            new("Attributes", "int", 1, 32, 24, null, null),
            new("AttributesEx", "int", 1, 32, 28, null, null),
            new("AttributesExB", "int", 1, 32, 32, null, null),
            new("AttributesExC", "int", 1, 32, 36, null, null),
            new("AttributesExD", "int", 1, 32, 40, null, null),
            new("ShapeshiftMask", "int", 1, 32, 44, null, null),
            new("ShapeshiftExclude", "int", 1, 32, 48, null, null),
            new("Targets", "int", 1, 32, 52, null, null),
            new("TargetCreatureType", "int", 1, 32, 56, null, null),
            new("RequiresSpellFocus", "int", 1, 32, 60, "SpellFocusObject", "ID"),
            new("CasterAuraState", "int", 1, 32, 64, null, null),
            new("TargetAuraState", "int", 1, 32, 68, null, null),
            new("CastingTimeIndex", "int", 1, 32, 72, "SpellCastTimes", "ID"),
            new("RecoveryTime", "int", 1, 32, 76, null, null),
            new("CategoryRecoveryTime", "int", 1, 32, 80, null, null),
            new("InterruptFlags", "int", 1, 32, 84, null, null),
            new("AuraInterruptFlags", "int", 1, 32, 88, null, null),
            new("ChannelInterruptFlags", "int", 1, 32, 92, null, null),
            new("ProcFlags", "int", 1, 32, 96, null, null),
            new("ProcChance", "int", 1, 32, 100, null, null),
            new("ProcCharges", "int", 1, 32, 104, null, null),
            new("MaxLevel", "int", 1, 32, 108, null, null),
            new("BaseLevel", "int", 1, 32, 112, null, null),
            new("SpellLevel", "int", 1, 32, 116, null, null),
            new("DurationIndex", "int", 1, 32, 120, "SpellDuration", "ID"),
            new("PowerType", "int", 1, 32, 124, null, null),
            new("ManaCost", "int", 1, 32, 128, null, null),
            new("ManaCostPerLevel", "int", 1, 32, 132, null, null),
            new("ManaPerSecond", "int", 1, 32, 136, null, null),
            new("ManaPerSecondPerLevel", "int", 1, 32, 140, null, null),
            new("RangeIndex", "int", 1, 32, 144, null, null),
            new("Speed", "float", 1, 32, 148, null, null),
            new("ModalNextSpell", "int", 1, 32, 152, null, null),
            new("CumulativeAura", "int", 1, 32, 156, null, null),
            new("Totem", "int", 2, 32, 160, null, null),
            new("Reagent", "int", 8, 32, 168, "Item", "ID"),
            new("ReagentCount", "int", 8, 32, 200, null, null),
            new("EquippedItemClass", "int", 1, 32, 232, null, null),
            new("EquippedItemSubclass", "int", 1, 32, 236, null, null),
            new("EquippedItemInvTypes", "int", 1, 32, 240, null, null),
            new("Effect", "int", 3, 32, 244, null, null),
            new("EffectDieSides", "int", 3, 32, 256, null, null),
            new("EffectBaseDice", "int", 3, 32, 268, null, null),
            new("EffectDicePerLevel", "int", 3, 32, 280, null, null),
            new("EffectRealPointsPerLevel", "float", 3, 32, 292, null, null),
            new("EffectBasePoints", "int", 3, 32, 304, null, null),
            new("EffectMechanic", "int", 3, 32, 316, "SpellMechanic", "ID"),
            new("ImplicitTargetA", "int", 3, 32, 328, null, null),
            new("ImplicitTargetB", "int", 3, 32, 340, null, null),
            new("EffectRadiusIndex", "int", 3, 32, 352, "SpellRadius", "ID"),
            new("EffectAura", "int", 3, 32, 364, null, null),
            new("EffectAuraPeriod", "int", 3, 32, 376, null, null),
            new("EffectAmplitude", "float", 3, 32, 388, null, null),
            new("EffectChainTargets", "int", 3, 32, 400, null, null),
            new("EffectItemType", "int", 3, 32, 412, null, null),
            new("EffectMiscValue", "int", 3, 32, 424, null, null),
            new("EffectTriggerSpell", "int", 3, 32, 436, "Spell", "ID"),
            new("EffectPointsPerCombo", "float", 3, 32, 448, null, null),
            new("SpellVisualID", "int", 2, 32, 460, "SpellVisual", "ID"),
            new("SpellIconID", "int", 1, 32, 468, "SpellIcon", "ID"),
            new("ActiveIconID", "int", 1, 32, 472, "SpellIcon", "ID"),
            new("SpellPriority", "int", 1, 32, 476, null, null),
            new("Name_lang", "locstring", 1, 32, 480, null, null),
            new("NameSubtext_lang", "locstring", 1, 32, 516, null, null),
            new("Description_lang", "locstring", 1, 32, 552, null, null),
            new("AuraDescription_lang", "locstring", 1, 32, 588, null, null),
            new("ManaCostPct", "int", 1, 32, 624, null, null),
            new("StartRecoveryCategory", "int", 1, 32, 628, null, null),
            new("StartRecoveryTime", "int", 1, 32, 632, null, null),
            new("MaxTargetLevel", "int", 1, 32, 636, null, null),
            new("SpellClassSet", "int", 1, 32, 640, null, null),
            new("SpellClassMask", "int", 2, 32, 644, null, null),
            new("MaxTargets", "int", 1, 32, 652, null, null),
            new("DefenseType", "int", 1, 32, 656, null, null),
            new("PreventionType", "int", 1, 32, 660, null, null),
            new("StanceBarOrder", "int", 1, 32, 664, null, null),
            new("EffectChainAmplitude", "float", 3, 32, 668, null, null),
            new("MinFactionID", "int", 1, 32, 680, "Faction", "ID"),
            new("MinReputation", "int", 1, 32, 684, null, null),
            new("RequiredAuraVision", "int", 1, 32, 688, null, null),
        }),
        new("SpellCastTimes.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Base", "int", 1, 32, 4, null, null),
            new("PerLevel", "int", 1, 32, 8, null, null),
            new("Minimum", "int", 1, 32, 12, null, null),
        }),
        new("SpellCategory.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Flags", "int", 1, 32, 4, null, null),
        }),
        new("SpellChainEffects.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("AvgSegLen", "float", 1, 32, 4, null, null),
            new("Width", "float", 1, 32, 8, null, null),
            new("NoiseScale", "float", 1, 32, 12, null, null),
            new("TexCoordScale", "float", 1, 32, 16, null, null),
            new("SegDuration", "int", 1, 32, 20, null, null),
            new("SegDelay", "int", 1, 32, 24, null, null),
            new("Texture", "string", 1, 32, 28, null, null),
        }),
        new("SpellDispelType.dbc", 12, 48, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("Mask", "int", 1, 32, 40, null, null),
            new("InternalName", "string", 1, 32, 44, null, null),
        }),
        new("SpellDuration.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Duration", "int", 1, 32, 4, null, null),
            new("DurationPerLevel", "int", 1, 32, 8, null, null),
            new("MaxDuration", "int", 1, 32, 12, null, null),
        }),
        new("SpellEffectCameraShakes.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("CameraShake", "int", 3, 32, 4, null, null),
        }),
        new("SpellFocusObject.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("SpellIcon.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("TextureFilename", "string", 1, 32, 4, null, null),
        }),
        new("SpellItemEnchantment.dbc", 24, 96, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Effect", "int", 3, 32, 4, null, null),
            new("EffectPointsMin", "int", 3, 32, 16, null, null),
            new("EffectPointsMax", "int", 3, 32, 28, null, null),
            new("EffectArg", "int", 3, 32, 40, "Spell", "ID"),
            new("Name_lang", "locstring", 1, 32, 52, null, null),
            new("ItemVisual", "int", 1, 32, 88, "ItemVisuals", "ID"),
            new("Flags", "int", 1, 32, 92, null, null),
        }),
        new("SpellMechanic.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("StateName_lang", "locstring", 1, 32, 4, null, null),
        }),
        new("SpellRadius.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Radius", "float", 1, 32, 4, null, null),
            new("RadiusPerLevel", "float", 1, 32, 8, null, null),
            new("RadiusMax", "float", 1, 32, 12, null, null),
        }),
        new("SpellRange.dbc", 22, 88, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("RangeMin", "float", 1, 32, 4, null, null),
            new("RangeMax", "float", 1, 32, 8, null, null),
            new("Flags", "int", 1, 32, 12, null, null),
            new("DisplayName_lang", "locstring", 1, 32, 16, null, null),
            new("DisplayNameShort_lang", "locstring", 1, 32, 52, null, null),
        }),
        new("SpellShapeshiftForm.dbc", 14, 56, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("BonusActionBar", "int", 1, 32, 4, null, null),
            new("Name_lang", "locstring", 1, 32, 8, null, null),
            new("Flags", "int", 1, 32, 44, null, null),
            new("CreatureType", "int", 1, 32, 48, "CreatureType", "ID"),
            new("AttackIconID", "int", 1, 32, 52, "SpellIcon", "ID"),
        }),
        new("SpellVisual.dbc", 16, 64, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("PrecastKit", "int", 1, 32, 4, "SpellVisualKit", "ID"),
            new("CastKit", "int", 1, 32, 8, "SpellVisualKit", "ID"),
            new("ImpactKit", "int", 1, 32, 12, "SpellVisualKit", "ID"),
            new("StateKit", "int", 1, 32, 16, "SpellVisualKit", "ID"),
            new("ChannelKit", "int", 1, 32, 20, "SpellVisualKit", "ID"),
            new("HasMissile", "int", 1, 32, 24, null, null),
            new("MissileModel", "int", 1, 32, 28, null, null),
            new("MissilePathType", "int", 1, 32, 32, null, null),
            new("MissileDestinationAttachment", "int", 1, 32, 36, null, null),
            new("MissileSound", "int", 1, 32, 40, null, null),
            new("HasAreaEffect", "int", 1, 32, 44, null, null),
            new("AreaModel", "int", 1, 32, 48, null, null),
            new("AreaKit", "int", 1, 32, 52, null, null),
            new("AnimEventSoundID", "int", 1, 32, 56, "SoundEntries", "ID"),
            new("Flags", "int", 1, 32, 60, null, null),
        }),
        new("SpellVisualEffectName.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("FileName", "string", 1, 32, 8, null, null),
            new("SpecialAttachPoint", "int", 1, 32, 12, null, null),
            new("AreaEffectSize", "float", 1, 32, 16, null, null),
        }),
        new("SpellVisualKit.dbc", 35, 140, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("KitType", "int", 1, 32, 4, null, null),
            new("AnimID", "int", 1, 32, 8, "AnimationData", "ID"),
            new("HeadEffect", "int", 1, 32, 12, null, null),
            new("ChestEffect", "int", 1, 32, 16, null, null),
            new("BaseEffect", "int", 1, 32, 20, null, null),
            new("LeftHandEffect", "int", 1, 32, 24, null, null),
            new("RightHandEffect", "int", 1, 32, 28, null, null),
            new("BreathEffect", "int", 1, 32, 32, null, null),
            new("SpecialEffect", "int", 3, 32, 36, null, null),
            new("WorldEffect", "int", 1, 32, 48, null, null),
            new("SoundID", "int", 1, 32, 52, "SoundEntries", "ID"),
            new("ShakeID", "int", 1, 32, 56, "SpellEffectCameraShakes", "ID"),
            new("CharProc", "int", 4, 32, 60, null, null),
            new("CharParamZero", "float", 4, 32, 76, null, null),
            new("CharParamOne", "float", 4, 32, 92, null, null),
            new("CharParamTwo", "float", 4, 32, 108, null, null),
            new("CharParamThree", "float", 4, 32, 124, null, null),
        }),
        new("SpellVisualPrecastTransitions.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("PrecastLoadAnimName", "string", 1, 32, 4, null, null),
            new("PrecastHoldAnimName", "string", 1, 32, 8, null, null),
        }),
        new("StableSlotPrices.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Cost", "int", 1, 32, 4, null, null),
        }),
        new("Startup_Strings.dbc", 11, 44, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("Message_lang", "locstring", 1, 32, 8, null, null),
        }),
        new("Stationery.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ItemID", "int", 1, 32, 4, "Item", "ID"),
            new("Texture", "string", 1, 32, 8, null, null),
            new("Flags", "int", 1, 32, 12, null, null),
        }),
        new("StringLookups.dbc", 2, 8, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("String", "string", 1, 32, 4, null, null),
        }),
        new("Talent.dbc", 21, 84, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("TabID", "int", 1, 32, 4, "TalentTab", "ID"),
            new("TierID", "int", 1, 32, 8, null, null),
            new("ColumnIndex", "int", 1, 32, 12, null, null),
            new("SpellRank", "int", 9, 32, 16, "Spell", "ID"),
            new("PrereqTalent", "int", 3, 32, 52, "Talent", "ID"),
            new("PrereqRank", "int", 3, 32, 64, null, null),
            new("Flags", "int", 1, 32, 76, null, null),
            new("RequiredSpellID", "int", 1, 32, 80, "Spell", "ID"),
        }),
        new("TalentTab.dbc", 15, 60, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name_lang", "locstring", 1, 32, 4, null, null),
            new("SpellIconID", "int", 1, 32, 40, "SpellIcon", "ID"),
            new("RaceMask", "int", 1, 32, 44, null, null),
            new("ClassMask", "int", 1, 32, 48, null, null),
            new("OrderIndex", "int", 1, 32, 52, null, null),
            new("BackgroundFile", "string", 1, 32, 56, null, null),
        }),
        new("TaxiNodes.dbc", 16, 64, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("ContinentID", "int", 1, 32, 4, "Map", "ID"),
            new("Pos", "float", 3, 32, 8, null, null),
            new("Name_lang", "locstring", 1, 32, 20, null, null),
            new("MountCreatureID", "int", 2, 32, 56, "Creature", "ID"),
        }),
        new("TaxiPath.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("FromTaxiNode", "int", 1, 32, 4, "TaxiNodes", "ID"),
            new("ToTaxiNode", "int", 1, 32, 8, "TaxiNodes", "ID"),
            new("Cost", "int", 1, 32, 12, null, null),
        }),
        new("TaxiPathNode.dbc", 9, 36, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("PathID", "int", 1, 32, 4, "TaxiPath", "ID"),
            new("NodeIndex", "int", 1, 32, 8, null, null),
            new("ContinentID", "int", 1, 32, 12, "Map", "ID"),
            new("Loc", "float", 3, 32, 16, null, null),
            new("Flags", "int", 1, 32, 28, null, null),
            new("Delay", "int", 1, 32, 32, null, null),
        }),
        new("TerrainType.dbc", 6, 24, new DbdField[]
        {
            new("TerrainID", "int", 1, 32, 0, null, null),
            new("TerrainDesc", "string", 1, 32, 4, null, null),
            new("FootstepSprayRun", "int", 1, 32, 8, null, null),
            new("FootstepSprayWalk", "int", 1, 32, 12, null, null),
            new("SoundID", "int", 1, 32, 16, "TerrainTypeSounds", "ID"),
            new("Flags", "int", 1, 32, 20, null, null),
        }),
        new("TerrainTypeSounds.dbc", 1, 4, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
        }),
        new("TransportAnimation.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("TransportID", "int", 1, 32, 4, null, null),
            new("TimeIndex", "int", 1, 32, 8, null, null),
            new("Pos", "float", 3, 32, 12, null, null),
            new("SequenceID", "int", 1, 32, 24, null, null),
        }),
        new("UISoundLookups.dbc", 3, 12, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SoundID", "int", 1, 32, 4, "SoundEntries", "ID"),
            new("SoundName", "string", 1, 32, 8, null, null),
        }),
        new("UnitBlood.dbc", 10, 40, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("CombatBloodSpurtFront", "int", 2, 32, 4, null, null),
            new("CombatBloodSpurtBack", "int", 2, 32, 12, null, null),
            new("GroundBlood", "string", 5, 32, 20, null, null),
        }),
        new("UnitBloodLevels.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Violencelevel", "int", 3, 32, 4, null, null),
        }),
        new("VideoHardware.dbc", 22, 88, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("VendorID", "int", 1, 32, 4, null, null),
            new("DeviceID", "int", 1, 32, 8, null, null),
            new("FarclipIdx", "int", 1, 32, 12, null, null),
            new("TerrainLODDistIdx", "int", 1, 32, 16, null, null),
            new("TerrainShadowLOD", "int", 1, 32, 20, null, null),
            new("DetailDoodadDensityIdx", "int", 1, 32, 24, null, null),
            new("DetailDoodadAlpha", "int", 1, 32, 28, null, null),
            new("AnimatingDoodadIdx", "int", 1, 32, 32, null, null),
            new("Trilinear", "int", 1, 32, 36, null, null),
            new("NumLights", "int", 1, 32, 40, null, null),
            new("Specularity", "int", 1, 32, 44, null, null),
            new("WaterLODIdx", "int", 1, 32, 48, null, null),
            new("ParticleDensityIdx", "int", 1, 32, 52, null, null),
            new("UnitDrawDistIdx", "int", 1, 32, 56, null, null),
            new("SmallCullDistIdx", "int", 1, 32, 60, null, null),
            new("ResolutionIdx", "int", 1, 32, 64, null, null),
            new("BaseMipLevel", "int", 1, 32, 68, null, null),
            new("OglOverrides", "string", 1, 32, 72, null, null),
            new("D3dOverrides", "string", 1, 32, 76, null, null),
            new("FixLag", "int", 1, 32, 80, null, null),
            new("Multisample", "int", 1, 32, 84, null, null),
        }),
        new("VocalUISounds.dbc", 7, 28, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("VocalUIEnum", "int", 1, 32, 4, null, null),
            new("RaceID", "int", 1, 32, 8, "ChrRaces", "ID"),
            new("NormalSoundID", "int", 2, 32, 12, "SoundKit", "ID"),
            new("PissedSoundID", "int", 2, 32, 20, "SoundKit", "ID"),
        }),
        new("WeaponImpactSounds.dbc", 23, 92, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("WeaponSubClassID", "int", 1, 32, 4, null, null),
            new("ParrySoundType", "int", 1, 32, 8, null, null),
            new("ImpactSoundID", "int", 10, 32, 12, "SoundEntries", "ID"),
            new("CritImpactSoundID", "int", 10, 32, 52, "SoundEntries", "ID"),
        }),
        new("WeaponSwingSounds2.dbc", 4, 16, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SwingType", "int", 1, 32, 4, null, null),
            new("Crit", "int", 1, 32, 8, null, null),
            new("SoundID", "int", 1, 32, 12, "SoundEntries", "ID"),
        }),
        new("WMOAreaTable.dbc", 20, 80, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("WMOID", "int", 1, 32, 4, null, null),
            new("NameSetID", "int", 1, 32, 8, null, null),
            new("WMOGroupID", "int", 1, 32, 12, null, null),
            new("SoundProviderPref", "int", 1, 32, 16, "SoundProviderPreferences", "ID"),
            new("SoundProviderPrefUnderwater", "int", 1, 32, 20, "SoundProviderPreferences", "ID"),
            new("AmbienceID", "int", 1, 32, 24, "SoundAmbience", "ID"),
            new("ZoneMusic", "int", 1, 32, 28, "ZoneMusic", "ID"),
            new("IntroSound", "int", 1, 32, 32, "ZoneIntroMusicTable", "ID"),
            new("Flags", "int", 1, 32, 36, null, null),
            new("AreaTableID", "int", 1, 32, 40, "AreaTable", "ID"),
            new("AreaName_lang", "locstring", 1, 32, 44, null, null),
        }),
        new("WorldMapArea.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MapID", "int", 1, 32, 4, "Map", "ID"),
            new("AreaID", "int", 1, 32, 8, "AreaTable", "ID"),
            new("AreaName", "string", 1, 32, 12, null, null),
            new("LocLeft", "float", 1, 32, 16, null, null),
            new("LocRight", "float", 1, 32, 20, null, null),
            new("LocTop", "float", 1, 32, 24, null, null),
            new("LocBottom", "float", 1, 32, 28, null, null),
        }),
        new("WorldMapContinent.dbc", 13, 52, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MapID", "int", 1, 32, 4, "Map", "ID"),
            new("LeftBoundary", "int", 1, 32, 8, null, null),
            new("RightBoundary", "int", 1, 32, 12, null, null),
            new("TopBoundary", "int", 1, 32, 16, null, null),
            new("BottomBoundary", "int", 1, 32, 20, null, null),
            new("ContinentOffset", "float", 2, 32, 24, null, null),
            new("Scale", "float", 1, 32, 32, null, null),
            new("TaxiMin", "float", 2, 32, 36, null, null),
            new("TaxiMax", "float", 2, 32, 44, null, null),
        }),
        new("WorldMapOverlay.dbc", 17, 68, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MapAreaID", "int", 1, 32, 4, "WorldMapArea", "ID"),
            new("AreaID", "int", 4, 32, 8, "AreaTable", "ID"),
            new("MapPointX", "int", 1, 32, 24, null, null),
            new("MapPointY", "int", 1, 32, 28, null, null),
            new("TextureName", "string", 1, 32, 32, null, null),
            new("TextureWidth", "int", 1, 32, 36, null, null),
            new("TextureHeight", "int", 1, 32, 40, null, null),
            new("OffsetX", "int", 1, 32, 44, null, null),
            new("OffsetY", "int", 1, 32, 48, null, null),
            new("HitRectTop", "int", 1, 32, 52, null, null),
            new("HitRectLeft", "int", 1, 32, 56, null, null),
            new("HitRectBottom", "int", 1, 32, 60, null, null),
            new("HitRectRight", "int", 1, 32, 64, null, null),
        }),
        new("WorldSafeLocs.dbc", 14, 56, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Continent", "int", 1, 32, 4, "Map", "ID"),
            new("Loc", "float", 3, 32, 8, null, null),
            new("AreaName_lang", "locstring", 1, 32, 20, null, null),
        }),
        new("WorldStateUI.dbc", 39, 156, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("MapID", "int", 1, 32, 4, "Map", "ID"),
            new("AreaID", "int", 1, 32, 8, "AreaTable", "ID"),
            new("Icon", "string", 1, 32, 12, null, null),
            new("String_lang", "locstring", 1, 32, 16, null, null),
            new("Tooltip_lang", "locstring", 1, 32, 52, null, null),
            new("FactionID", "int", 1, 32, 88, "Faction", "ID"),
            new("StateVariable", "int", 1, 32, 92, null, null),
            new("Type", "int", 1, 32, 96, null, null),
            new("DynamicIcon", "string", 1, 32, 100, null, null),
            new("DynamicTooltip_lang", "locstring", 1, 32, 104, null, null),
            new("ExtendedUI", "string", 1, 32, 140, null, null),
            new("ExtendedUIStateVariable", "int", 3, 32, 144, null, null),
        }),
        new("WowError_Strings.dbc", 11, 44, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("Description_lang", "locstring", 1, 32, 8, null, null),
        }),
        new("ZoneIntroMusicTable.dbc", 5, 20, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("Name", "string", 1, 32, 4, null, null),
            new("SoundID", "int", 1, 32, 8, "SoundEntries", "ID"),
            new("Priority", "int", 1, 32, 12, null, null),
            new("MinDelayMinutes", "int", 1, 32, 16, null, null),
        }),
        new("ZoneMusic.dbc", 8, 32, new DbdField[]
        {
            new("ID", "int", 1, 32, 0, null, null),
            new("SetName", "string", 1, 32, 4, null, null),
            new("SilenceIntervalMin", "int", 2, 32, 8, null, null),
            new("SilenceIntervalMax", "int", 2, 32, 16, null, null),
            new("Sounds", "int", 2, 32, 24, "SoundEntries", "ID"),
        }),
    }.ToDictionary(l => l.File, StringComparer.OrdinalIgnoreCase);
}
