// <auto-generated>
// Generated by tools/codegen/gen_wow_tables.py -- do not edit by hand.
// Source: vmangos UpdateFields_1_12_1.cpp (the client's own field descriptor table for
// build 5875); all 236 gtker/wow_messages 1.12 update-mask ranges were verified
// to be tiled by these fields with matching offsets, sizes and types.
// </auto-generated>

#nullable enable

namespace ArcaneCore.Game;

/// <summary>Absolute update-field indices for build 5875.</summary>
public static class UpdateFields
{
    /// <summary>OBJECT_FIELD_GUID (size 2); Public.</summary>
    public const int ObjectFieldGuid = 0x0;
    /// <summary>OBJECT_FIELD_TYPE; Public.</summary>
    public const int ObjectFieldType = 0x2;
    /// <summary>OBJECT_FIELD_ENTRY; Public.</summary>
    public const int ObjectFieldEntry = 0x3;
    /// <summary>OBJECT_FIELD_SCALE_X; Public.</summary>
    public const int ObjectFieldScaleX = 0x4;
    /// <summary>OBJECT_FIELD_PADDING; None.</summary>
    public const int ObjectFieldPadding = 0x5;
    /// <summary>OBJECT_END; None.</summary>
    public const int ObjectEnd = 0x6;
    /// <summary>ITEM_FIELD_OWNER (size 2); Public.</summary>
    public const int ItemFieldOwner = 0x6;
    /// <summary>ITEM_FIELD_CONTAINED (size 2); Public.</summary>
    public const int ItemFieldContained = 0x8;
    /// <summary>ITEM_FIELD_CREATOR (size 2); Public.</summary>
    public const int ItemFieldCreator = 0xA;
    /// <summary>ITEM_FIELD_GIFTCREATOR (size 2); Public.</summary>
    public const int ItemFieldGiftcreator = 0xC;
    /// <summary>ITEM_FIELD_STACK_COUNT; OwnerOnly, ItemOwner.</summary>
    public const int ItemFieldStackCount = 0xE;
    /// <summary>ITEM_FIELD_DURATION; OwnerOnly, ItemOwner.</summary>
    public const int ItemFieldDuration = 0xF;
    /// <summary>ITEM_FIELD_SPELL_CHARGES (size 5); OwnerOnly, ItemOwner.</summary>
    public const int ItemFieldSpellCharges = 0x10;
    /// <summary>ITEM_FIELD_FLAGS; Public.</summary>
    public const int ItemFieldFlags = 0x15;
    /// <summary>ITEM_FIELD_ENCHANTMENT (size 21); Public.</summary>
    public const int ItemFieldEnchantment = 0x16;
    /// <summary>ITEM_FIELD_PROPERTY_SEED; Public.</summary>
    public const int ItemFieldPropertySeed = 0x2B;
    /// <summary>ITEM_FIELD_RANDOM_PROPERTIES_ID; Public.</summary>
    public const int ItemFieldRandomPropertiesId = 0x2C;
    /// <summary>ITEM_FIELD_ITEM_TEXT_ID; OwnerOnly.</summary>
    public const int ItemFieldItemTextId = 0x2D;
    /// <summary>ITEM_FIELD_DURABILITY; OwnerOnly, ItemOwner.</summary>
    public const int ItemFieldDurability = 0x2E;
    /// <summary>ITEM_FIELD_MAXDURABILITY; OwnerOnly, ItemOwner.</summary>
    public const int ItemFieldMaxdurability = 0x2F;
    /// <summary>ITEM_END; None.</summary>
    public const int ItemEnd = 0x30;
    /// <summary>CONTAINER_FIELD_NUM_SLOTS; Public.</summary>
    public const int ContainerFieldNumSlots = 0x30;
    /// <summary>CONTAINER_ALIGN_PAD; None.</summary>
    public const int ContainerAlignPad = 0x31;
    /// <summary>CONTAINER_FIELD_SLOT_1 (size 72); Public.</summary>
    public const int ContainerFieldSlot1 = 0x32;
    /// <summary>CONTAINER_END; None.</summary>
    public const int ContainerEnd = 0x7A;
    /// <summary>UNIT_FIELD_CHARM (size 2); Public.</summary>
    public const int UnitFieldCharm = 0x6;
    /// <summary>UNIT_FIELD_SUMMON (size 2); Public.</summary>
    public const int UnitFieldSummon = 0x8;
    /// <summary>UNIT_FIELD_CHARMEDBY (size 2); Public.</summary>
    public const int UnitFieldCharmedby = 0xA;
    /// <summary>UNIT_FIELD_SUMMONEDBY (size 2); Public.</summary>
    public const int UnitFieldSummonedby = 0xC;
    /// <summary>UNIT_FIELD_CREATEDBY (size 2); Public.</summary>
    public const int UnitFieldCreatedby = 0xE;
    /// <summary>UNIT_FIELD_TARGET (size 2); Public.</summary>
    public const int UnitFieldTarget = 0x10;
    /// <summary>UNIT_FIELD_PERSUADED (size 2); Public.</summary>
    public const int UnitFieldPersuaded = 0x12;
    /// <summary>UNIT_FIELD_CHANNEL_OBJECT (size 2); Public.</summary>
    public const int UnitFieldChannelObject = 0x14;
    /// <summary>UNIT_FIELD_HEALTH; Dynamic.</summary>
    public const int UnitFieldHealth = 0x16;
    /// <summary>UNIT_FIELD_POWER1; Public.</summary>
    public const int UnitFieldPower1 = 0x17;
    /// <summary>UNIT_FIELD_POWER2; Public.</summary>
    public const int UnitFieldPower2 = 0x18;
    /// <summary>UNIT_FIELD_POWER3; Public.</summary>
    public const int UnitFieldPower3 = 0x19;
    /// <summary>UNIT_FIELD_POWER4; Public.</summary>
    public const int UnitFieldPower4 = 0x1A;
    /// <summary>UNIT_FIELD_POWER5; Public.</summary>
    public const int UnitFieldPower5 = 0x1B;
    /// <summary>UNIT_FIELD_MAXHEALTH; Dynamic.</summary>
    public const int UnitFieldMaxhealth = 0x1C;
    /// <summary>UNIT_FIELD_MAXPOWER1; Public.</summary>
    public const int UnitFieldMaxpower1 = 0x1D;
    /// <summary>UNIT_FIELD_MAXPOWER2; Public.</summary>
    public const int UnitFieldMaxpower2 = 0x1E;
    /// <summary>UNIT_FIELD_MAXPOWER3; Public.</summary>
    public const int UnitFieldMaxpower3 = 0x1F;
    /// <summary>UNIT_FIELD_MAXPOWER4; Public.</summary>
    public const int UnitFieldMaxpower4 = 0x20;
    /// <summary>UNIT_FIELD_MAXPOWER5; Public.</summary>
    public const int UnitFieldMaxpower5 = 0x21;
    /// <summary>UNIT_FIELD_LEVEL; Public.</summary>
    public const int UnitFieldLevel = 0x22;
    /// <summary>UNIT_FIELD_FACTIONTEMPLATE; Public.</summary>
    public const int UnitFieldFactiontemplate = 0x23;
    /// <summary>UNIT_FIELD_BYTES_0; Public.</summary>
    public const int UnitFieldBytes0 = 0x24;
    /// <summary>UNIT_VIRTUAL_ITEM_SLOT_DISPLAY (size 3); Public.</summary>
    public const int UnitVirtualItemSlotDisplay = 0x25;
    /// <summary>UNIT_VIRTUAL_ITEM_INFO (size 6); Public.</summary>
    public const int UnitVirtualItemInfo = 0x28;
    /// <summary>UNIT_FIELD_FLAGS; Public.</summary>
    public const int UnitFieldFlags = 0x2E;
    /// <summary>UNIT_FIELD_AURA (size 48); Public.</summary>
    public const int UnitFieldAura = 0x2F;
    /// <summary>UNIT_FIELD_AURAFLAGS (size 6); Public.</summary>
    public const int UnitFieldAuraflags = 0x5F;
    /// <summary>UNIT_FIELD_AURALEVELS (size 12); Public.</summary>
    public const int UnitFieldAuralevels = 0x65;
    /// <summary>UNIT_FIELD_AURAAPPLICATIONS (size 12); Public.</summary>
    public const int UnitFieldAuraapplications = 0x71;
    /// <summary>UNIT_FIELD_AURASTATE; Public.</summary>
    public const int UnitFieldAurastate = 0x7D;
    /// <summary>UNIT_FIELD_BASEATTACKTIME (size 2); Public.</summary>
    public const int UnitFieldBaseattacktime = 0x7E;
    /// <summary>UNIT_FIELD_RANGEDATTACKTIME; Private.</summary>
    public const int UnitFieldRangedattacktime = 0x80;
    /// <summary>UNIT_FIELD_BOUNDINGRADIUS; Public.</summary>
    public const int UnitFieldBoundingradius = 0x81;
    /// <summary>UNIT_FIELD_COMBATREACH; Public.</summary>
    public const int UnitFieldCombatreach = 0x82;
    /// <summary>UNIT_FIELD_DISPLAYID; Public.</summary>
    public const int UnitFieldDisplayid = 0x83;
    /// <summary>UNIT_FIELD_NATIVEDISPLAYID; Public.</summary>
    public const int UnitFieldNativedisplayid = 0x84;
    /// <summary>UNIT_FIELD_MOUNTDISPLAYID; Public.</summary>
    public const int UnitFieldMountdisplayid = 0x85;
    /// <summary>UNIT_FIELD_MINDAMAGE; Private, OwnerOnly, SpecialInfo.</summary>
    public const int UnitFieldMindamage = 0x86;
    /// <summary>UNIT_FIELD_MAXDAMAGE; Private, OwnerOnly, SpecialInfo.</summary>
    public const int UnitFieldMaxdamage = 0x87;
    /// <summary>UNIT_FIELD_MINOFFHANDDAMAGE; Private, OwnerOnly, SpecialInfo.</summary>
    public const int UnitFieldMinoffhanddamage = 0x88;
    /// <summary>UNIT_FIELD_MAXOFFHANDDAMAGE; Private, OwnerOnly, SpecialInfo.</summary>
    public const int UnitFieldMaxoffhanddamage = 0x89;
    /// <summary>UNIT_FIELD_BYTES_1; Public.</summary>
    public const int UnitFieldBytes1 = 0x8A;
    /// <summary>UNIT_FIELD_PETNUMBER; Public.</summary>
    public const int UnitFieldPetnumber = 0x8B;
    /// <summary>UNIT_FIELD_PET_NAME_TIMESTAMP; Public.</summary>
    public const int UnitFieldPetNameTimestamp = 0x8C;
    /// <summary>UNIT_FIELD_PETEXPERIENCE; OwnerOnly.</summary>
    public const int UnitFieldPetexperience = 0x8D;
    /// <summary>UNIT_FIELD_PETNEXTLEVELEXP; OwnerOnly.</summary>
    public const int UnitFieldPetnextlevelexp = 0x8E;
    /// <summary>UNIT_DYNAMIC_FLAGS; Dynamic.</summary>
    public const int UnitDynamicFlags = 0x8F;
    /// <summary>UNIT_CHANNEL_SPELL; Public.</summary>
    public const int UnitChannelSpell = 0x90;
    /// <summary>UNIT_MOD_CAST_SPEED; Public.</summary>
    public const int UnitModCastSpeed = 0x91;
    /// <summary>UNIT_CREATED_BY_SPELL; Public.</summary>
    public const int UnitCreatedBySpell = 0x92;
    /// <summary>UNIT_NPC_FLAGS; Public.</summary>
    public const int UnitNpcFlags = 0x93;
    /// <summary>UNIT_NPC_EMOTESTATE; Public.</summary>
    public const int UnitNpcEmotestate = 0x94;
    /// <summary>UNIT_TRAINING_POINTS; OwnerOnly.</summary>
    public const int UnitTrainingPoints = 0x95;
    /// <summary>UNIT_FIELD_STAT0; Private, OwnerOnly.</summary>
    public const int UnitFieldStat0 = 0x96;
    /// <summary>UNIT_FIELD_STAT1; Private, OwnerOnly.</summary>
    public const int UnitFieldStat1 = 0x97;
    /// <summary>UNIT_FIELD_STAT2; Private, OwnerOnly.</summary>
    public const int UnitFieldStat2 = 0x98;
    /// <summary>UNIT_FIELD_STAT3; Private, OwnerOnly.</summary>
    public const int UnitFieldStat3 = 0x99;
    /// <summary>UNIT_FIELD_STAT4; Private, OwnerOnly.</summary>
    public const int UnitFieldStat4 = 0x9A;
    /// <summary>UNIT_FIELD_RESISTANCES (size 7); Private, OwnerOnly, SpecialInfo.</summary>
    public const int UnitFieldResistances = 0x9B;
    /// <summary>UNIT_FIELD_BASE_MANA; Private, OwnerOnly.</summary>
    public const int UnitFieldBaseMana = 0xA2;
    /// <summary>UNIT_FIELD_BASE_HEALTH; Private, OwnerOnly.</summary>
    public const int UnitFieldBaseHealth = 0xA3;
    /// <summary>UNIT_FIELD_BYTES_2; Public.</summary>
    public const int UnitFieldBytes2 = 0xA4;
    /// <summary>UNIT_FIELD_ATTACK_POWER; Private, OwnerOnly.</summary>
    public const int UnitFieldAttackPower = 0xA5;
    /// <summary>UNIT_FIELD_ATTACK_POWER_MODS; Private, OwnerOnly.</summary>
    public const int UnitFieldAttackPowerMods = 0xA6;
    /// <summary>UNIT_FIELD_ATTACK_POWER_MULTIPLIER; Private, OwnerOnly.</summary>
    public const int UnitFieldAttackPowerMultiplier = 0xA7;
    /// <summary>UNIT_FIELD_RANGED_ATTACK_POWER; Private, OwnerOnly.</summary>
    public const int UnitFieldRangedAttackPower = 0xA8;
    /// <summary>UNIT_FIELD_RANGED_ATTACK_POWER_MODS; Private, OwnerOnly.</summary>
    public const int UnitFieldRangedAttackPowerMods = 0xA9;
    /// <summary>UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER; Private, OwnerOnly.</summary>
    public const int UnitFieldRangedAttackPowerMultiplier = 0xAA;
    /// <summary>UNIT_FIELD_MINRANGEDDAMAGE; Private, OwnerOnly.</summary>
    public const int UnitFieldMinrangeddamage = 0xAB;
    /// <summary>UNIT_FIELD_MAXRANGEDDAMAGE; Private, OwnerOnly.</summary>
    public const int UnitFieldMaxrangeddamage = 0xAC;
    /// <summary>UNIT_FIELD_POWER_COST_MODIFIER (size 7); Private, OwnerOnly.</summary>
    public const int UnitFieldPowerCostModifier = 0xAD;
    /// <summary>UNIT_FIELD_POWER_COST_MULTIPLIER (size 7); Private, OwnerOnly.</summary>
    public const int UnitFieldPowerCostMultiplier = 0xB4;
    /// <summary>UNIT_FIELD_PADDING; None.</summary>
    public const int UnitFieldPadding = 0xBB;
    /// <summary>UNIT_END; None.</summary>
    public const int UnitEnd = 0xBC;
    /// <summary>PLAYER_DUEL_ARBITER (size 2); Public.</summary>
    public const int PlayerDuelArbiter = 0xBC;
    /// <summary>PLAYER_FLAGS; Public.</summary>
    public const int PlayerFlags = 0xBE;
    /// <summary>PLAYER_GUILDID; Public.</summary>
    public const int PlayerGuildid = 0xBF;
    /// <summary>PLAYER_GUILDRANK; Public.</summary>
    public const int PlayerGuildrank = 0xC0;
    /// <summary>PLAYER_BYTES; Public.</summary>
    public const int PlayerBytes = 0xC1;
    /// <summary>PLAYER_BYTES_2; Public.</summary>
    public const int PlayerBytes2 = 0xC2;
    /// <summary>PLAYER_BYTES_3; Public.</summary>
    public const int PlayerBytes3 = 0xC3;
    /// <summary>PLAYER_DUEL_TEAM; Public.</summary>
    public const int PlayerDuelTeam = 0xC4;
    /// <summary>PLAYER_GUILD_TIMESTAMP; Public.</summary>
    public const int PlayerGuildTimestamp = 0xC5;
    /// <summary>PLAYER_QUEST_LOG_1_1; GroupOnly.</summary>
    public const int PlayerQuestLog11 = 0xC6;
    /// <summary>PLAYER_QUEST_LOG_1_2 (size 2); Private.</summary>
    public const int PlayerQuestLog12 = 0xC7;
    /// <summary>PLAYER_QUEST_LOG_2_1; GroupOnly.</summary>
    public const int PlayerQuestLog21 = 0xC9;
    /// <summary>PLAYER_QUEST_LOG_2_2 (size 2); Private.</summary>
    public const int PlayerQuestLog22 = 0xCA;
    /// <summary>PLAYER_QUEST_LOG_3_1; GroupOnly.</summary>
    public const int PlayerQuestLog31 = 0xCC;
    /// <summary>PLAYER_QUEST_LOG_3_2 (size 2); Private.</summary>
    public const int PlayerQuestLog32 = 0xCD;
    /// <summary>PLAYER_QUEST_LOG_4_1; GroupOnly.</summary>
    public const int PlayerQuestLog41 = 0xCF;
    /// <summary>PLAYER_QUEST_LOG_4_2 (size 2); Private.</summary>
    public const int PlayerQuestLog42 = 0xD0;
    /// <summary>PLAYER_QUEST_LOG_5_1; GroupOnly.</summary>
    public const int PlayerQuestLog51 = 0xD2;
    /// <summary>PLAYER_QUEST_LOG_5_2 (size 2); Private.</summary>
    public const int PlayerQuestLog52 = 0xD3;
    /// <summary>PLAYER_QUEST_LOG_6_1; GroupOnly.</summary>
    public const int PlayerQuestLog61 = 0xD5;
    /// <summary>PLAYER_QUEST_LOG_6_2 (size 2); Private.</summary>
    public const int PlayerQuestLog62 = 0xD6;
    /// <summary>PLAYER_QUEST_LOG_7_1; GroupOnly.</summary>
    public const int PlayerQuestLog71 = 0xD8;
    /// <summary>PLAYER_QUEST_LOG_7_2 (size 2); Private.</summary>
    public const int PlayerQuestLog72 = 0xD9;
    /// <summary>PLAYER_QUEST_LOG_8_1; GroupOnly.</summary>
    public const int PlayerQuestLog81 = 0xDB;
    /// <summary>PLAYER_QUEST_LOG_8_2 (size 2); Private.</summary>
    public const int PlayerQuestLog82 = 0xDC;
    /// <summary>PLAYER_QUEST_LOG_9_1; GroupOnly.</summary>
    public const int PlayerQuestLog91 = 0xDE;
    /// <summary>PLAYER_QUEST_LOG_9_2 (size 2); Private.</summary>
    public const int PlayerQuestLog92 = 0xDF;
    /// <summary>PLAYER_QUEST_LOG_10_1; GroupOnly.</summary>
    public const int PlayerQuestLog101 = 0xE1;
    /// <summary>PLAYER_QUEST_LOG_10_2 (size 2); Private.</summary>
    public const int PlayerQuestLog102 = 0xE2;
    /// <summary>PLAYER_QUEST_LOG_11_1; GroupOnly.</summary>
    public const int PlayerQuestLog111 = 0xE4;
    /// <summary>PLAYER_QUEST_LOG_11_2 (size 2); Private.</summary>
    public const int PlayerQuestLog112 = 0xE5;
    /// <summary>PLAYER_QUEST_LOG_12_1; GroupOnly.</summary>
    public const int PlayerQuestLog121 = 0xE7;
    /// <summary>PLAYER_QUEST_LOG_12_2 (size 2); Private.</summary>
    public const int PlayerQuestLog122 = 0xE8;
    /// <summary>PLAYER_QUEST_LOG_13_1; GroupOnly.</summary>
    public const int PlayerQuestLog131 = 0xEA;
    /// <summary>PLAYER_QUEST_LOG_13_2 (size 2); Private.</summary>
    public const int PlayerQuestLog132 = 0xEB;
    /// <summary>PLAYER_QUEST_LOG_14_1; GroupOnly.</summary>
    public const int PlayerQuestLog141 = 0xED;
    /// <summary>PLAYER_QUEST_LOG_14_2 (size 2); Private.</summary>
    public const int PlayerQuestLog142 = 0xEE;
    /// <summary>PLAYER_QUEST_LOG_15_1; GroupOnly.</summary>
    public const int PlayerQuestLog151 = 0xF0;
    /// <summary>PLAYER_QUEST_LOG_15_2 (size 2); Private.</summary>
    public const int PlayerQuestLog152 = 0xF1;
    /// <summary>PLAYER_QUEST_LOG_16_1; GroupOnly.</summary>
    public const int PlayerQuestLog161 = 0xF3;
    /// <summary>PLAYER_QUEST_LOG_16_2 (size 2); Private.</summary>
    public const int PlayerQuestLog162 = 0xF4;
    /// <summary>PLAYER_QUEST_LOG_17_1; GroupOnly.</summary>
    public const int PlayerQuestLog171 = 0xF6;
    /// <summary>PLAYER_QUEST_LOG_17_2 (size 2); Private.</summary>
    public const int PlayerQuestLog172 = 0xF7;
    /// <summary>PLAYER_QUEST_LOG_18_1; GroupOnly.</summary>
    public const int PlayerQuestLog181 = 0xF9;
    /// <summary>PLAYER_QUEST_LOG_18_2 (size 2); Private.</summary>
    public const int PlayerQuestLog182 = 0xFA;
    /// <summary>PLAYER_QUEST_LOG_19_1; GroupOnly.</summary>
    public const int PlayerQuestLog191 = 0xFC;
    /// <summary>PLAYER_QUEST_LOG_19_2 (size 2); Private.</summary>
    public const int PlayerQuestLog192 = 0xFD;
    /// <summary>PLAYER_QUEST_LOG_20_1; GroupOnly.</summary>
    public const int PlayerQuestLog201 = 0xFF;
    /// <summary>PLAYER_QUEST_LOG_20_2 (size 2); Private.</summary>
    public const int PlayerQuestLog202 = 0x100;
    /// <summary>PLAYER_VISIBLE_ITEM_1_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem1Creator = 0x102;
    /// <summary>PLAYER_VISIBLE_ITEM_1_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem10 = 0x104;
    /// <summary>PLAYER_VISIBLE_ITEM_1_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem1Properties = 0x10C;
    /// <summary>PLAYER_VISIBLE_ITEM_1_PAD; Public.</summary>
    public const int PlayerVisibleItem1Pad = 0x10D;
    /// <summary>PLAYER_VISIBLE_ITEM_2_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem2Creator = 0x10E;
    /// <summary>PLAYER_VISIBLE_ITEM_2_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem20 = 0x110;
    /// <summary>PLAYER_VISIBLE_ITEM_2_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem2Properties = 0x118;
    /// <summary>PLAYER_VISIBLE_ITEM_2_PAD; Public.</summary>
    public const int PlayerVisibleItem2Pad = 0x119;
    /// <summary>PLAYER_VISIBLE_ITEM_3_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem3Creator = 0x11A;
    /// <summary>PLAYER_VISIBLE_ITEM_3_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem30 = 0x11C;
    /// <summary>PLAYER_VISIBLE_ITEM_3_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem3Properties = 0x124;
    /// <summary>PLAYER_VISIBLE_ITEM_3_PAD; Public.</summary>
    public const int PlayerVisibleItem3Pad = 0x125;
    /// <summary>PLAYER_VISIBLE_ITEM_4_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem4Creator = 0x126;
    /// <summary>PLAYER_VISIBLE_ITEM_4_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem40 = 0x128;
    /// <summary>PLAYER_VISIBLE_ITEM_4_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem4Properties = 0x130;
    /// <summary>PLAYER_VISIBLE_ITEM_4_PAD; Public.</summary>
    public const int PlayerVisibleItem4Pad = 0x131;
    /// <summary>PLAYER_VISIBLE_ITEM_5_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem5Creator = 0x132;
    /// <summary>PLAYER_VISIBLE_ITEM_5_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem50 = 0x134;
    /// <summary>PLAYER_VISIBLE_ITEM_5_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem5Properties = 0x13C;
    /// <summary>PLAYER_VISIBLE_ITEM_5_PAD; Public.</summary>
    public const int PlayerVisibleItem5Pad = 0x13D;
    /// <summary>PLAYER_VISIBLE_ITEM_6_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem6Creator = 0x13E;
    /// <summary>PLAYER_VISIBLE_ITEM_6_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem60 = 0x140;
    /// <summary>PLAYER_VISIBLE_ITEM_6_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem6Properties = 0x148;
    /// <summary>PLAYER_VISIBLE_ITEM_6_PAD; Public.</summary>
    public const int PlayerVisibleItem6Pad = 0x149;
    /// <summary>PLAYER_VISIBLE_ITEM_7_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem7Creator = 0x14A;
    /// <summary>PLAYER_VISIBLE_ITEM_7_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem70 = 0x14C;
    /// <summary>PLAYER_VISIBLE_ITEM_7_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem7Properties = 0x154;
    /// <summary>PLAYER_VISIBLE_ITEM_7_PAD; Public.</summary>
    public const int PlayerVisibleItem7Pad = 0x155;
    /// <summary>PLAYER_VISIBLE_ITEM_8_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem8Creator = 0x156;
    /// <summary>PLAYER_VISIBLE_ITEM_8_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem80 = 0x158;
    /// <summary>PLAYER_VISIBLE_ITEM_8_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem8Properties = 0x160;
    /// <summary>PLAYER_VISIBLE_ITEM_8_PAD; Public.</summary>
    public const int PlayerVisibleItem8Pad = 0x161;
    /// <summary>PLAYER_VISIBLE_ITEM_9_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem9Creator = 0x162;
    /// <summary>PLAYER_VISIBLE_ITEM_9_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem90 = 0x164;
    /// <summary>PLAYER_VISIBLE_ITEM_9_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem9Properties = 0x16C;
    /// <summary>PLAYER_VISIBLE_ITEM_9_PAD; Public.</summary>
    public const int PlayerVisibleItem9Pad = 0x16D;
    /// <summary>PLAYER_VISIBLE_ITEM_10_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem10Creator = 0x16E;
    /// <summary>PLAYER_VISIBLE_ITEM_10_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem100 = 0x170;
    /// <summary>PLAYER_VISIBLE_ITEM_10_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem10Properties = 0x178;
    /// <summary>PLAYER_VISIBLE_ITEM_10_PAD; Public.</summary>
    public const int PlayerVisibleItem10Pad = 0x179;
    /// <summary>PLAYER_VISIBLE_ITEM_11_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem11Creator = 0x17A;
    /// <summary>PLAYER_VISIBLE_ITEM_11_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem110 = 0x17C;
    /// <summary>PLAYER_VISIBLE_ITEM_11_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem11Properties = 0x184;
    /// <summary>PLAYER_VISIBLE_ITEM_11_PAD; Public.</summary>
    public const int PlayerVisibleItem11Pad = 0x185;
    /// <summary>PLAYER_VISIBLE_ITEM_12_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem12Creator = 0x186;
    /// <summary>PLAYER_VISIBLE_ITEM_12_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem120 = 0x188;
    /// <summary>PLAYER_VISIBLE_ITEM_12_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem12Properties = 0x190;
    /// <summary>PLAYER_VISIBLE_ITEM_12_PAD; Public.</summary>
    public const int PlayerVisibleItem12Pad = 0x191;
    /// <summary>PLAYER_VISIBLE_ITEM_13_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem13Creator = 0x192;
    /// <summary>PLAYER_VISIBLE_ITEM_13_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem130 = 0x194;
    /// <summary>PLAYER_VISIBLE_ITEM_13_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem13Properties = 0x19C;
    /// <summary>PLAYER_VISIBLE_ITEM_13_PAD; Public.</summary>
    public const int PlayerVisibleItem13Pad = 0x19D;
    /// <summary>PLAYER_VISIBLE_ITEM_14_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem14Creator = 0x19E;
    /// <summary>PLAYER_VISIBLE_ITEM_14_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem140 = 0x1A0;
    /// <summary>PLAYER_VISIBLE_ITEM_14_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem14Properties = 0x1A8;
    /// <summary>PLAYER_VISIBLE_ITEM_14_PAD; Public.</summary>
    public const int PlayerVisibleItem14Pad = 0x1A9;
    /// <summary>PLAYER_VISIBLE_ITEM_15_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem15Creator = 0x1AA;
    /// <summary>PLAYER_VISIBLE_ITEM_15_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem150 = 0x1AC;
    /// <summary>PLAYER_VISIBLE_ITEM_15_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem15Properties = 0x1B4;
    /// <summary>PLAYER_VISIBLE_ITEM_15_PAD; Public.</summary>
    public const int PlayerVisibleItem15Pad = 0x1B5;
    /// <summary>PLAYER_VISIBLE_ITEM_16_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem16Creator = 0x1B6;
    /// <summary>PLAYER_VISIBLE_ITEM_16_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem160 = 0x1B8;
    /// <summary>PLAYER_VISIBLE_ITEM_16_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem16Properties = 0x1C0;
    /// <summary>PLAYER_VISIBLE_ITEM_16_PAD; Public.</summary>
    public const int PlayerVisibleItem16Pad = 0x1C1;
    /// <summary>PLAYER_VISIBLE_ITEM_17_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem17Creator = 0x1C2;
    /// <summary>PLAYER_VISIBLE_ITEM_17_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem170 = 0x1C4;
    /// <summary>PLAYER_VISIBLE_ITEM_17_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem17Properties = 0x1CC;
    /// <summary>PLAYER_VISIBLE_ITEM_17_PAD; Public.</summary>
    public const int PlayerVisibleItem17Pad = 0x1CD;
    /// <summary>PLAYER_VISIBLE_ITEM_18_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem18Creator = 0x1CE;
    /// <summary>PLAYER_VISIBLE_ITEM_18_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem180 = 0x1D0;
    /// <summary>PLAYER_VISIBLE_ITEM_18_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem18Properties = 0x1D8;
    /// <summary>PLAYER_VISIBLE_ITEM_18_PAD; Public.</summary>
    public const int PlayerVisibleItem18Pad = 0x1D9;
    /// <summary>PLAYER_VISIBLE_ITEM_19_CREATOR (size 2); Public.</summary>
    public const int PlayerVisibleItem19Creator = 0x1DA;
    /// <summary>PLAYER_VISIBLE_ITEM_19_0 (size 8); Public.</summary>
    public const int PlayerVisibleItem190 = 0x1DC;
    /// <summary>PLAYER_VISIBLE_ITEM_19_PROPERTIES; Public.</summary>
    public const int PlayerVisibleItem19Properties = 0x1E4;
    /// <summary>PLAYER_VISIBLE_ITEM_19_PAD; Public.</summary>
    public const int PlayerVisibleItem19Pad = 0x1E5;
    /// <summary>PLAYER_FIELD_INV_SLOT_HEAD (size 46); Private.</summary>
    public const int PlayerFieldInvSlotHead = 0x1E6;
    /// <summary>PLAYER_FIELD_PACK_SLOT_1 (size 32); Private.</summary>
    public const int PlayerFieldPackSlot1 = 0x214;
    /// <summary>PLAYER_FIELD_BANK_SLOT_1 (size 48); Private.</summary>
    public const int PlayerFieldBankSlot1 = 0x234;
    /// <summary>PLAYER_FIELD_BANKBAG_SLOT_1 (size 12); Private.</summary>
    public const int PlayerFieldBankbagSlot1 = 0x264;
    /// <summary>PLAYER_FIELD_VENDORBUYBACK_SLOT_1 (size 24); Private.</summary>
    public const int PlayerFieldVendorbuybackSlot1 = 0x270;
    /// <summary>PLAYER_FIELD_KEYRING_SLOT_1 (size 64); Private.</summary>
    public const int PlayerFieldKeyringSlot1 = 0x288;
    /// <summary>PLAYER_FARSIGHT (size 2); Private.</summary>
    public const int PlayerFarsight = 0x2C8;
    /// <summary>PLAYER__FIELD_COMBO_TARGET (size 2); Private.</summary>
    public const int PlayerFieldComboTarget = 0x2CA;
    /// <summary>PLAYER_XP; Private.</summary>
    public const int PlayerXp = 0x2CC;
    /// <summary>PLAYER_NEXT_LEVEL_XP; Private.</summary>
    public const int PlayerNextLevelXp = 0x2CD;
    /// <summary>PLAYER_SKILL_INFO_1_1 (size 384); Private.</summary>
    public const int PlayerSkillInfo11 = 0x2CE;
    /// <summary>PLAYER_CHARACTER_POINTS1; Private.</summary>
    public const int PlayerCharacterPoints1 = 0x44E;
    /// <summary>PLAYER_CHARACTER_POINTS2; Private.</summary>
    public const int PlayerCharacterPoints2 = 0x44F;
    /// <summary>PLAYER_TRACK_CREATURES; Private.</summary>
    public const int PlayerTrackCreatures = 0x450;
    /// <summary>PLAYER_TRACK_RESOURCES; Private.</summary>
    public const int PlayerTrackResources = 0x451;
    /// <summary>PLAYER_BLOCK_PERCENTAGE; Private.</summary>
    public const int PlayerBlockPercentage = 0x452;
    /// <summary>PLAYER_DODGE_PERCENTAGE; Private.</summary>
    public const int PlayerDodgePercentage = 0x453;
    /// <summary>PLAYER_PARRY_PERCENTAGE; Private.</summary>
    public const int PlayerParryPercentage = 0x454;
    /// <summary>PLAYER_CRIT_PERCENTAGE; Private.</summary>
    public const int PlayerCritPercentage = 0x455;
    /// <summary>PLAYER_RANGED_CRIT_PERCENTAGE; Private.</summary>
    public const int PlayerRangedCritPercentage = 0x456;
    /// <summary>PLAYER_EXPLORED_ZONES_1 (size 64); Private.</summary>
    public const int PlayerExploredZones1 = 0x457;
    /// <summary>PLAYER_REST_STATE_EXPERIENCE; Private.</summary>
    public const int PlayerRestStateExperience = 0x497;
    /// <summary>PLAYER_FIELD_COINAGE; Private.</summary>
    public const int PlayerFieldCoinage = 0x498;
    /// <summary>PLAYER_FIELD_POSSTAT0; Private.</summary>
    public const int PlayerFieldPosstat0 = 0x499;
    /// <summary>PLAYER_FIELD_POSSTAT1; Private.</summary>
    public const int PlayerFieldPosstat1 = 0x49A;
    /// <summary>PLAYER_FIELD_POSSTAT2; Private.</summary>
    public const int PlayerFieldPosstat2 = 0x49B;
    /// <summary>PLAYER_FIELD_POSSTAT3; Private.</summary>
    public const int PlayerFieldPosstat3 = 0x49C;
    /// <summary>PLAYER_FIELD_POSSTAT4; Private.</summary>
    public const int PlayerFieldPosstat4 = 0x49D;
    /// <summary>PLAYER_FIELD_NEGSTAT0; Private.</summary>
    public const int PlayerFieldNegstat0 = 0x49E;
    /// <summary>PLAYER_FIELD_NEGSTAT1; Private.</summary>
    public const int PlayerFieldNegstat1 = 0x49F;
    /// <summary>PLAYER_FIELD_NEGSTAT2; Private.</summary>
    public const int PlayerFieldNegstat2 = 0x4A0;
    /// <summary>PLAYER_FIELD_NEGSTAT3; Private.</summary>
    public const int PlayerFieldNegstat3 = 0x4A1;
    /// <summary>PLAYER_FIELD_NEGSTAT4; Private.</summary>
    public const int PlayerFieldNegstat4 = 0x4A2;
    /// <summary>PLAYER_FIELD_RESISTANCEBUFFMODSPOSITIVE (size 7); Private.</summary>
    public const int PlayerFieldResistancebuffmodspositive = 0x4A3;
    /// <summary>PLAYER_FIELD_RESISTANCEBUFFMODSNEGATIVE (size 7); Private.</summary>
    public const int PlayerFieldResistancebuffmodsnegative = 0x4AA;
    /// <summary>PLAYER_FIELD_MOD_DAMAGE_DONE_POS (size 7); Private.</summary>
    public const int PlayerFieldModDamageDonePos = 0x4B1;
    /// <summary>PLAYER_FIELD_MOD_DAMAGE_DONE_NEG (size 7); Private.</summary>
    public const int PlayerFieldModDamageDoneNeg = 0x4B8;
    /// <summary>PLAYER_FIELD_MOD_DAMAGE_DONE_PCT (size 7); Private.</summary>
    public const int PlayerFieldModDamageDonePct = 0x4BF;
    /// <summary>PLAYER_FIELD_BYTES; Private.</summary>
    public const int PlayerFieldBytes = 0x4C6;
    /// <summary>PLAYER_AMMO_ID; Private.</summary>
    public const int PlayerAmmoId = 0x4C7;
    /// <summary>PLAYER_SELF_RES_SPELL; Private.</summary>
    public const int PlayerSelfResSpell = 0x4C8;
    /// <summary>PLAYER_FIELD_PVP_MEDALS; Private.</summary>
    public const int PlayerFieldPvpMedals = 0x4C9;
    /// <summary>PLAYER_FIELD_BUYBACK_PRICE_1 (size 12); Private.</summary>
    public const int PlayerFieldBuybackPrice1 = 0x4CA;
    /// <summary>PLAYER_FIELD_BUYBACK_TIMESTAMP_1 (size 12); Private.</summary>
    public const int PlayerFieldBuybackTimestamp1 = 0x4D6;
    /// <summary>PLAYER_FIELD_SESSION_KILLS; Private.</summary>
    public const int PlayerFieldSessionKills = 0x4E2;
    /// <summary>PLAYER_FIELD_YESTERDAY_KILLS; Private.</summary>
    public const int PlayerFieldYesterdayKills = 0x4E3;
    /// <summary>PLAYER_FIELD_LAST_WEEK_KILLS; Private.</summary>
    public const int PlayerFieldLastWeekKills = 0x4E4;
    /// <summary>PLAYER_FIELD_THIS_WEEK_KILLS; Private.</summary>
    public const int PlayerFieldThisWeekKills = 0x4E5;
    /// <summary>PLAYER_FIELD_THIS_WEEK_CONTRIBUTION; Private.</summary>
    public const int PlayerFieldThisWeekContribution = 0x4E6;
    /// <summary>PLAYER_FIELD_LIFETIME_HONORBALE_KILLS; Private.</summary>
    public const int PlayerFieldLifetimeHonorbaleKills = 0x4E7;
    /// <summary>PLAYER_FIELD_LIFETIME_DISHONORBALE_KILLS; Private.</summary>
    public const int PlayerFieldLifetimeDishonorbaleKills = 0x4E8;
    /// <summary>PLAYER_FIELD_YESTERDAY_CONTRIBUTION; Private.</summary>
    public const int PlayerFieldYesterdayContribution = 0x4E9;
    /// <summary>PLAYER_FIELD_LAST_WEEK_CONTRIBUTION; Private.</summary>
    public const int PlayerFieldLastWeekContribution = 0x4EA;
    /// <summary>PLAYER_FIELD_LAST_WEEK_RANK; Private.</summary>
    public const int PlayerFieldLastWeekRank = 0x4EB;
    /// <summary>PLAYER_FIELD_BYTES2; Private.</summary>
    public const int PlayerFieldBytes2 = 0x4EC;
    /// <summary>PLAYER_FIELD_WATCHED_FACTION_INDEX; Private.</summary>
    public const int PlayerFieldWatchedFactionIndex = 0x4ED;
    /// <summary>PLAYER_FIELD_COMBAT_RATING_1 (size 20); Private.</summary>
    public const int PlayerFieldCombatRating1 = 0x4EE;
    /// <summary>PLAYER_END; None.</summary>
    public const int PlayerEnd = 0x502;
    /// <summary>OBJECT_FIELD_CREATED_BY (size 2); Public.</summary>
    public const int ObjectFieldCreatedBy = 0x6;
    /// <summary>GAMEOBJECT_DISPLAYID; Public.</summary>
    public const int GameobjectDisplayid = 0x8;
    /// <summary>GAMEOBJECT_FLAGS; Public.</summary>
    public const int GameobjectFlags = 0x9;
    /// <summary>GAMEOBJECT_ROTATION (size 4); Public.</summary>
    public const int GameobjectRotation = 0xA;
    /// <summary>GAMEOBJECT_STATE; Public.</summary>
    public const int GameobjectState = 0xE;
    /// <summary>GAMEOBJECT_POS_X; Public.</summary>
    public const int GameobjectPosX = 0xF;
    /// <summary>GAMEOBJECT_POS_Y; Public.</summary>
    public const int GameobjectPosY = 0x10;
    /// <summary>GAMEOBJECT_POS_Z; Public.</summary>
    public const int GameobjectPosZ = 0x11;
    /// <summary>GAMEOBJECT_FACING; Public.</summary>
    public const int GameobjectFacing = 0x12;
    /// <summary>GAMEOBJECT_DYN_FLAGS; Dynamic.</summary>
    public const int GameobjectDynFlags = 0x13;
    /// <summary>GAMEOBJECT_FACTION; Public.</summary>
    public const int GameobjectFaction = 0x14;
    /// <summary>GAMEOBJECT_TYPE_ID; Public.</summary>
    public const int GameobjectTypeId = 0x15;
    /// <summary>GAMEOBJECT_LEVEL; Public.</summary>
    public const int GameobjectLevel = 0x16;
    /// <summary>GAMEOBJECT_ARTKIT; Public.</summary>
    public const int GameobjectArtkit = 0x17;
    /// <summary>GAMEOBJECT_ANIMPROGRESS; Dynamic.</summary>
    public const int GameobjectAnimprogress = 0x18;
    /// <summary>GAMEOBJECT_PADDING; None.</summary>
    public const int GameobjectPadding = 0x19;
    /// <summary>GAMEOBJECT_END; None.</summary>
    public const int GameobjectEnd = 0x1A;
    /// <summary>DYNAMICOBJECT_CASTER (size 2); Public.</summary>
    public const int DynamicobjectCaster = 0x6;
    /// <summary>DYNAMICOBJECT_BYTES; Public.</summary>
    public const int DynamicobjectBytes = 0x8;
    /// <summary>DYNAMICOBJECT_SPELLID; Public.</summary>
    public const int DynamicobjectSpellid = 0x9;
    /// <summary>DYNAMICOBJECT_RADIUS; Public.</summary>
    public const int DynamicobjectRadius = 0xA;
    /// <summary>DYNAMICOBJECT_POS_X; Public.</summary>
    public const int DynamicobjectPosX = 0xB;
    /// <summary>DYNAMICOBJECT_POS_Y; Public.</summary>
    public const int DynamicobjectPosY = 0xC;
    /// <summary>DYNAMICOBJECT_POS_Z; Public.</summary>
    public const int DynamicobjectPosZ = 0xD;
    /// <summary>DYNAMICOBJECT_FACING; Public.</summary>
    public const int DynamicobjectFacing = 0xE;
    /// <summary>DYNAMICOBJECT_PAD; Public.</summary>
    public const int DynamicobjectPad = 0xF;
    /// <summary>DYNAMICOBJECT_END; None.</summary>
    public const int DynamicobjectEnd = 0x10;
    /// <summary>CORPSE_FIELD_OWNER (size 2); Public.</summary>
    public const int CorpseFieldOwner = 0x6;
    /// <summary>CORPSE_FIELD_FACING; Public.</summary>
    public const int CorpseFieldFacing = 0x8;
    /// <summary>CORPSE_FIELD_POS_X; Public.</summary>
    public const int CorpseFieldPosX = 0x9;
    /// <summary>CORPSE_FIELD_POS_Y; Public.</summary>
    public const int CorpseFieldPosY = 0xA;
    /// <summary>CORPSE_FIELD_POS_Z; Public.</summary>
    public const int CorpseFieldPosZ = 0xB;
    /// <summary>CORPSE_FIELD_DISPLAY_ID; Public.</summary>
    public const int CorpseFieldDisplayId = 0xC;
    /// <summary>CORPSE_FIELD_ITEM (size 19); Public.</summary>
    public const int CorpseFieldItem = 0xD;
    /// <summary>CORPSE_FIELD_BYTES_1; Public.</summary>
    public const int CorpseFieldBytes1 = 0x20;
    /// <summary>CORPSE_FIELD_BYTES_2; Public.</summary>
    public const int CorpseFieldBytes2 = 0x21;
    /// <summary>CORPSE_FIELD_GUILD; Public.</summary>
    public const int CorpseFieldGuild = 0x22;
    /// <summary>CORPSE_FIELD_FLAGS; Public.</summary>
    public const int CorpseFieldFlags = 0x23;
    /// <summary>CORPSE_FIELD_DYNAMIC_FLAGS; Dynamic.</summary>
    public const int CorpseFieldDynamicFlags = 0x24;
    /// <summary>CORPSE_FIELD_PAD; None.</summary>
    public const int CorpseFieldPad = 0x25;
    /// <summary>CORPSE_END; None.</summary>
    public const int CorpseEnd = 0x26;
}

/// <summary>
/// Who may receive an update field (vmangos UpdateFieldFlags). <see cref="ItemOwner"/> is
/// vmangos UF_FLAG_UNK2, which it grants together with OwnerOnly to an item's owner.
/// </summary>
[Flags]
public enum UpdateFieldFlags : ushort
{
    None = 0x000,
    Public = 0x001,
    Private = 0x002,
    OwnerOnly = 0x004,
    Unk1 = 0x008,
    ItemOwner = 0x010,
    SpecialInfo = 0x020,
    GroupOnly = 0x040,
    Unk5 = 0x080,
    Dynamic = 0x100,
}

/// <summary>Per-object-type visibility flags and GUID-pair starts, one entry per field index.</summary>
public static class UpdateFieldTables
{
    /// <summary>Visibility flags — Items and containers (indexed up to CONTAINER_END).</summary>
    public static ReadOnlySpan<ushort> ContainerVisibility => new ushort[]
    {
        0x001, 0x001, 0x001, 0x001, 0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x014, 0x014,
        0x014, 0x014, 0x014, 0x014, 0x014, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x004, 0x014, 0x014,
        0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
    };

    /// <summary>True at the low half of each 64-bit GUID field — Items and containers (indexed up to CONTAINER_END).</summary>
    public static ReadOnlySpan<bool> ContainerGuidStarts => new bool[]
    {
        true, false, false, false, false, false, true, false, true, false, true, false, true, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false,
    };

    /// <summary>Visibility flags — Units and players (indexed up to PLAYER_END).</summary>
    public static ReadOnlySpan<ushort> UnitVisibility => new ushort[]
    {
        0x001, 0x001, 0x001, 0x001, 0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x100, 0x001, 0x001, 0x001, 0x001, 0x001, 0x100, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x002, 0x001, 0x001, 0x001, 0x001, 0x001, 0x026, 0x026, 0x026, 0x026, 0x001, 0x001, 0x001, 0x004, 0x004, 0x100,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x004, 0x006, 0x006, 0x006, 0x006, 0x006, 0x026, 0x026, 0x026, 0x026, 0x026,
        0x026, 0x026, 0x006, 0x006, 0x001, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006,
        0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x006, 0x000, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040,
        0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002,
        0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002,
        0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040, 0x002, 0x002, 0x040,
        0x002, 0x002, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002, 0x002,
        0x002, 0x002,
    };

    /// <summary>True at the low half of each 64-bit GUID field — Units and players (indexed up to PLAYER_END).</summary>
    public static ReadOnlySpan<bool> UnitGuidStarts => new bool[]
    {
        true, false, false, false, false, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false,
        false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
        false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false,
        false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
        false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false,
        false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
        false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false,
        false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
        false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false,
        false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false,
        false, false, false, false, false, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false,
        true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false,
    };

    /// <summary>Visibility flags — Game objects (indexed up to GAMEOBJECT_END).</summary>
    public static ReadOnlySpan<ushort> GameObjectVisibility => new ushort[]
    {
        0x001, 0x001, 0x001, 0x001, 0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x100, 0x001, 0x001, 0x001, 0x001, 0x100, 0x000,
    };

    /// <summary>True at the low half of each 64-bit GUID field — Game objects (indexed up to GAMEOBJECT_END).</summary>
    public static ReadOnlySpan<bool> GameObjectGuidStarts => new bool[]
    {
        true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false,
    };

    /// <summary>Visibility flags — Dynamic objects (indexed up to DYNAMICOBJECT_END).</summary>
    public static ReadOnlySpan<ushort> DynamicObjectVisibility => new ushort[]
    {
        0x001, 0x001, 0x001, 0x001, 0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
    };

    /// <summary>True at the low half of each 64-bit GUID field — Dynamic objects (indexed up to DYNAMICOBJECT_END).</summary>
    public static ReadOnlySpan<bool> DynamicObjectGuidStarts => new bool[]
    {
        true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
    };

    /// <summary>Visibility flags — Corpses (indexed up to CORPSE_END).</summary>
    public static ReadOnlySpan<ushort> CorpseVisibility => new ushort[]
    {
        0x001, 0x001, 0x001, 0x001, 0x001, 0x000, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001, 0x001,
        0x001, 0x001, 0x001, 0x001, 0x100, 0x000,
    };

    /// <summary>True at the low half of each 64-bit GUID field — Corpses (indexed up to CORPSE_END).</summary>
    public static ReadOnlySpan<bool> CorpseGuidStarts => new bool[]
    {
        true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false,
    };
}
