#!/usr/bin/env python3
"""Generate build-5875 DBC metadata from WoWDBDefs definitions.

WoWDBDefs commit e3df370: definitions are CC BY-SA 4.0; repository code is
BSD-3-Clause. This parser is original code; no .dbd files are vendored.
See THIRD_PARTY_NOTICES.md. The vmangos DBCfmt.h transcriptions in
ClientDbcLayouts.cs remain authoritative when both sources describe a file.
"""

import argparse
from pathlib import Path
import re


BUILD = (1, 12, 1, 5875)
ROOT = Path(__file__).resolve().parents[2]
CLIENT_DATA = ROOT / 'src' / 'ArcaneCore.Data' / 'ClientData'
FIELD = re.compile(r"^(?:\$[^$]+\$)?([\w?]+)(?:<([^>]+)>)?(?:\[(\d+)\])?$")
COLUMN = re.compile(r"^(int|float|string|locstring)(?:<([^>]+)>)?\s+([\w?]+)$")
VMANGOS = re.compile(r'\b[VA]\("([^"]+\.dbc)",\s*(?:"([^"]+)"|(\d+))')
PACKED = re.compile(r'\bA\("([^"]+\.dbc)",\s*\d+,[^\n]*?packedRecordSize:\s*(\d+)')


def covers(spec):
    for part in spec.split(','):
        ends = part.strip().split('-')
        if len(ends) not in (1, 2):
            raise ValueError(f"bad BUILD range: {part}")
        versions = [tuple(map(int, end.split('.'))) for end in ends]
        if any(len(version) != 4 for version in versions):
            raise ValueError(f"bad BUILD version: {part}")
        if versions[0] <= BUILD <= versions[-1]:
            return True
    return False


def parse(path):
    columns = {}
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    selected = []
    in_columns = False
    builds = []
    fields = []

    def finish():
        if builds and any(covers(build) for build in builds):
            if not fields:
                raise ValueError(f"{path.name}: matching BUILD has no fields")
            selected.append(tuple(fields))

    for raw in lines + ["LAYOUT END"]:
        line = raw.split('//', 1)[0].strip()
        if not line:
            continue
        if line == "COLUMNS":
            in_columns = True
            continue
        if line.startswith(("BUILD ", "LAYOUT ")):
            if fields:
                finish()
                builds, fields = [], []
            in_columns = False
            if line.startswith("BUILD "):
                builds.append(line[6:])
            continue
        if line.startswith("COMMENT "):
            continue
        if in_columns:
            match = COLUMN.fullmatch(line)
            if match:
                columns[match.group(3).rstrip('?')] = (match.group(1), match.group(2))
            else:
                raise ValueError(f"{path.name}: unknown COLUMNS syntax: {line}")
        elif builds:
            match = FIELD.fullmatch(line)
            if not match:
                raise ValueError(f"{path.name}: unknown field syntax: {line}")
            name, width, array = match.groups()
            if name not in columns:
                raise ValueError(f"{path.name}: missing COLUMNS entry for {name}")
            kind, foreign = columns[name]
            fields.append((name, kind, int(array or 1), int(re.sub(r'\D', '', width)) if width else 32, foreign))

    if len(selected) != 1:
        raise ValueError(f"{path.name}: expected one build-5875 block, found {len(selected)}")
    return selected[0]


def quote(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def generate(definitions, layouts, dbc_names):
    primary = {}
    for name, fmt, count in VMANGOS.findall(layouts.read_text(encoding='utf-8-sig')):
        primary[name.lower()] = len(fmt) if fmt else int(count)
    packed = {name.lower(): int(size) for name, size in PACKED.findall(layouts.read_text(encoding='utf-8-sig'))}
    entries = []
    for name in sorted(dbc_names, key=str.lower):
        path = definitions / (name + '.dbd')
        if not path.is_file():
            raise ValueError(f"no WoWDBDefs definition for {name}")
        fields = parse(path)
        count = sum(field[2] * (9 if field[1] == 'locstring' else 1) for field in fields)
        size = sum(field[2] * (32 if field[1] in ('locstring', 'string') else field[3]) // 8 * (9 if field[1] == 'locstring' else 1) for field in fields)
        expected = primary.get((name + '.dbc').lower())
        if expected is not None and expected != count:
            raise ValueError(f"{name}: WoWDBDefs {count} fields disagrees with primary vmangos/ArcaneCore {expected}")
        if expected is not None and size != packed.get((name + '.dbc').lower(), expected * 4):
            raise ValueError(f"{name}: WoWDBDefs {size}-byte records disagree with primary vmangos/ArcaneCore")
        entries.append((name, count, size, fields))
    out = [
        '// <auto-generated> tools/codegen/gen_dbc_layouts.py; WoWDBDefs e3df370 (definitions CC BY-SA 4.0). </auto-generated>',
        '#nullable enable',
        'namespace ArcaneCore.Data.ClientData;',
        '',
        '/// <summary>A WoWDBDefs field in physical record order. ArrayLength counts logical values; locstring has eight strings and a flags slot.</summary>',
        'public sealed record DbdField(string Name, string Type, int ArrayLength, int WidthBits, int Offset, string? ForeignTable, string? ForeignColumn);',
        '',
        '/// <summary>One build-5875 DBC definition.</summary>',
        'public sealed record DbdLayout(string File, int Fields, int RecordSize, IReadOnlyList<DbdField> Columns);',
        '',
        'public static class ClientDbcDbdLayouts',
        '{',
        '    public static IReadOnlyDictionary<string, DbdLayout> All { get; } = new DbdLayout[]',
        '    {',
    ]
    for name, count, size, fields in entries:
        out.append(f'        new({quote(name + ".dbc")}, {count}, {size}, new DbdField[]')
        out.append('        {')
        offset = 0
        for field, kind, array, width, foreign in fields:
            table, _, column = foreign.partition('::') if foreign else ('', '', '')
            out.append(f'            new({quote(field)}, {quote(kind)}, {array}, {width}, {offset}, {quote(table) if table else "null"}, {quote(column) if column else "null"}),')
            offset += array * (9 if kind == 'locstring' else 1) * (32 if kind in ('locstring', 'string') else width) // 8
        out.append('        }),')
    out += ['    }.ToDictionary(l => l.File, StringComparer.OrdinalIgnoreCase);', '}']
    return '\n'.join(out) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--definitions', type=Path, default=Path('D:/ArcaneCore-lanes/_refs/csharp-cores/WoWDBDefs/definitions'))
    parser.add_argument('--dbc-dir', type=Path, default=Path('D:/ArcaneCore-data/client-dbc-5875'))
    parser.add_argument('--output', type=Path, default=CLIENT_DATA / 'ClientDbcLayouts.Dbd.g.cs')
    args = parser.parse_args()
    names = {path.stem for path in args.dbc_dir.glob('*.dbc')}
    if len(names) != 154:
        raise ValueError(f"expected 154 client DBCs, found {len(names)} in {args.dbc_dir}")
    content = generate(args.definitions, CLIENT_DATA / 'ClientDbcLayouts.cs', names)
    args.output.write_text(content, encoding='utf-8')
    print(f"generated {len(names)} layouts: {args.output}")


if __name__ == '__main__':
    main()
