CREATE TABLE "account" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_account" PRIMARY KEY AUTOINCREMENT,
    "Username" TEXT NOT NULL,
    "Salt" BLOB NOT NULL,
    "Verifier" BLOB NOT NULL,
    "SessionKey" BLOB NULL,
    "Status" INTEGER NOT NULL,
    "Security" INTEGER NOT NULL
);
CREATE TABLE "account_data" (
    "AccountId" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL,
    "Time" INTEGER NOT NULL,
    "Data" BLOB NOT NULL,
    CONSTRAINT "PK_account_data" PRIMARY KEY ("AccountId", "Type")
);
CREATE TABLE "account_tutorial" (
    "AccountId" INTEGER NOT NULL CONSTRAINT "PK_account_tutorial" PRIMARY KEY,
    "Tut0" INTEGER NOT NULL,
    "Tut1" INTEGER NOT NULL,
    "Tut2" INTEGER NOT NULL,
    "Tut3" INTEGER NOT NULL,
    "Tut4" INTEGER NOT NULL,
    "Tut5" INTEGER NOT NULL,
    "Tut6" INTEGER NOT NULL,
    "Tut7" INTEGER NOT NULL
);
CREATE TABLE "area_template" (
    "Entry" INTEGER NOT NULL CONSTRAINT "PK_area_template" PRIMARY KEY,
    "MapId" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "ExploreFlag" INTEGER NOT NULL,
    "Flags" INTEGER NOT NULL,
    "AreaLevel" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "Team" INTEGER NOT NULL,
    "LiquidTypeId" INTEGER NOT NULL
);
CREATE TABLE "areatrigger_teleport" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_areatrigger_teleport" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Message" TEXT NOT NULL,
    "RequiredLevel" INTEGER NOT NULL,
    "TargetMap" INTEGER NOT NULL,
    "TargetPositionX" REAL NOT NULL,
    "TargetPositionY" REAL NOT NULL,
    "TargetPositionZ" REAL NOT NULL,
    "TargetOrientation" REAL NOT NULL
);
CREATE TABLE "areatrigger_template" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_areatrigger_template" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "MapId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Radius" REAL NOT NULL,
    "BoxX" REAL NOT NULL,
    "BoxY" REAL NOT NULL,
    "BoxZ" REAL NOT NULL,
    "BoxOrientation" REAL NOT NULL
);
CREATE TABLE "auth_schema" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_auth_schema" PRIMARY KEY,
    "Version" INTEGER NOT NULL
);
CREATE TABLE "character_action" (
    "CharacterId" INTEGER NOT NULL,
    "Button" INTEGER NOT NULL,
    "Action" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL,
    CONSTRAINT "PK_character_action" PRIMARY KEY ("CharacterId", "Button")
);
CREATE TABLE "character_inventory" (
    "item_guid" INTEGER NOT NULL CONSTRAINT "PK_character_inventory" PRIMARY KEY,
    "guid" INTEGER NOT NULL,
    "bag" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL
);
CREATE TABLE "character_queststatus" (
    "guid" INTEGER NOT NULL,
    "quest" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "rewarded" INTEGER NOT NULL,
    "explored" INTEGER NOT NULL,
    "timer" INTEGER NOT NULL,
    "mob_count1" INTEGER NOT NULL,
    "mob_count2" INTEGER NOT NULL,
    "mob_count3" INTEGER NOT NULL,
    "mob_count4" INTEGER NOT NULL,
    "item_count1" INTEGER NOT NULL,
    "item_count2" INTEGER NOT NULL,
    "item_count3" INTEGER NOT NULL,
    "item_count4" INTEGER NOT NULL,
    "reward_choice" INTEGER NOT NULL,
    CONSTRAINT "PK_character_queststatus" PRIMARY KEY ("guid", "quest")
);
CREATE TABLE "character_social" (
    "CharacterId" INTEGER NOT NULL,
    "OtherId" INTEGER NOT NULL,
    "Flags" INTEGER NOT NULL,
    CONSTRAINT "PK_character_social" PRIMARY KEY ("CharacterId", "OtherId")
);
CREATE TABLE "character_spell" (
    "CharacterId" INTEGER NOT NULL,
    "Spell" INTEGER NOT NULL,
    CONSTRAINT "PK_character_spell" PRIMARY KEY ("CharacterId", "Spell")
);
CREATE TABLE "character_taxi" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_character_taxi" PRIMARY KEY,
    "mask0" INTEGER NOT NULL,
    "mask1" INTEGER NOT NULL,
    "mask2" INTEGER NOT NULL,
    "mask3" INTEGER NOT NULL,
    "mask4" INTEGER NOT NULL,
    "mask5" INTEGER NOT NULL,
    "mask6" INTEGER NOT NULL,
    "mask7" INTEGER NOT NULL
);
CREATE TABLE "characters" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_characters" PRIMARY KEY AUTOINCREMENT,
    "AccountId" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "Race" INTEGER NOT NULL,
    "Class" INTEGER NOT NULL,
    "Gender" INTEGER NOT NULL,
    "Skin" INTEGER NOT NULL,
    "Face" INTEGER NOT NULL,
    "HairStyle" INTEGER NOT NULL,
    "HairColor" INTEGER NOT NULL,
    "FacialHair" INTEGER NOT NULL,
    "Level" INTEGER NOT NULL,
    "MapId" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "PlayedTime" INTEGER NOT NULL,
    "LevelPlayedTime" INTEGER NOT NULL,
    "Money" INTEGER NOT NULL,
    "ActionBarToggles" INTEGER NOT NULL,
    "HomeMapId" INTEGER NOT NULL,
    "HomeZoneId" INTEGER NOT NULL,
    "HomeX" REAL NOT NULL,
    "HomeY" REAL NOT NULL,
    "HomeZ" REAL NOT NULL
);
CREATE TABLE "characters_schema" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_characters_schema" PRIMARY KEY,
    "Version" INTEGER NOT NULL
);
CREATE TABLE "class_info" (
    "Class" INTEGER NOT NULL CONSTRAINT "PK_class_info" PRIMARY KEY,
    "BaseHealth" INTEGER NOT NULL,
    "BaseMana" INTEGER NOT NULL,
    "PowerType" INTEGER NOT NULL
);
CREATE TABLE "creature_addon" (
    "Guid" INTEGER NOT NULL CONSTRAINT "PK_creature_addon" PRIMARY KEY,
    "MountDisplayId" INTEGER NOT NULL,
    "StandState" INTEGER NOT NULL,
    "SheathState" INTEGER NOT NULL,
    "EmoteState" INTEGER NOT NULL
);
CREATE TABLE "creature_involvedrelation" (
    "id" INTEGER NOT NULL,
    "quest" INTEGER NOT NULL,
    CONSTRAINT "PK_creature_involvedrelation" PRIMARY KEY ("id", "quest")
);
CREATE TABLE "creature_model_info" (
    "DisplayId" INTEGER NOT NULL CONSTRAINT "PK_creature_model_info" PRIMARY KEY,
    "BoundingRadius" REAL NOT NULL,
    "CombatReach" REAL NOT NULL,
    "Gender" INTEGER NOT NULL,
    "DisplayIdOtherGender" INTEGER NOT NULL
);
CREATE TABLE "creature_movement" (
    "SpawnGuid" INTEGER NOT NULL,
    "Point" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "WaitTimeMs" INTEGER NOT NULL,
    CONSTRAINT "PK_creature_movement" PRIMARY KEY ("SpawnGuid", "Point")
);
CREATE TABLE "creature_questrelation" (
    "id" INTEGER NOT NULL,
    "quest" INTEGER NOT NULL,
    CONSTRAINT "PK_creature_questrelation" PRIMARY KEY ("id", "quest")
);
CREATE TABLE "creature_spawn" (
    "Guid" INTEGER NOT NULL CONSTRAINT "PK_creature_spawn" PRIMARY KEY,
    "Entry" INTEGER NOT NULL,
    "MapId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "SpawnTimeMinSeconds" INTEGER NOT NULL,
    "SpawnTimeMaxSeconds" INTEGER NOT NULL,
    "WanderDistance" REAL NOT NULL,
    "MovementType" INTEGER NOT NULL
);
CREATE TABLE "creature_template" (
    "Entry" INTEGER NOT NULL CONSTRAINT "PK_creature_template" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "SubName" TEXT NOT NULL,
    "MinLevel" INTEGER NOT NULL,
    "MaxLevel" INTEGER NOT NULL,
    "DisplayId1" INTEGER NOT NULL,
    "DisplayId2" INTEGER NOT NULL,
    "DisplayId3" INTEGER NOT NULL,
    "DisplayId4" INTEGER NOT NULL,
    "DisplayProbability1" INTEGER NOT NULL,
    "DisplayProbability2" INTEGER NOT NULL,
    "DisplayProbability3" INTEGER NOT NULL,
    "DisplayProbability4" INTEGER NOT NULL,
    "Scale" REAL NOT NULL,
    "Faction" INTEGER NOT NULL,
    "NpcFlags" INTEGER NOT NULL,
    "UnitFlags" INTEGER NOT NULL,
    "DynamicFlags" INTEGER NOT NULL,
    "TypeFlags" INTEGER NOT NULL,
    "CreatureType" INTEGER NOT NULL,
    "Family" INTEGER NOT NULL,
    "Rank" INTEGER NOT NULL,
    "UnitClass" INTEGER NOT NULL,
    "InhabitType" INTEGER NOT NULL,
    "Civilian" INTEGER NOT NULL,
    "RacialLeader" INTEGER NOT NULL,
    "SpeedWalk" REAL NOT NULL,
    "SpeedRun" REAL NOT NULL,
    "MinLevelHealth" INTEGER NOT NULL,
    "MaxLevelHealth" INTEGER NOT NULL,
    "MinLevelMana" INTEGER NOT NULL,
    "MaxLevelMana" INTEGER NOT NULL,
    "Armor" INTEGER NOT NULL,
    "MinMeleeDamage" REAL NOT NULL,
    "MaxMeleeDamage" REAL NOT NULL,
    "MinRangedDamage" REAL NOT NULL,
    "MaxRangedDamage" REAL NOT NULL,
    "MeleeAttackPower" INTEGER NOT NULL,
    "RangedAttackPower" INTEGER NOT NULL,
    "MeleeBaseAttackTime" INTEGER NOT NULL,
    "RangedBaseAttackTime" INTEGER NOT NULL,
    "DamageSchool" INTEGER NOT NULL,
    "PetSpellDataId" INTEGER NOT NULL,
    "MovementType" INTEGER NOT NULL,
    "CorpseDecaySeconds" INTEGER NOT NULL,
    "ExtraFlags" INTEGER NOT NULL
);
CREATE TABLE "game_tele" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_game_tele" PRIMARY KEY,
    "PositionX" REAL NOT NULL,
    "PositionY" REAL NOT NULL,
    "PositionZ" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "Map" INTEGER NOT NULL,
    "Name" TEXT NOT NULL
);
CREATE TABLE "gossip_menu" (
    "entry" INTEGER NOT NULL,
    "text_id" INTEGER NOT NULL,
    "condition_id" INTEGER NOT NULL,
    CONSTRAINT "PK_gossip_menu" PRIMARY KEY ("entry", "text_id", "condition_id")
);
CREATE TABLE "gossip_menu_option" (
    "menu_id" INTEGER NOT NULL,
    "id" INTEGER NOT NULL,
    "option_icon" INTEGER NOT NULL,
    "option_text" TEXT NOT NULL,
    "option_id" INTEGER NOT NULL,
    "npc_option_npcflag" INTEGER NOT NULL,
    "action_menu_id" INTEGER NOT NULL,
    "action_poi_id" INTEGER NOT NULL,
    "box_coded" INTEGER NOT NULL,
    "box_text" TEXT NOT NULL,
    "condition_id" INTEGER NOT NULL,
    CONSTRAINT "PK_gossip_menu_option" PRIMARY KEY ("menu_id", "id")
);
CREATE TABLE "guild" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_guild" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "LeaderId" INTEGER NOT NULL,
    "Motd" TEXT NOT NULL,
    "Info" TEXT NOT NULL,
    "CreatedAt" INTEGER NOT NULL,
    "EmblemStyle" INTEGER NOT NULL,
    "EmblemColor" INTEGER NOT NULL,
    "BorderStyle" INTEGER NOT NULL,
    "BorderColor" INTEGER NOT NULL,
    "BackgroundColor" INTEGER NOT NULL
);
CREATE TABLE "guild_member" (
    "GuildId" INTEGER NOT NULL,
    "CharacterId" INTEGER NOT NULL,
    "Rank" INTEGER NOT NULL,
    "PublicNote" TEXT NOT NULL,
    "OfficerNote" TEXT NOT NULL,
    "Level" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "LogoutTime" INTEGER NOT NULL,
    CONSTRAINT "PK_guild_member" PRIMARY KEY ("GuildId", "CharacterId")
);
CREATE TABLE "guild_rank" (
    "GuildId" INTEGER NOT NULL,
    "RankId" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "Rights" INTEGER NOT NULL,
    CONSTRAINT "PK_guild_rank" PRIMARY KEY ("GuildId", "RankId")
);
CREATE TABLE "item_instance" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_item_instance" PRIMARY KEY,
    "owner_guid" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "creator_guid" INTEGER NOT NULL,
    "gift_creator_guid" INTEGER NOT NULL,
    "count" INTEGER NOT NULL,
    "duration" INTEGER NOT NULL,
    "charges" TEXT NOT NULL,
    "flags" INTEGER NOT NULL,
    "enchantments" TEXT NOT NULL,
    "random_property_id" INTEGER NOT NULL,
    "durability" INTEGER NOT NULL,
    "text" INTEGER NOT NULL
);
CREATE TABLE "item_template" (
    "entry" INTEGER NOT NULL CONSTRAINT "PK_item_template" PRIMARY KEY,
    "class" INTEGER NOT NULL,
    "subclass" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "display_id" INTEGER NOT NULL,
    "quality" INTEGER NOT NULL,
    "flags" INTEGER NOT NULL,
    "buy_count" INTEGER NOT NULL,
    "buy_price" INTEGER NOT NULL,
    "sell_price" INTEGER NOT NULL,
    "inventory_type" INTEGER NOT NULL,
    "allowable_class" INTEGER NOT NULL,
    "allowable_race" INTEGER NOT NULL,
    "item_level" INTEGER NOT NULL,
    "required_level" INTEGER NOT NULL,
    "required_skill" INTEGER NOT NULL,
    "required_skill_rank" INTEGER NOT NULL,
    "required_spell" INTEGER NOT NULL,
    "required_honor_rank" INTEGER NOT NULL,
    "required_city_rank" INTEGER NOT NULL,
    "required_reputation_faction" INTEGER NOT NULL,
    "required_reputation_rank" INTEGER NOT NULL,
    "max_count" INTEGER NOT NULL,
    "stackable" INTEGER NOT NULL,
    "container_slots" INTEGER NOT NULL,
    "stat_type1" INTEGER NOT NULL,
    "stat_value1" INTEGER NOT NULL,
    "stat_type2" INTEGER NOT NULL,
    "stat_value2" INTEGER NOT NULL,
    "stat_type3" INTEGER NOT NULL,
    "stat_value3" INTEGER NOT NULL,
    "stat_type4" INTEGER NOT NULL,
    "stat_value4" INTEGER NOT NULL,
    "stat_type5" INTEGER NOT NULL,
    "stat_value5" INTEGER NOT NULL,
    "stat_type6" INTEGER NOT NULL,
    "stat_value6" INTEGER NOT NULL,
    "stat_type7" INTEGER NOT NULL,
    "stat_value7" INTEGER NOT NULL,
    "stat_type8" INTEGER NOT NULL,
    "stat_value8" INTEGER NOT NULL,
    "stat_type9" INTEGER NOT NULL,
    "stat_value9" INTEGER NOT NULL,
    "stat_type10" INTEGER NOT NULL,
    "stat_value10" INTEGER NOT NULL,
    "delay" INTEGER NOT NULL,
    "range_mod" REAL NOT NULL,
    "ammo_type" INTEGER NOT NULL,
    "dmg_min1" REAL NOT NULL,
    "dmg_max1" REAL NOT NULL,
    "dmg_type1" INTEGER NOT NULL,
    "dmg_min2" REAL NOT NULL,
    "dmg_max2" REAL NOT NULL,
    "dmg_type2" INTEGER NOT NULL,
    "dmg_min3" REAL NOT NULL,
    "dmg_max3" REAL NOT NULL,
    "dmg_type3" INTEGER NOT NULL,
    "dmg_min4" REAL NOT NULL,
    "dmg_max4" REAL NOT NULL,
    "dmg_type4" INTEGER NOT NULL,
    "dmg_min5" REAL NOT NULL,
    "dmg_max5" REAL NOT NULL,
    "dmg_type5" INTEGER NOT NULL,
    "block" INTEGER NOT NULL,
    "armor" INTEGER NOT NULL,
    "holy_res" INTEGER NOT NULL,
    "fire_res" INTEGER NOT NULL,
    "nature_res" INTEGER NOT NULL,
    "frost_res" INTEGER NOT NULL,
    "shadow_res" INTEGER NOT NULL,
    "arcane_res" INTEGER NOT NULL,
    "spellid_1" INTEGER NOT NULL,
    "spelltrigger_1" INTEGER NOT NULL,
    "spellcharges_1" INTEGER NOT NULL,
    "spellppmrate_1" REAL NOT NULL,
    "spellcooldown_1" INTEGER NOT NULL,
    "spellcategory_1" INTEGER NOT NULL,
    "spellcategorycooldown_1" INTEGER NOT NULL,
    "spellid_2" INTEGER NOT NULL,
    "spelltrigger_2" INTEGER NOT NULL,
    "spellcharges_2" INTEGER NOT NULL,
    "spellppmrate_2" REAL NOT NULL,
    "spellcooldown_2" INTEGER NOT NULL,
    "spellcategory_2" INTEGER NOT NULL,
    "spellcategorycooldown_2" INTEGER NOT NULL,
    "spellid_3" INTEGER NOT NULL,
    "spelltrigger_3" INTEGER NOT NULL,
    "spellcharges_3" INTEGER NOT NULL,
    "spellppmrate_3" REAL NOT NULL,
    "spellcooldown_3" INTEGER NOT NULL,
    "spellcategory_3" INTEGER NOT NULL,
    "spellcategorycooldown_3" INTEGER NOT NULL,
    "spellid_4" INTEGER NOT NULL,
    "spelltrigger_4" INTEGER NOT NULL,
    "spellcharges_4" INTEGER NOT NULL,
    "spellppmrate_4" REAL NOT NULL,
    "spellcooldown_4" INTEGER NOT NULL,
    "spellcategory_4" INTEGER NOT NULL,
    "spellcategorycooldown_4" INTEGER NOT NULL,
    "spellid_5" INTEGER NOT NULL,
    "spelltrigger_5" INTEGER NOT NULL,
    "spellcharges_5" INTEGER NOT NULL,
    "spellppmrate_5" REAL NOT NULL,
    "spellcooldown_5" INTEGER NOT NULL,
    "spellcategory_5" INTEGER NOT NULL,
    "spellcategorycooldown_5" INTEGER NOT NULL,
    "bonding" INTEGER NOT NULL,
    "page_text" INTEGER NOT NULL,
    "page_language" INTEGER NOT NULL,
    "page_material" INTEGER NOT NULL,
    "start_quest" INTEGER NOT NULL,
    "lock_id" INTEGER NOT NULL,
    "material" INTEGER NOT NULL,
    "sheath" INTEGER NOT NULL,
    "random_property" INTEGER NOT NULL,
    "set_id" INTEGER NOT NULL,
    "max_durability" INTEGER NOT NULL,
    "area_bound" INTEGER NOT NULL,
    "map_bound" INTEGER NOT NULL,
    "duration" INTEGER NOT NULL,
    "bag_family" INTEGER NOT NULL,
    "disenchant_id" INTEGER NOT NULL,
    "food_type" INTEGER NOT NULL,
    "min_money_loot" INTEGER NOT NULL,
    "max_money_loot" INTEGER NOT NULL,
    "wrapped_gift" INTEGER NOT NULL,
    "extra_flags" INTEGER NOT NULL,
    "other_team_entry" INTEGER NOT NULL
);
CREATE TABLE "map_template" (
    "Entry" INTEGER NOT NULL CONSTRAINT "PK_map_template" PRIMARY KEY,
    "Parent" INTEGER NOT NULL,
    "MapType" INTEGER NOT NULL,
    "LinkedZone" INTEGER NOT NULL,
    "PlayerLimit" INTEGER NOT NULL,
    "ResetDelay" INTEGER NOT NULL,
    "GhostEntranceMap" INTEGER NOT NULL,
    "GhostEntranceX" REAL NOT NULL,
    "GhostEntranceY" REAL NOT NULL,
    "MapName" TEXT NOT NULL,
    "ScriptName" TEXT NOT NULL
);
CREATE TABLE "npc_gossip" (
    "npc_guid" INTEGER NOT NULL CONSTRAINT "PK_npc_gossip" PRIMARY KEY,
    "textid" INTEGER NOT NULL
);
CREATE TABLE "npc_text" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_npc_text" PRIMARY KEY,
    "text0_0" TEXT NOT NULL,
    "text0_1" TEXT NOT NULL,
    "lang0" INTEGER NOT NULL,
    "prob0" REAL NOT NULL,
    "em0_0" INTEGER NOT NULL,
    "em0_1" INTEGER NOT NULL,
    "em0_2" INTEGER NOT NULL,
    "em0_3" INTEGER NOT NULL,
    "em0_4" INTEGER NOT NULL,
    "em0_5" INTEGER NOT NULL,
    "text1_0" TEXT NOT NULL,
    "text1_1" TEXT NOT NULL,
    "lang1" INTEGER NOT NULL,
    "prob1" REAL NOT NULL,
    "em1_0" INTEGER NOT NULL,
    "em1_1" INTEGER NOT NULL,
    "em1_2" INTEGER NOT NULL,
    "em1_3" INTEGER NOT NULL,
    "em1_4" INTEGER NOT NULL,
    "em1_5" INTEGER NOT NULL,
    "text2_0" TEXT NOT NULL,
    "text2_1" TEXT NOT NULL,
    "lang2" INTEGER NOT NULL,
    "prob2" REAL NOT NULL,
    "em2_0" INTEGER NOT NULL,
    "em2_1" INTEGER NOT NULL,
    "em2_2" INTEGER NOT NULL,
    "em2_3" INTEGER NOT NULL,
    "em2_4" INTEGER NOT NULL,
    "em2_5" INTEGER NOT NULL,
    "text3_0" TEXT NOT NULL,
    "text3_1" TEXT NOT NULL,
    "lang3" INTEGER NOT NULL,
    "prob3" REAL NOT NULL,
    "em3_0" INTEGER NOT NULL,
    "em3_1" INTEGER NOT NULL,
    "em3_2" INTEGER NOT NULL,
    "em3_3" INTEGER NOT NULL,
    "em3_4" INTEGER NOT NULL,
    "em3_5" INTEGER NOT NULL,
    "text4_0" TEXT NOT NULL,
    "text4_1" TEXT NOT NULL,
    "lang4" INTEGER NOT NULL,
    "prob4" REAL NOT NULL,
    "em4_0" INTEGER NOT NULL,
    "em4_1" INTEGER NOT NULL,
    "em4_2" INTEGER NOT NULL,
    "em4_3" INTEGER NOT NULL,
    "em4_4" INTEGER NOT NULL,
    "em4_5" INTEGER NOT NULL,
    "text5_0" TEXT NOT NULL,
    "text5_1" TEXT NOT NULL,
    "lang5" INTEGER NOT NULL,
    "prob5" REAL NOT NULL,
    "em5_0" INTEGER NOT NULL,
    "em5_1" INTEGER NOT NULL,
    "em5_2" INTEGER NOT NULL,
    "em5_3" INTEGER NOT NULL,
    "em5_4" INTEGER NOT NULL,
    "em5_5" INTEGER NOT NULL,
    "text6_0" TEXT NOT NULL,
    "text6_1" TEXT NOT NULL,
    "lang6" INTEGER NOT NULL,
    "prob6" REAL NOT NULL,
    "em6_0" INTEGER NOT NULL,
    "em6_1" INTEGER NOT NULL,
    "em6_2" INTEGER NOT NULL,
    "em6_3" INTEGER NOT NULL,
    "em6_4" INTEGER NOT NULL,
    "em6_5" INTEGER NOT NULL,
    "text7_0" TEXT NOT NULL,
    "text7_1" TEXT NOT NULL,
    "lang7" INTEGER NOT NULL,
    "prob7" REAL NOT NULL,
    "em7_0" INTEGER NOT NULL,
    "em7_1" INTEGER NOT NULL,
    "em7_2" INTEGER NOT NULL,
    "em7_3" INTEGER NOT NULL,
    "em7_4" INTEGER NOT NULL,
    "em7_5" INTEGER NOT NULL
);
CREATE TABLE "npc_trainer" (
    "entry" INTEGER NOT NULL,
    "spell" INTEGER NOT NULL,
    "spellcost" INTEGER NOT NULL,
    "reqskill" INTEGER NOT NULL,
    "reqskillvalue" INTEGER NOT NULL,
    "reqlevel" INTEGER NOT NULL,
    CONSTRAINT "PK_npc_trainer" PRIMARY KEY ("entry", "spell")
);
CREATE TABLE "npc_vendor" (
    "entry" INTEGER NOT NULL,
    "item" INTEGER NOT NULL,
    "maxcount" INTEGER NOT NULL,
    "incrtime" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "condition_id" INTEGER NOT NULL,
    CONSTRAINT "PK_npc_vendor" PRIMARY KEY ("entry", "item")
);
CREATE TABLE "player_create_info" (
    "Race" INTEGER NOT NULL,
    "Class" INTEGER NOT NULL,
    "MapId" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    CONSTRAINT "PK_player_create_info" PRIMARY KEY ("Race", "Class")
);
CREATE TABLE "playercreateinfo_item" (
    "race" INTEGER NOT NULL,
    "class" INTEGER NOT NULL,
    "itemid" INTEGER NOT NULL,
    "amount" INTEGER NOT NULL,
    CONSTRAINT "PK_playercreateinfo_item" PRIMARY KEY ("race", "class", "itemid")
);
CREATE TABLE "playercreateinfo_spell" (
    "race" INTEGER NOT NULL,
    "class" INTEGER NOT NULL,
    "Spell" INTEGER NOT NULL,
    "Note" TEXT NULL,
    CONSTRAINT "PK_playercreateinfo_spell" PRIMARY KEY ("race", "class", "Spell")
);
CREATE TABLE "points_of_interest" (
    "entry" INTEGER NOT NULL CONSTRAINT "PK_points_of_interest" PRIMARY KEY,
    "x" REAL NOT NULL,
    "y" REAL NOT NULL,
    "icon" INTEGER NOT NULL,
    "flags" INTEGER NOT NULL,
    "data" INTEGER NOT NULL,
    "icon_name" TEXT NOT NULL
);
CREATE TABLE "quest_template" (
    "entry" INTEGER NOT NULL CONSTRAINT "PK_quest_template" PRIMARY KEY,
    "Method" INTEGER NOT NULL,
    "ZoneOrSort" INTEGER NOT NULL,
    "MinLevel" INTEGER NOT NULL,
    "MaxLevel" INTEGER NOT NULL,
    "QuestLevel" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL,
    "RequiredClasses" INTEGER NOT NULL,
    "RequiredRaces" INTEGER NOT NULL,
    "RequiredSkill" INTEGER NOT NULL,
    "RequiredSkillValue" INTEGER NOT NULL,
    "RepObjectiveFaction" INTEGER NOT NULL,
    "RepObjectiveValue" INTEGER NOT NULL,
    "RequiredMinRepFaction" INTEGER NOT NULL,
    "RequiredMinRepValue" INTEGER NOT NULL,
    "RequiredMaxRepFaction" INTEGER NOT NULL,
    "RequiredMaxRepValue" INTEGER NOT NULL,
    "SuggestedPlayers" INTEGER NOT NULL,
    "LimitTime" INTEGER NOT NULL,
    "QuestFlags" INTEGER NOT NULL,
    "SpecialFlags" INTEGER NOT NULL,
    "PrevQuestId" INTEGER NOT NULL,
    "NextQuestId" INTEGER NOT NULL,
    "ExclusiveGroup" INTEGER NOT NULL,
    "BreadcrumbForQuestId" INTEGER NOT NULL,
    "NextQuestInChain" INTEGER NOT NULL,
    "SrcItemId" INTEGER NOT NULL,
    "SrcItemCount" INTEGER NOT NULL,
    "SrcSpell" INTEGER NOT NULL,
    "Title" TEXT NOT NULL,
    "Details" TEXT NOT NULL,
    "Objectives" TEXT NOT NULL,
    "OfferRewardText" TEXT NOT NULL,
    "RequestItemsText" TEXT NOT NULL,
    "EndText" TEXT NOT NULL,
    "ObjectiveText1" TEXT NOT NULL,
    "ObjectiveText2" TEXT NOT NULL,
    "ObjectiveText3" TEXT NOT NULL,
    "ObjectiveText4" TEXT NOT NULL,
    "ReqItemId1" INTEGER NOT NULL,
    "ReqItemId2" INTEGER NOT NULL,
    "ReqItemId3" INTEGER NOT NULL,
    "ReqItemId4" INTEGER NOT NULL,
    "ReqItemCount1" INTEGER NOT NULL,
    "ReqItemCount2" INTEGER NOT NULL,
    "ReqItemCount3" INTEGER NOT NULL,
    "ReqItemCount4" INTEGER NOT NULL,
    "ReqSourceId1" INTEGER NOT NULL,
    "ReqSourceId2" INTEGER NOT NULL,
    "ReqSourceId3" INTEGER NOT NULL,
    "ReqSourceId4" INTEGER NOT NULL,
    "ReqSourceCount1" INTEGER NOT NULL,
    "ReqSourceCount2" INTEGER NOT NULL,
    "ReqSourceCount3" INTEGER NOT NULL,
    "ReqSourceCount4" INTEGER NOT NULL,
    "ReqCreatureOrGOId1" INTEGER NOT NULL,
    "ReqCreatureOrGOId2" INTEGER NOT NULL,
    "ReqCreatureOrGOId3" INTEGER NOT NULL,
    "ReqCreatureOrGOId4" INTEGER NOT NULL,
    "ReqCreatureOrGOCount1" INTEGER NOT NULL,
    "ReqCreatureOrGOCount2" INTEGER NOT NULL,
    "ReqCreatureOrGOCount3" INTEGER NOT NULL,
    "ReqCreatureOrGOCount4" INTEGER NOT NULL,
    "ReqSpellCast1" INTEGER NOT NULL,
    "ReqSpellCast2" INTEGER NOT NULL,
    "ReqSpellCast3" INTEGER NOT NULL,
    "ReqSpellCast4" INTEGER NOT NULL,
    "RewChoiceItemId1" INTEGER NOT NULL,
    "RewChoiceItemId2" INTEGER NOT NULL,
    "RewChoiceItemId3" INTEGER NOT NULL,
    "RewChoiceItemId4" INTEGER NOT NULL,
    "RewChoiceItemId5" INTEGER NOT NULL,
    "RewChoiceItemId6" INTEGER NOT NULL,
    "RewChoiceItemCount1" INTEGER NOT NULL,
    "RewChoiceItemCount2" INTEGER NOT NULL,
    "RewChoiceItemCount3" INTEGER NOT NULL,
    "RewChoiceItemCount4" INTEGER NOT NULL,
    "RewChoiceItemCount5" INTEGER NOT NULL,
    "RewChoiceItemCount6" INTEGER NOT NULL,
    "RewItemId1" INTEGER NOT NULL,
    "RewItemId2" INTEGER NOT NULL,
    "RewItemId3" INTEGER NOT NULL,
    "RewItemId4" INTEGER NOT NULL,
    "RewItemCount1" INTEGER NOT NULL,
    "RewItemCount2" INTEGER NOT NULL,
    "RewItemCount3" INTEGER NOT NULL,
    "RewItemCount4" INTEGER NOT NULL,
    "RewXP" INTEGER NOT NULL,
    "RewOrReqMoney" INTEGER NOT NULL,
    "RewMoneyMaxLevel" INTEGER NOT NULL,
    "RewSpell" INTEGER NOT NULL,
    "RewSpellCast" INTEGER NOT NULL,
    "PointMapId" INTEGER NOT NULL,
    "PointX" REAL NOT NULL,
    "PointY" REAL NOT NULL,
    "PointOpt" INTEGER NOT NULL,
    "DetailsEmote1" INTEGER NOT NULL,
    "DetailsEmote2" INTEGER NOT NULL,
    "DetailsEmote3" INTEGER NOT NULL,
    "DetailsEmote4" INTEGER NOT NULL,
    "DetailsEmoteDelay1" INTEGER NOT NULL,
    "DetailsEmoteDelay2" INTEGER NOT NULL,
    "DetailsEmoteDelay3" INTEGER NOT NULL,
    "DetailsEmoteDelay4" INTEGER NOT NULL,
    "IncompleteEmote" INTEGER NOT NULL,
    "CompleteEmote" INTEGER NOT NULL,
    "OfferRewardEmote1" INTEGER NOT NULL,
    "OfferRewardEmote2" INTEGER NOT NULL,
    "OfferRewardEmote3" INTEGER NOT NULL,
    "OfferRewardEmote4" INTEGER NOT NULL,
    "OfferRewardEmoteDelay1" INTEGER NOT NULL,
    "OfferRewardEmoteDelay2" INTEGER NOT NULL,
    "OfferRewardEmoteDelay3" INTEGER NOT NULL,
    "OfferRewardEmoteDelay4" INTEGER NOT NULL,
    "RequiredCondition" INTEGER NOT NULL
);
CREATE TABLE "race_info" (
    "Race" INTEGER NOT NULL,
    "Gender" INTEGER NOT NULL,
    "DisplayId" INTEGER NOT NULL,
    "FactionTemplate" INTEGER NOT NULL,
    CONSTRAINT "PK_race_info" PRIMARY KEY ("Race", "Gender")
);
CREATE TABLE "race_taxi_start" (
    "race" INTEGER NOT NULL CONSTRAINT "PK_race_taxi_start" PRIMARY KEY,
    "mask" INTEGER NOT NULL
);
CREATE TABLE "realmlist" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_realmlist" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Address" TEXT NOT NULL,
    "Type" INTEGER NOT NULL,
    "Flags" INTEGER NOT NULL,
    "Population" REAL NOT NULL,
    "Category" INTEGER NOT NULL
);
CREATE TABLE "spell_cast_times" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_spell_cast_times" PRIMARY KEY,
    "CastTime" INTEGER NOT NULL,
    "CastTimePerLevel" INTEGER NOT NULL,
    "MinCastTime" INTEGER NOT NULL
);
CREATE TABLE "spell_duration" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_spell_duration" PRIMARY KEY,
    "Duration" INTEGER NOT NULL,
    "DurationPerLevel" INTEGER NOT NULL,
    "MaxDuration" INTEGER NOT NULL
);
CREATE TABLE "spell_radius" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_spell_radius" PRIMARY KEY,
    "Radius" REAL NOT NULL,
    "RadiusPerLevel" REAL NOT NULL,
    "RadiusMax" REAL NOT NULL
);
CREATE TABLE "spell_range" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_spell_range" PRIMARY KEY,
    "MinRange" REAL NOT NULL,
    "MaxRange" REAL NOT NULL,
    "Flags" INTEGER NOT NULL
);
CREATE TABLE "spell_target_position" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_spell_target_position" PRIMARY KEY,
    "target_map" INTEGER NOT NULL,
    "target_position_x" REAL NOT NULL,
    "target_position_y" REAL NOT NULL,
    "target_position_z" REAL NOT NULL,
    "target_orientation" REAL NOT NULL
);
CREATE TABLE "spell_template" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_spell_template" PRIMARY KEY,
    "School" INTEGER NOT NULL,
    "Category" INTEGER NOT NULL,
    "Dispel" INTEGER NOT NULL,
    "Mechanic" INTEGER NOT NULL,
    "Attributes" INTEGER NOT NULL,
    "AttributesEx" INTEGER NOT NULL,
    "AttributesEx2" INTEGER NOT NULL,
    "AttributesEx3" INTEGER NOT NULL,
    "AttributesEx4" INTEGER NOT NULL,
    "Stances" INTEGER NOT NULL,
    "StancesNot" INTEGER NOT NULL,
    "Targets" INTEGER NOT NULL,
    "TargetCreatureType" INTEGER NOT NULL,
    "RequiresSpellFocus" INTEGER NOT NULL,
    "CasterAuraState" INTEGER NOT NULL,
    "TargetAuraState" INTEGER NOT NULL,
    "CastingTimeIndex" INTEGER NOT NULL,
    "RecoveryTime" INTEGER NOT NULL,
    "CategoryRecoveryTime" INTEGER NOT NULL,
    "InterruptFlags" INTEGER NOT NULL,
    "AuraInterruptFlags" INTEGER NOT NULL,
    "ChannelInterruptFlags" INTEGER NOT NULL,
    "ProcFlags" INTEGER NOT NULL,
    "ProcChance" INTEGER NOT NULL,
    "ProcCharges" INTEGER NOT NULL,
    "MaxLevel" INTEGER NOT NULL,
    "BaseLevel" INTEGER NOT NULL,
    "SpellLevel" INTEGER NOT NULL,
    "DurationIndex" INTEGER NOT NULL,
    "PowerType" INTEGER NOT NULL,
    "ManaCost" INTEGER NOT NULL,
    "ManaCostPerlevel" INTEGER NOT NULL,
    "ManaPerSecond" INTEGER NOT NULL,
    "ManaPerSecondPerLevel" INTEGER NOT NULL,
    "RangeIndex" INTEGER NOT NULL,
    "Speed" REAL NOT NULL,
    "StackAmount" INTEGER NOT NULL,
    "Totem1" INTEGER NOT NULL,
    "Totem2" INTEGER NOT NULL,
    "Reagent1" INTEGER NOT NULL,
    "Reagent2" INTEGER NOT NULL,
    "Reagent3" INTEGER NOT NULL,
    "Reagent4" INTEGER NOT NULL,
    "Reagent5" INTEGER NOT NULL,
    "Reagent6" INTEGER NOT NULL,
    "Reagent7" INTEGER NOT NULL,
    "Reagent8" INTEGER NOT NULL,
    "ReagentCount1" INTEGER NOT NULL,
    "ReagentCount2" INTEGER NOT NULL,
    "ReagentCount3" INTEGER NOT NULL,
    "ReagentCount4" INTEGER NOT NULL,
    "ReagentCount5" INTEGER NOT NULL,
    "ReagentCount6" INTEGER NOT NULL,
    "ReagentCount7" INTEGER NOT NULL,
    "ReagentCount8" INTEGER NOT NULL,
    "EquippedItemClass" INTEGER NOT NULL,
    "EquippedItemSubClassMask" INTEGER NOT NULL,
    "EquippedItemInventoryTypeMask" INTEGER NOT NULL,
    "Effect1" INTEGER NOT NULL,
    "Effect2" INTEGER NOT NULL,
    "Effect3" INTEGER NOT NULL,
    "EffectDieSides1" INTEGER NOT NULL,
    "EffectDieSides2" INTEGER NOT NULL,
    "EffectDieSides3" INTEGER NOT NULL,
    "EffectBaseDice1" INTEGER NOT NULL,
    "EffectBaseDice2" INTEGER NOT NULL,
    "EffectBaseDice3" INTEGER NOT NULL,
    "EffectDicePerLevel1" REAL NOT NULL,
    "EffectDicePerLevel2" REAL NOT NULL,
    "EffectDicePerLevel3" REAL NOT NULL,
    "EffectRealPointsPerLevel1" REAL NOT NULL,
    "EffectRealPointsPerLevel2" REAL NOT NULL,
    "EffectRealPointsPerLevel3" REAL NOT NULL,
    "EffectBasePoints1" INTEGER NOT NULL,
    "EffectBasePoints2" INTEGER NOT NULL,
    "EffectBasePoints3" INTEGER NOT NULL,
    "EffectMechanic1" INTEGER NOT NULL,
    "EffectMechanic2" INTEGER NOT NULL,
    "EffectMechanic3" INTEGER NOT NULL,
    "EffectImplicitTargetA1" INTEGER NOT NULL,
    "EffectImplicitTargetA2" INTEGER NOT NULL,
    "EffectImplicitTargetA3" INTEGER NOT NULL,
    "EffectImplicitTargetB1" INTEGER NOT NULL,
    "EffectImplicitTargetB2" INTEGER NOT NULL,
    "EffectImplicitTargetB3" INTEGER NOT NULL,
    "EffectRadiusIndex1" INTEGER NOT NULL,
    "EffectRadiusIndex2" INTEGER NOT NULL,
    "EffectRadiusIndex3" INTEGER NOT NULL,
    "EffectApplyAuraName1" INTEGER NOT NULL,
    "EffectApplyAuraName2" INTEGER NOT NULL,
    "EffectApplyAuraName3" INTEGER NOT NULL,
    "EffectAmplitude1" INTEGER NOT NULL,
    "EffectAmplitude2" INTEGER NOT NULL,
    "EffectAmplitude3" INTEGER NOT NULL,
    "EffectMultipleValue1" REAL NOT NULL,
    "EffectMultipleValue2" REAL NOT NULL,
    "EffectMultipleValue3" REAL NOT NULL,
    "EffectChainTarget1" INTEGER NOT NULL,
    "EffectChainTarget2" INTEGER NOT NULL,
    "EffectChainTarget3" INTEGER NOT NULL,
    "EffectItemType1" INTEGER NOT NULL,
    "EffectItemType2" INTEGER NOT NULL,
    "EffectItemType3" INTEGER NOT NULL,
    "EffectMiscValue1" INTEGER NOT NULL,
    "EffectMiscValue2" INTEGER NOT NULL,
    "EffectMiscValue3" INTEGER NOT NULL,
    "EffectTriggerSpell1" INTEGER NOT NULL,
    "EffectTriggerSpell2" INTEGER NOT NULL,
    "EffectTriggerSpell3" INTEGER NOT NULL,
    "EffectPointsPerComboPoint1" REAL NOT NULL,
    "EffectPointsPerComboPoint2" REAL NOT NULL,
    "EffectPointsPerComboPoint3" REAL NOT NULL,
    "SpellVisual" INTEGER NOT NULL,
    "SpellIconID" INTEGER NOT NULL,
    "ActiveIconID" INTEGER NOT NULL,
    "SpellPriority" INTEGER NOT NULL,
    "SpellName" TEXT NULL,
    "SpellName2" TEXT NULL,
    "SpellName3" TEXT NULL,
    "SpellName4" TEXT NULL,
    "SpellName5" TEXT NULL,
    "SpellName6" TEXT NULL,
    "SpellName7" TEXT NULL,
    "SpellName8" TEXT NULL,
    "Rank" TEXT NULL,
    "Rank2" TEXT NULL,
    "Rank3" TEXT NULL,
    "Rank4" TEXT NULL,
    "Rank5" TEXT NULL,
    "Rank6" TEXT NULL,
    "Rank7" TEXT NULL,
    "Rank8" TEXT NULL,
    "ManaCostPercentage" INTEGER NOT NULL,
    "StartRecoveryCategory" INTEGER NOT NULL,
    "StartRecoveryTime" INTEGER NOT NULL,
    "MaxTargetLevel" INTEGER NOT NULL,
    "SpellFamilyName" INTEGER NOT NULL,
    "SpellFamilyFlags" INTEGER NOT NULL,
    "MaxAffectedTargets" INTEGER NOT NULL,
    "DmgClass" INTEGER NOT NULL,
    "PreventionType" INTEGER NOT NULL,
    "DmgMultiplier1" REAL NOT NULL,
    "DmgMultiplier2" REAL NOT NULL,
    "DmgMultiplier3" REAL NOT NULL,
    "IsServerSide" INTEGER NOT NULL
);
CREATE TABLE "taxi_nodes" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_taxi_nodes" PRIMARY KEY,
    "map_id" INTEGER NOT NULL,
    "x" REAL NOT NULL,
    "y" REAL NOT NULL,
    "z" REAL NOT NULL,
    "name" TEXT NOT NULL,
    "mount_horde" INTEGER NOT NULL,
    "mount_alliance" INTEGER NOT NULL
);
CREATE TABLE "taxi_path" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_taxi_path" PRIMARY KEY,
    "from_node" INTEGER NOT NULL,
    "to_node" INTEGER NOT NULL,
    "price" INTEGER NOT NULL
);
CREATE TABLE "world_schema" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_world_schema" PRIMARY KEY,
    "Version" INTEGER NOT NULL
);
CREATE UNIQUE INDEX "IX_account_Username" ON "account" ("Username");
CREATE INDEX "IX_character_inventory_guid" ON "character_inventory" ("guid");
CREATE INDEX "IX_characters_AccountId" ON "characters" ("AccountId");
CREATE UNIQUE INDEX "IX_characters_Name" ON "characters" ("Name");
CREATE INDEX "IX_creature_spawn_MapId" ON "creature_spawn" ("MapId");
CREATE UNIQUE INDEX "IX_guild_member_CharacterId" ON "guild_member" ("CharacterId");
CREATE INDEX "IX_item_instance_owner_guid" ON "item_instance" ("owner_guid");
