// The aura support baseline.
// Seeded from the live registrations of a composed world host plus a scan of AuraType references (see docs/areas/aura-engine.md).
// The totality test (AuraSupportTests) keeps this table honest: a type with a registered handler must be Handler, and no type may be
// missing. A later slice that adds a handler changes its row in the same commit.
namespace ArcaneCore.Game.Spells;

public static partial class AuraSupport
{
    private static readonly AuraSupportEntry[] s_baseline =
    [
        new(AuraType.None, AuraSupportLevel.NotAnAura, "HandleNULL", 65, "ImmunityRules.cs", ""),
        new(AuraType.BindSight, AuraSupportLevel.Unsupported, "HandleBindSight", 66, "", ""),
        new(AuraType.ModPossess, AuraSupportLevel.Handler, "HandleModPossess", 67, "CharmService.Possess.cs, CharmCastCheck.cs, SpellSystem.Dispel.cs", ""),
        new(AuraType.PeriodicDamage, AuraSupportLevel.Handler, "HandlePeriodicDamage", 68, "SpellCoefficients.cs, SpellInfoRuleExtensions.cs, SpellPackets.cs", ""),
        new(AuraType.Dummy, AuraSupportLevel.Handler, "HandleAuraDummy", 69, "SpellCoefficients.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.ModConfuse, AuraSupportLevel.Handler, "HandleModConfuse", 70, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ModCharm, AuraSupportLevel.Handler, "HandleModCharm", 71, "CharmService.Charm.cs, CharmCastCheck.cs, SpellSystem.Dispel.cs", ""),
        new(AuraType.ModFear, AuraSupportLevel.Handler, "HandleModFear", 72, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.PeriodicHeal, AuraSupportLevel.Handler, "HandlePeriodicHeal", 73, "SpellCoefficients.cs, SpellInfoRuleExtensions.cs, SpellPackets.cs", ""),
        new(AuraType.ModAttackspeed, AuraSupportLevel.Handler, "HandleModAttackSpeed", 74, "AttackSpeedAuras.cs", ""),
        new(AuraType.ModThreat, AuraSupportLevel.Handler, "HandleModThreat", 75, "SpellSystem.Auras.cs, SpellThreatModifiers.cs, SpellThreat.cs", "threat-and-aggro"),
        new(AuraType.ModTaunt, AuraSupportLevel.Handler, "HandleModTaunt", 76, "ThreatAuras.cs", ""),
        new(AuraType.ModStun, AuraSupportLevel.Handler, "HandleAuraModStun", 77, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ModDamageDone, AuraSupportLevel.Referenced, "HandleModDamageDone", 78, "SpellBonusModule.cs", ""),
        new(AuraType.ModDamageTaken, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 79, "SpellBinary.cs, SpellBonusModule.cs", ""),
        new(AuraType.DamageShield, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 80, "SpellSystem.Auras.cs, SpellSystem.CombatProcs.cs", ""),
        new(AuraType.ModStealth, AuraSupportLevel.Handler, "HandleModStealth", 81, "GeneralCastChecks.cs, SpellSystem.AuraInterrupt.cs, StealthAuras.cs", ""),
        new(AuraType.ModStealthDetect, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 82, "StealthDetection.cs, StealthFeature.cs", ""),
        new(AuraType.ModInvisibility, AuraSupportLevel.Handler, "HandleInvisibility", 83, "../../Stealth/InvisibilityAuras.cs", ""),
        new(AuraType.ModInvisibilityDetection, AuraSupportLevel.Handler, "HandleInvisibilityDetect", 84, "../../Stealth/InvisibilityAuras.cs", ""),
        new(AuraType.ObsModHealth, AuraSupportLevel.Handler, "HandleAuraModTotalHealthPercentRegen", 85, "SpellPackets.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.ObsModMana, AuraSupportLevel.Handler, "HandleAuraModTotalManaPercentRegen", 86, "PeriodicTiming.cs, SpellPackets.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.ModResistance, AuraSupportLevel.Handler, "HandleAuraModResistance", 87, "SpellBinary.cs, StatAuras.cs", ""),
        new(AuraType.PeriodicTriggerSpell, AuraSupportLevel.Handler, "HandlePeriodicTriggerSpell", 88, "QuestRewardEffects.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.PeriodicEnergize, AuraSupportLevel.Handler, "HandlePeriodicEnergize", 89, "SpellPackets.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.ModPacify, AuraSupportLevel.Handler, "HandleAuraModPacify", 90, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ModRoot, AuraSupportLevel.Handler, "HandleAuraModRoot", 91, "CcAuraHandlers.cs, SpellBinary.cs, SpellCoefficients.cs", ""),
        new(AuraType.ModSilence, AuraSupportLevel.Handler, "HandleAuraModSilence", 92, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ReflectSpells, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 93, "SpellSystem.Auras.cs, SpellSystem.Reflect.cs", ""),
        new(AuraType.ModStat, AuraSupportLevel.Handler, "HandleAuraModStat", 94, "StatAuras.cs", ""),
        new(AuraType.ModSkill, AuraSupportLevel.Handler, "HandleAuraModSkill", 95, "SkillAuras.cs", ""),
        new(AuraType.ModIncreaseSpeed, AuraSupportLevel.Handler, "HandleAuraModIncreaseSpeed", 96, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModIncreaseMountedSpeed, AuraSupportLevel.Handler, "HandleAuraModIncreaseMountedSpeed", 97, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModDecreaseSpeed, AuraSupportLevel.Handler, "HandleAuraModDecreaseSpeed", 98, "SpeedAuras.cs, SpellBinary.cs, SpellCoefficients.cs", ""),
        new(AuraType.ModIncreaseHealth, AuraSupportLevel.Handler, "HandleAuraModIncreaseHealth", 99, "PercentStatAuras.cs", ""),
        new(AuraType.ModIncreaseEnergy, AuraSupportLevel.Handler, "HandleAuraModIncreaseEnergy", 100, "PercentStatAuras.cs", ""),
        new(AuraType.ModShapeshift, AuraSupportLevel.Handler, "HandleAuraModShapeshift", 101, "ShapeshiftService.cs", "druid-forms"),
        new(AuraType.EffectImmunity, AuraSupportLevel.Handler, "HandleAuraModEffectImmunity", 102, "ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.StateImmunity, AuraSupportLevel.Handler, "HandleAuraModStateImmunity", 103, "ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.SchoolImmunity, AuraSupportLevel.Handler, "HandleAuraModSchoolImmunity", 104, "CasterAuraGate.cs, ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.DamageImmunity, AuraSupportLevel.Handler, "HandleAuraModDmgImmunity", 105, "ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.DispelImmunity, AuraSupportLevel.Handler, "HandleAuraModDispelImmunity", 106, "CasterAuraGate.cs, ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.ProcTriggerSpell, AuraSupportLevel.Handler, "HandleAuraProcTriggerSpell", 107, "BuiltInProcHandlers.cs, SpellSystem.Auras.cs, SpellSystem.Procs.cs", ""),
        new(AuraType.ProcTriggerDamage, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 108, "BuiltInProcHandlers.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.TrackCreatures, AuraSupportLevel.Handler, "HandleAuraTrackCreatures", 109, "RangedHandlers.cs, SpellInfo.cs, TrackingAuras.cs", ""),
        new(AuraType.TrackResources, AuraSupportLevel.Handler, "HandleAuraTrackResources", 110, "RangedHandlers.cs, SpellInfo.cs, TrackingAuras.cs", ""),
        new(AuraType.ModParrySkill, AuraSupportLevel.Unsupported, "HandleUnused", 111, "", ""),
        new(AuraType.ModParryPercent, AuraSupportLevel.Handler, "HandleAuraModParryPercent", 112, "PercentStatAuras.cs", ""),
        new(AuraType.ModDodgeSkill, AuraSupportLevel.Unsupported, "HandleUnused", 113, "", ""),
        new(AuraType.ModDodgePercent, AuraSupportLevel.Handler, "HandleAuraModDodgePercent", 114, "PercentStatAuras.cs", ""),
        new(AuraType.ModBlockSkill, AuraSupportLevel.Unsupported, "HandleUnused", 115, "", ""),
        new(AuraType.ModBlockPercent, AuraSupportLevel.Handler, "HandleAuraModBlockPercent", 116, "PercentStatAuras.cs", ""),
        new(AuraType.ModCritPercent, AuraSupportLevel.Referenced, "HandleAuraModCritPercent", 117, "SpellCombatRules.cs", ""),
        new(AuraType.PeriodicLeech, AuraSupportLevel.Handler, "HandlePeriodicLeech", 118, "DrainAuras.cs, SpellCoefficients.cs, SpellInfoRuleExtensions.cs", ""),
        new(AuraType.ModHitChance, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 119, "", ""),
        new(AuraType.ModSpellHitChance, AuraSupportLevel.Referenced, "HandleModSpellHitChance", 120, "SpellCombatRules.cs, SpellSystem.Feign.cs", ""),
        new(AuraType.Transform, AuraSupportLevel.Handler, "HandleAuraTransform", 121, "TransformAuras.cs, ShapeshiftService.cs, CombatOptions.cs", ""),
        new(AuraType.ModSpellCritChance, AuraSupportLevel.Referenced, "HandleModSpellCritChance", 122, "SpellCombatRules.cs", ""),
        new(AuraType.ModIncreaseSwimSpeed, AuraSupportLevel.Handler, "HandleAuraModIncreaseSwimSpeed", 123, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModDamageDoneCreature, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 124, "", ""),
        new(AuraType.ModPacifySilence, AuraSupportLevel.Handler, "HandleAuraModPacifyAndSilence", 125, "CasterAuraGate.cs, CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ModScale, AuraSupportLevel.Handler, "HandleAuraModScale", 126, "VisualAuras.cs", ""),
        new(AuraType.PeriodicHealthFunnel, AuraSupportLevel.Unsupported, "HandlePeriodicHealthFunnel", 127, "", ""),
        new(AuraType.PeriodicManaFunnel, AuraSupportLevel.Unsupported, "HandleUnused", 128, "", ""),
        new(AuraType.PeriodicManaLeech, AuraSupportLevel.Handler, "HandlePeriodicManaLeech", 129, "CasterPeriodicPackets.cs, DrainAuras.cs", ""),
        new(AuraType.ModCastingSpeedNotStack, AuraSupportLevel.Unsupported, "HandleModCastingSpeed", 130, "", "aura-transform (not scheduled)"),
        new(AuraType.FeignDeath, AuraSupportLevel.Handler, "HandleFeignDeath", 131, "RangedHandlers.cs, SpellSystem.Feign.cs", ""),
        new(AuraType.ModDisarm, AuraSupportLevel.Handler, "HandleAuraModDisarm", 132, "CcAuraHandlers.cs, CcState.cs, SpellBinary.cs", ""),
        new(AuraType.ModStalked, AuraSupportLevel.Handler, "HandleAuraModStalked", 133, "RangedHandlers.cs, SpellSystem.Stealth.cs, SpellSystem.Tracking.cs", ""),
        new(AuraType.SchoolAbsorb, AuraSupportLevel.Referenced, "HandleSchoolAbsorb", 134, "SpellSystem.Mitigation.cs", ""),
        new(AuraType.ExtraAttacks, AuraSupportLevel.Unsupported, "HandleUnused", 135, "", ""),
        new(AuraType.ModSpellCritChanceSchool, AuraSupportLevel.Referenced, "HandleModSpellCritChanceSchool", 136, "SpellCombatRules.cs", ""),
        new(AuraType.ModPowerCostSchoolPct, AuraSupportLevel.Handler, "HandleModPowerCostPCT", 137, "PowerCostAuras.cs", ""),
        new(AuraType.ModPowerCostSchool, AuraSupportLevel.Handler, "HandleModPowerCost", 138, "PowerCostAuras.cs", ""),
        new(AuraType.ReflectSpellsSchool, AuraSupportLevel.Handler, "HandleReflectSpellsSchool", 139, "BuiltInProcHandlers.cs, SpellSystem.Auras.cs, SpellSystem.Reflect.cs", ""),
        new(AuraType.ModLanguage, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 140, "ChatLanguageQueries.cs", ""),
        new(AuraType.FarSight, AuraSupportLevel.Unsupported, "HandleFarSight", 141, "", ""),
        new(AuraType.MechanicImmunity, AuraSupportLevel.Handler, "HandleModMechanicImmunity", 142, "CasterAuraGate.cs, ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.Mounted, AuraSupportLevel.Handler, "HandleAuraMounted", 143, "MountAura.cs, MountService.cs", ""),
        new(AuraType.ModDamagePercentDone, AuraSupportLevel.Referenced, "HandleModDamagePercentDone", 144, "SpellBonusModule.cs", ""),
        new(AuraType.ModPercentStat, AuraSupportLevel.Handler, "HandleModPercentStat", 145, "PercentStatAuras.cs", ""),
        new(AuraType.SplitDamagePct, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 146, "SpellSystem.Mitigation.cs", ""),
        new(AuraType.WaterBreathing, AuraSupportLevel.Handler, "HandleWaterBreathing", 147, "WaterBreathingAuras.cs", ""),
        new(AuraType.ModBaseResistance, AuraSupportLevel.Handler, "HandleModBaseResistance", 148, "PercentStatAuras.cs", ""),
        new(AuraType.ModRegen, AuraSupportLevel.Handler, "HandleModRegen", 149, "FoodDrinkAuras.cs, RegenModifiers.cs", ""),
        new(AuraType.ModPowerRegen, AuraSupportLevel.Handler, "HandleModPowerRegen", 150, "SpellSystem.PowerRegenAuras.cs, RegenModifiers.cs", ""),
        new(AuraType.ChannelDeathItem, AuraSupportLevel.Handler, "HandleChannelDeathItem", 151, "../Warlock/ChannelDeathItemAura.cs", ""),
        new(AuraType.ModDamagePercentTaken, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 152, "SpellBonusModule.cs", ""),
        new(AuraType.ModHealthRegenPercent, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 153, "HealthRegenPercentAuras.cs, MapCombat.Regen.cs", ""),
        new(AuraType.PeriodicDamagePercent, AuraSupportLevel.Handler, "HandlePeriodicDamagePCT", 154, "SpellInfoRuleExtensions.cs, SpellPackets.cs, SpellSystem.Auras.cs", ""),
        new(AuraType.ModResistChance, AuraSupportLevel.Unsupported, "HandleUnused", 155, "", ""),
        new(AuraType.ModDetectRange, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 156, "", ""),
        new(AuraType.PreventsFleeing, AuraSupportLevel.Referenced, "HandlePreventFleeing", 157, "CcAuraHandlers.cs, CcState.cs", ""),
        new(AuraType.ModUnattackable, AuraSupportLevel.Unsupported, "HandleModUnattackable", 158, "", ""),
        new(AuraType.InterruptRegen, AuraSupportLevel.Referenced, "HandleInterruptRegen", 159, "MapCombat.Regen.cs", ""),
        new(AuraType.Ghost, AuraSupportLevel.Handler, "HandleAuraGhost", 160, "GhostAuras.cs", ""),
        new(AuraType.SpellMagnet, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 161, "../Magnet/SpellMagnetAuras.cs", ""),
        new(AuraType.ManaShield, AuraSupportLevel.Referenced, "HandleManaShield", 162, "SpellSystem.Mitigation.cs", ""),
        new(AuraType.ModSkillTalent, AuraSupportLevel.Handler, "HandleAuraModSkill", 163, "SkillAuras.cs", ""),
        new(AuraType.ModAttackPower, AuraSupportLevel.Handler, "HandleAuraModAttackPower", 164, "StatAuras.cs", ""),
        new(AuraType.AurasVisible, AuraSupportLevel.Unsupported, "HandleAurasVisible", 165, "", ""),
        new(AuraType.ModResistancePct, AuraSupportLevel.Handler, "HandleModResistancePercent", 166, "PercentStatAuras.cs", ""),
        new(AuraType.ModMeleeAttackPowerVersus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 167, "", ""),
        new(AuraType.ModTotalThreat, AuraSupportLevel.Handler, "HandleAuraModTotalThreat", 168, "ThreatAuras.cs", ""),
        new(AuraType.WaterWalk, AuraSupportLevel.Handler, "HandleAuraWaterWalk", 169, "MovementFlagAuras.cs", ""),
        new(AuraType.FeatherFall, AuraSupportLevel.Handler, "HandleAuraFeatherFall", 170, "FallObserver.cs, MovementFlagAuras.cs", ""),
        new(AuraType.Hover, AuraSupportLevel.Handler, "HandleAuraHover", 171, "FallObserver.cs, MovementFlagAuras.cs", ""),
        new(AuraType.AddFlatModifier, AuraSupportLevel.Handler, "HandleAddModifier", 172, "../Mods/SpellModModule.cs", ""),
        new(AuraType.AddPctModifier, AuraSupportLevel.Handler, "HandleAddModifier", 173, "../Mods/SpellModModule.cs", ""),
        new(AuraType.AddTargetTrigger, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 174, "BuiltInProcHandlers.cs, SpellSystem.Auras.cs, SpellSystem.SpellProcs.cs", ""),
        new(AuraType.ModPowerRegenPercent, AuraSupportLevel.Referenced, "HandleModPowerRegenPCT", 175, "CombatOptions.cs", ""),
        new(AuraType.AddCasterHitTrigger, AuraSupportLevel.Unsupported, "HandleUnused", 176, "", ""),
        new(AuraType.OverrideClassScripts, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 177, "ShapeshiftService.cs", "druid-forms"),
        new(AuraType.ModRangedDamageTaken, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 178, "", ""),
        new(AuraType.ModRangedDamageTakenPct, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 179, "", ""),
        new(AuraType.ModHealing, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 180, "SpellBonusModule.cs", ""),
        new(AuraType.ModRegenDuringCombat, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 181, "CombatHealthRegenAuras.cs, MapCombat.Regen.cs", ""),
        new(AuraType.ModMechanicResistance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 182, "MechanicResistRule.cs, SpellCombatRules.cs", ""),
        new(AuraType.ModHealingPct, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 183, "DirectCombatEffects.cs, SpellBonusModule.cs", ""),
        new(AuraType.SharePetTracking, AuraSupportLevel.Unsupported, "HandleUnused", 184, "", ""),
        new(AuraType.Untrackable, AuraSupportLevel.Unsupported, "HandleAuraUntrackable", 185, "", ""),
        new(AuraType.Empathy, AuraSupportLevel.Unsupported, "HandleAuraEmpathy", 186, "", ""),
        new(AuraType.ModOffhandDamagePct, AuraSupportLevel.Unsupported, "HandleModOffhandDamagePercent", 187, "", ""),
        new(AuraType.ModTargetResistance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 188, "SpellCombatRules.cs", ""),
        new(AuraType.ModRangedAttackPower, AuraSupportLevel.Handler, "HandleAuraModRangedAttackPower", 189, "StatAuras.cs", ""),
        new(AuraType.ModMeleeDamageTaken, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 190, "", ""),
        new(AuraType.ModMeleeDamageTakenPct, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 191, "", ""),
        new(AuraType.RangedAttackPowerAttackerBonus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 192, "", ""),
        new(AuraType.ModPossessPet, AuraSupportLevel.Handler, "HandleModPossessPet", 193, "CharmService.Possess.cs, CharmCastCheck.cs", ""),
        new(AuraType.ModSpeedAlways, AuraSupportLevel.Handler, "HandleAuraModIncreaseSpeed", 194, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModMountedSpeedAlways, AuraSupportLevel.Handler, "HandleAuraModIncreaseMountedSpeed", 195, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModRangedAttackPowerVersus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 196, "", ""),
        new(AuraType.ModIncreaseEnergyPercent, AuraSupportLevel.Handler, "HandleAuraModIncreaseEnergyPercent", 197, "PercentStatAuras.cs", ""),
        new(AuraType.ModIncreaseHealthPercent, AuraSupportLevel.Handler, "HandleAuraModIncreaseHealthPercent", 198, "PercentStatAuras.cs", ""),
        new(AuraType.ModManaRegenInterrupt, AuraSupportLevel.Handler, "HandleAuraModRegenInterrupt", 199, "ManaRegenInterruptAuras.cs, RegenModifiers.cs", ""),
        new(AuraType.ModHealingDone, AuraSupportLevel.Referenced, "HandleModHealingDone", 200, "SpellBonusModule.cs", ""),
        new(AuraType.ModHealingDonePercent, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 201, "DirectCombatEffects.cs, SpellBonusModule.cs", ""),
        new(AuraType.ModTotalStatPercentage, AuraSupportLevel.Handler, "HandleModTotalPercentStat", 202, "PercentStatAuras.cs", ""),
        new(AuraType.ModMeleeHaste, AuraSupportLevel.Handler, "HandleModMeleeSpeedPct", 203, "AttackSpeedAuras.cs", ""),
        new(AuraType.ForceReaction, AuraSupportLevel.Handler, "HandleForceReaction", 204, "../ReputationSpellHandlers.cs", ""),
        new(AuraType.ModRangedHaste, AuraSupportLevel.Handler, "HandleAuraModRangedHaste", 205, "AttackSpeedAuras.cs", ""),
        new(AuraType.ModRangedAmmoHaste, AuraSupportLevel.Handler, "HandleRangedAmmoHaste", 206, "AttackSpeedAuras.cs", ""),
        new(AuraType.ModBaseResistancePct, AuraSupportLevel.Handler, "HandleAuraModBaseResistancePercent", 207, "PercentStatAuras.cs", ""),
        new(AuraType.ModResistanceExclusive, AuraSupportLevel.Unsupported, "HandleAuraModResistanceExclusive", 208, "", ""),
        new(AuraType.SafeFall, AuraSupportLevel.Handler, "HandleAuraSafeFall", 209, "FallObserver.cs, MovementFlagAuras.cs", ""),
        new(AuraType.Charisma, AuraSupportLevel.Unsupported, "HandleUnused", 210, "", ""),
        new(AuraType.Persuaded, AuraSupportLevel.Unsupported, "HandleUnused", 211, "", ""),
        new(AuraType.MechanicImmunityMask, AuraSupportLevel.Handler, "HandleModMechanicImmunityMask", 212, "CasterAuraGate.cs, ImmunityAuraHandlers.cs, ImmunityRules.cs", ""),
        new(AuraType.RetainComboPoints, AuraSupportLevel.Referenced, "HandleAuraRetainComboPoints", 213, "ComboPointService.cs", ""),
        new(AuraType.ResistPushback, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 214, "SpellSystem.Pushback.cs", ""),
        new(AuraType.ModShieldBlockvaluePct, AuraSupportLevel.Handler, "HandleShieldBlockValue", 215, "PercentStatAuras.cs", ""),
        new(AuraType.TrackStealthed, AuraSupportLevel.Handler, "HandleAuraTrackStealthed", 216, "RangedHandlers.cs, SpellInfo.cs, TrackingAuras.cs", ""),
        new(AuraType.ModDetectedRange, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 217, "", ""),
        new(AuraType.SplitDamageFlat, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 218, "SpellSystem.Mitigation.cs", ""),
        new(AuraType.ModStealthLevel, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 219, "StealthDetection.cs, StealthFeature.cs", ""),
        new(AuraType.ModWaterBreathing, AuraSupportLevel.Handler, "HandleModWaterBreathing", 220, "WaterBreathingAuras.cs", ""),
        new(AuraType.ModReputationGain, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 221, "../ReputationSpellHandlers.cs", ""),
        new(AuraType.PetDamageMulti, AuraSupportLevel.Unsupported, "HandleUnused", 222, "", ""),
        new(AuraType.ModShieldBlockvalue, AuraSupportLevel.Handler, "HandleShieldBlockValue", 223, "PercentStatAuras.cs", ""),
        new(AuraType.NoPvpCredit, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 224, "../../Honor/HonorSpellEffects.cs", ""),
        new(AuraType.ModAoeAvoidance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 225, "SpellCombatRules.cs", ""),
        new(AuraType.ModHealthRegenInCombat, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 226, "CombatFlatHealthRegenAuras.cs, MapCombat.Regen.cs", ""),
        new(AuraType.PowerBurnMana, AuraSupportLevel.Unsupported, "HandleAuraPowerBurn", 227, "", ""),
        new(AuraType.ModCritDamageBonus, AuraSupportLevel.Unsupported, "HandleUnused", 228, "", ""),
        new(AuraType.Unk164, AuraSupportLevel.Unsupported, "HandleUnused", 229, "", ""),
        new(AuraType.MeleeAttackPowerAttackerBonus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 230, "", ""),
        new(AuraType.ModAttackPowerPct, AuraSupportLevel.Handler, "HandleAuraModAttackPowerPercent", 231, "PercentStatAuras.cs", ""),
        new(AuraType.ModRangedAttackPowerPct, AuraSupportLevel.Handler, "HandleAuraModRangedAttackPowerPercent", 232, "PercentStatAuras.cs", ""),
        new(AuraType.ModDamageDoneVersus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 233, "", ""),
        new(AuraType.ModCritPercentVersus, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 234, "SpellCombatRules.cs", ""),
        new(AuraType.DetectAmore, AuraSupportLevel.Unsupported, "HandleDetectAmore", 235, "", ""),
        new(AuraType.ModSpeedNotStack, AuraSupportLevel.Handler, "HandleAuraModIncreaseSpeed", 236, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.ModMountedSpeedNotStack, AuraSupportLevel.Handler, "HandleAuraModIncreaseMountedSpeed", 237, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.AllowChampionSpells, AuraSupportLevel.Unsupported, "HandleUnused", 238, "", ""),
        new(AuraType.ModSpellDamageOfStatPercent, AuraSupportLevel.Referenced, "HandleModSpellDamagePercentFromStat", 239, "SpellBonusModule.cs", ""),
        new(AuraType.ModSpellHealingOfStatPercent, AuraSupportLevel.Referenced, "HandleModSpellHealingPercentFromStat", 240, "SpellBonusModule.cs", ""),
        new(AuraType.SpiritOfRedemption, AuraSupportLevel.Unsupported, "HandleSpiritOfRedemption", 241, "", "graveyards-resurrection"),
        new(AuraType.AoeCharm, AuraSupportLevel.Handler, "HandleAuraAoeCharm", 242, "CharmService.Charm.cs", ""),
        new(AuraType.ModDebuffResistance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 243, "SpellCombatRules.cs", ""),
        new(AuraType.ModAttackerSpellCritChance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 244, "SpellCombatRules.cs", ""),
        new(AuraType.ModFlatSpellDamageVersus, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 245, "", ""),
        new(AuraType.ModFlatSpellCritDamageVersus, AuraSupportLevel.Unsupported, "HandleUnused", 246, "", ""),
        new(AuraType.ModResistanceOfStatPercent, AuraSupportLevel.Unsupported, "HandleAuraModResistenceOfStatPercent", 247, "", ""),
        new(AuraType.ModCriticalThreat, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 248, "", "threat-and-aggro"),
        new(AuraType.ModAttackerMeleeHitChance, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 249, "", ""),
        new(AuraType.ModAttackerRangedHitChance, AuraSupportLevel.Unsupported, "HandleNoImmediateEffect", 250, "", ""),
        new(AuraType.ModAttackerSpellHitChance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 251, "SpellCombatRules.cs", ""),
        new(AuraType.ModAttackerMeleeCritChance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 252, "SpellCombatRules.cs", ""),
        new(AuraType.ModAttackerRangedCritChance, AuraSupportLevel.Referenced, "HandleNoImmediateEffect", 253, "SpellCombatRules.cs", ""),
        new(AuraType.ModRating, AuraSupportLevel.Unsupported, "HandleUnused", 254, "", ""),
        new(AuraType.ModFactionReputationGain, AuraSupportLevel.Handler, "HandleNoImmediateEffect", 255, "../ReputationSpellHandlers.cs", ""),
        new(AuraType.UseNormalMovementSpeed, AuraSupportLevel.Handler, "HandleAuraModUseNormalSpeed", 256, "SpeedAuras.cs, UnitSpeed.cs", ""),
        new(AuraType.AuraSpell, AuraSupportLevel.Unsupported, "HandleAuraAuraSpell", 258, "", ""),
    ];
}
