-- The auth schema exactly as the Codex line created it at commit 0e07c29b (schema version 4).
-- Generated by running that commit's SchemaBootstrapper against an empty SQLite file and reading
-- sqlite_master in creation order; it matches the live Codex-line databases of 2026-10-07 object for object.
CREATE TABLE "auth_schema" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_auth_schema" PRIMARY KEY,
    "Version" INTEGER NOT NULL
);
CREATE TABLE "account" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_account" PRIMARY KEY AUTOINCREMENT,
    "Username" TEXT NOT NULL,
    "Salt" BLOB NOT NULL,
    "Verifier" BLOB NOT NULL,
    "SessionKey" BLOB NULL,
    "Status" INTEGER NOT NULL,
    "Security" INTEGER NOT NULL
);
CREATE UNIQUE INDEX "IX_account_Username" ON "account" ("Username");
CREATE TABLE "account_banned" (
    "BanId" INTEGER NOT NULL CONSTRAINT "PK_account_banned" PRIMARY KEY AUTOINCREMENT,
    "AccountId" INTEGER NOT NULL,
    "BanDate" INTEGER NOT NULL,
    "UnbanDate" INTEGER NOT NULL,
    "BannedBy" TEXT NOT NULL,
    "BanReason" TEXT NOT NULL,
    "Active" INTEGER NOT NULL,
    "Realm" INTEGER NOT NULL
);
CREATE INDEX "IX_account_banned_AccountId_Active" ON "account_banned" ("AccountId", "Active");
CREATE INDEX "IX_account_banned_Active" ON "account_banned" ("Active");
CREATE TABLE "ip_banned" (
    "Ip" TEXT NOT NULL CONSTRAINT "PK_ip_banned" PRIMARY KEY,
    "BanDate" INTEGER NOT NULL,
    "UnbanDate" INTEGER NOT NULL,
    "BannedBy" TEXT NOT NULL,
    "BanReason" TEXT NOT NULL
);
CREATE TABLE "managed_playerbot_provision" (
    "BotId" TEXT NOT NULL CONSTRAINT "PK_managed_playerbot_provision" PRIMARY KEY,
    "AccountId" INTEGER NOT NULL,
    "AccountName" TEXT NOT NULL,
    "CreatedUnix" INTEGER NOT NULL
);
CREATE UNIQUE INDEX "IX_managed_playerbot_provision_AccountId" ON "managed_playerbot_provision" ("AccountId");
CREATE TABLE "realmlist" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_realmlist" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Address" TEXT NOT NULL,
    "Type" INTEGER NOT NULL,
    "Flags" INTEGER NOT NULL,
    "Population" REAL NOT NULL,
    "Category" INTEGER NOT NULL
);
INSERT INTO "auth_schema" ("Id", "Version") VALUES (1, 4);
