-- The characters schema exactly as the Codex line created it at commit 0e07c29b (schema version 25).
-- Generated by running that commit's SchemaBootstrapper against an empty SQLite file and reading
-- sqlite_master in creation order; it matches the live Codex-line databases of 2026-10-07 object for object.
CREATE TABLE "characters_schema" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_characters_schema" PRIMARY KEY,
    "Version" INTEGER NOT NULL
);
CREATE TABLE "account_data" (
    "AccountId" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL,
    "Time" INTEGER NOT NULL,
    "Data" BLOB NOT NULL,
    CONSTRAINT "PK_account_data" PRIMARY KEY ("AccountId", "Type")
);
CREATE TABLE "account_tutorial" (
    "AccountId" INTEGER NOT NULL CONSTRAINT "PK_account_tutorial" PRIMARY KEY,
    "Tut0" INTEGER NOT NULL,
    "Tut1" INTEGER NOT NULL,
    "Tut2" INTEGER NOT NULL,
    "Tut3" INTEGER NOT NULL,
    "Tut4" INTEGER NOT NULL,
    "Tut5" INTEGER NOT NULL,
    "Tut6" INTEGER NOT NULL,
    "Tut7" INTEGER NOT NULL
);
CREATE TABLE "auction" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_auction" PRIMARY KEY,
    "house_id" INTEGER NOT NULL,
    "item_guid" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "item_count" INTEGER NOT NULL,
    "seller_guid" INTEGER NOT NULL,
    "start_bid" INTEGER NOT NULL,
    "buyout_price" INTEGER NOT NULL,
    "expire_time" INTEGER NOT NULL,
    "buyer_guid" INTEGER NOT NULL,
    "last_bid" INTEGER NOT NULL,
    "deposit" INTEGER NOT NULL
);
CREATE INDEX "IX_auction_expire_time" ON "auction" ("expire_time");
CREATE UNIQUE INDEX "IX_auction_item_guid" ON "auction" ("item_guid");
CREATE INDEX "IX_auction_seller_guid" ON "auction" ("seller_guid");
CREATE TABLE "character_action" (
    "CharacterId" INTEGER NOT NULL,
    "Button" INTEGER NOT NULL,
    "Action" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL,
    CONSTRAINT "PK_character_action" PRIMARY KEY ("CharacterId", "Button")
);
CREATE TABLE "character_aura" (
    "CharacterId" INTEGER NOT NULL,
    "Seq" INTEGER NOT NULL,
    "Spell" INTEGER NOT NULL,
    "CasterGuid" INTEGER NOT NULL,
    "CasterLevel" INTEGER NOT NULL,
    "StackCount" INTEGER NOT NULL,
    "Charges" INTEGER NOT NULL,
    "MaxDurationMs" INTEGER NOT NULL,
    "RemainingMs" INTEGER NOT NULL,
    "EffectMask" INTEGER NOT NULL,
    "Amount0" INTEGER NOT NULL,
    "Amount1" INTEGER NOT NULL,
    "Amount2" INTEGER NOT NULL,
    "PeriodicTimer0" INTEGER NOT NULL,
    "PeriodicTimer1" INTEGER NOT NULL,
    "PeriodicTimer2" INTEGER NOT NULL,
    "SavedAtUnixMs" INTEGER NOT NULL,
    CONSTRAINT "PK_character_aura" PRIMARY KEY ("CharacterId", "Seq")
);
CREATE TABLE "character_corpse" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_corpse" PRIMARY KEY,
    "MapId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "GhostTime" INTEGER NOT NULL,
    "Type" INTEGER NOT NULL
);
CREATE TABLE "character_deletion" (
    "operation_id" TEXT NOT NULL CONSTRAINT "PK_character_deletion" PRIMARY KEY,
    "character_id" INTEGER NOT NULL,
    "account_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "committed_at" INTEGER NOT NULL
);
CREATE INDEX "IX_character_deletion_account_id" ON "character_deletion" ("account_id");
CREATE UNIQUE INDEX "IX_character_deletion_character_id" ON "character_deletion" ("character_id");
CREATE TABLE "character_explored_zones" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_character_explored_zones" PRIMARY KEY,
    "explored_zones" TEXT NOT NULL
);
CREATE TABLE "character_forgotten_skills" (
    "guid" INTEGER NOT NULL,
    "skill" INTEGER NOT NULL,
    "value" INTEGER NOT NULL,
    CONSTRAINT "PK_character_forgotten_skills" PRIMARY KEY ("guid", "skill")
);
CREATE TABLE "character_instance" (
    "CharacterId" INTEGER NOT NULL,
    "InstanceId" INTEGER NOT NULL,
    "Permanent" INTEGER NOT NULL,
    CONSTRAINT "PK_character_instance" PRIMARY KEY ("CharacterId", "InstanceId")
);
CREATE INDEX "IX_character_instance_InstanceId" ON "character_instance" ("InstanceId");
CREATE TABLE "character_inventory" (
    "item_guid" INTEGER NOT NULL CONSTRAINT "PK_character_inventory" PRIMARY KEY,
    "guid" INTEGER NOT NULL,
    "bag" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL
);
CREATE INDEX "IX_character_inventory_guid" ON "character_inventory" ("guid");
CREATE TABLE "character_item_cooldown_owner" (
    "CharacterId" INTEGER NOT NULL,
    "SpellId" INTEGER NOT NULL,
    "ItemId" INTEGER NOT NULL,
    "Category" INTEGER NOT NULL,
    "SpellEndsAtUnixMs" INTEGER NOT NULL,
    "CategoryEndsAtUnixMs" INTEGER NOT NULL,
    CONSTRAINT "PK_character_item_cooldown_owner" PRIMARY KEY ("CharacterId", "SpellId", "ItemId")
);
CREATE TABLE "character_item_state" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_item_state" PRIMARY KEY,
    "AmmoId" INTEGER NOT NULL
);
CREATE TABLE "character_last_instance" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_last_instance" PRIMARY KEY,
    "MapId" INTEGER NOT NULL,
    "InstanceId" INTEGER NOT NULL
);
CREATE TABLE "character_pet" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_pet" PRIMARY KEY,
    "PetNumber" INTEGER NOT NULL,
    "Entry" INTEGER NOT NULL,
    "Level" INTEGER NOT NULL,
    "Experience" INTEGER NOT NULL,
    "Health" INTEGER NOT NULL,
    "Mana" INTEGER NOT NULL,
    "Happiness" INTEGER NOT NULL,
    "ReactState" INTEGER NOT NULL,
    "ActionBarJson" TEXT NOT NULL,
    "SpellsJson" TEXT NOT NULL,
    "IsCurrent" INTEGER NOT NULL,
    "Name" TEXT NOT NULL DEFAULT '',
    "NameTimestamp" INTEGER NOT NULL,
    "RenameAllowed" INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE "character_pet_cooldown" (
    "CharacterId" INTEGER NOT NULL,
    "PetNumber" INTEGER NOT NULL,
    "Kind" INTEGER NOT NULL,
    "SpellId" INTEGER NOT NULL,
    "Category" INTEGER NOT NULL,
    "EndsAtUnixMs" INTEGER NOT NULL,
    CONSTRAINT "PK_character_pet_cooldown" PRIMARY KEY ("CharacterId", "PetNumber", "Kind", "SpellId", "Category")
);
CREATE TABLE "character_queststatus" (
    "guid" INTEGER NOT NULL,
    "quest" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "rewarded" INTEGER NOT NULL,
    "explored" INTEGER NOT NULL,
    "timer" INTEGER NOT NULL,
    "mob_count1" INTEGER NOT NULL,
    "mob_count2" INTEGER NOT NULL,
    "mob_count3" INTEGER NOT NULL,
    "mob_count4" INTEGER NOT NULL,
    "item_count1" INTEGER NOT NULL,
    "item_count2" INTEGER NOT NULL,
    "item_count3" INTEGER NOT NULL,
    "item_count4" INTEGER NOT NULL,
    "reward_choice" INTEGER NOT NULL,
    CONSTRAINT "PK_character_queststatus" PRIMARY KEY ("guid", "quest")
);
CREATE TABLE "character_reputation" (
    "guid" INTEGER NOT NULL,
    "faction" INTEGER NOT NULL,
    "standing" INTEGER NOT NULL,
    "flags" INTEGER NOT NULL,
    CONSTRAINT "PK_character_reputation" PRIMARY KEY ("guid", "faction")
);
CREATE TABLE "character_reputation_watch" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_character_reputation_watch" PRIMARY KEY,
    "watched_faction" INTEGER NOT NULL
);
CREATE TABLE "character_skills" (
    "guid" INTEGER NOT NULL,
    "skill" INTEGER NOT NULL,
    "value" INTEGER NOT NULL,
    "max" INTEGER NOT NULL,
    CONSTRAINT "PK_character_skills" PRIMARY KEY ("guid", "skill")
);
CREATE TABLE "character_social" (
    "CharacterId" INTEGER NOT NULL,
    "OtherId" INTEGER NOT NULL,
    "Flags" INTEGER NOT NULL,
    CONSTRAINT "PK_character_social" PRIMARY KEY ("CharacterId", "OtherId")
);
CREATE TABLE "character_spell" (
    "CharacterId" INTEGER NOT NULL,
    "Spell" INTEGER NOT NULL,
    CONSTRAINT "PK_character_spell" PRIMARY KEY ("CharacterId", "Spell")
);
CREATE TABLE "character_spell_cooldown" (
    "CharacterId" INTEGER NOT NULL,
    "Kind" INTEGER NOT NULL,
    "Id" INTEGER NOT NULL,
    "EndsAtUnixMs" INTEGER NOT NULL,
    CONSTRAINT "PK_character_spell_cooldown" PRIMARY KEY ("CharacterId", "Kind", "Id")
);
CREATE TABLE "character_spell_disabled" (
    "CharacterId" INTEGER NOT NULL,
    "Spell" INTEGER NOT NULL,
    CONSTRAINT "PK_character_spell_disabled" PRIMARY KEY ("CharacterId", "Spell")
);
CREATE TABLE "character_talent" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_talent" PRIMARY KEY,
    "ResetMultiplier" INTEGER NOT NULL,
    "ResetTimeUnix" INTEGER NOT NULL
);
CREATE TABLE "character_taxi" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_character_taxi" PRIMARY KEY,
    "mask0" INTEGER NOT NULL,
    "mask1" INTEGER NOT NULL,
    "mask2" INTEGER NOT NULL,
    "mask3" INTEGER NOT NULL,
    "mask4" INTEGER NOT NULL,
    "mask5" INTEGER NOT NULL,
    "mask6" INTEGER NOT NULL,
    "mask7" INTEGER NOT NULL
);
CREATE TABLE "character_vitals" (
    "CharacterId" INTEGER NOT NULL CONSTRAINT "PK_character_vitals" PRIMARY KEY,
    "Health" INTEGER NOT NULL,
    "Power1" INTEGER NOT NULL,
    "Power2" INTEGER NOT NULL,
    "Power3" INTEGER NOT NULL,
    "Power4" INTEGER NOT NULL,
    "Power5" INTEGER NOT NULL,
    "Xp" INTEGER NOT NULL,
    "DeathExpireTime" INTEGER NOT NULL,
    "IsGhost" INTEGER NOT NULL
);
CREATE TABLE "characters" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_characters" PRIMARY KEY AUTOINCREMENT,
    "AccountId" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "Race" INTEGER NOT NULL,
    "Class" INTEGER NOT NULL,
    "Gender" INTEGER NOT NULL,
    "Skin" INTEGER NOT NULL,
    "Face" INTEGER NOT NULL,
    "HairStyle" INTEGER NOT NULL,
    "HairColor" INTEGER NOT NULL,
    "FacialHair" INTEGER NOT NULL,
    "Level" INTEGER NOT NULL,
    "MapId" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Z" REAL NOT NULL,
    "Orientation" REAL NOT NULL,
    "PlayedTime" INTEGER NOT NULL,
    "LevelPlayedTime" INTEGER NOT NULL,
    "Money" INTEGER NOT NULL,
    "ActionBarToggles" INTEGER NOT NULL,
    "HomeMapId" INTEGER NOT NULL,
    "HomeZoneId" INTEGER NOT NULL,
    "HomeX" REAL NOT NULL,
    "HomeY" REAL NOT NULL,
    "HomeZ" REAL NOT NULL
);
CREATE INDEX "IX_characters_AccountId" ON "characters" ("AccountId");
CREATE UNIQUE INDEX "IX_characters_Name" ON "characters" ("Name");
CREATE TABLE "economy_operation" (
    "id" TEXT NOT NULL CONSTRAINT "PK_economy_operation" PRIMARY KEY,
    "committed_at" INTEGER NOT NULL
);
CREATE TABLE "guild" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_guild" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "LeaderId" INTEGER NOT NULL,
    "Motd" TEXT NOT NULL,
    "Info" TEXT NOT NULL,
    "CreatedAt" INTEGER NOT NULL,
    "EmblemStyle" INTEGER NOT NULL,
    "EmblemColor" INTEGER NOT NULL,
    "BorderStyle" INTEGER NOT NULL,
    "BorderColor" INTEGER NOT NULL,
    "BackgroundColor" INTEGER NOT NULL
);
CREATE TABLE "guild_member" (
    "GuildId" INTEGER NOT NULL,
    "CharacterId" INTEGER NOT NULL,
    "Rank" INTEGER NOT NULL,
    "PublicNote" TEXT NOT NULL,
    "OfficerNote" TEXT NOT NULL,
    "Level" INTEGER NOT NULL,
    "ZoneId" INTEGER NOT NULL,
    "LogoutTime" INTEGER NOT NULL,
    CONSTRAINT "PK_guild_member" PRIMARY KEY ("GuildId", "CharacterId")
);
CREATE UNIQUE INDEX "IX_guild_member_CharacterId" ON "guild_member" ("CharacterId");
CREATE TABLE "guild_rank" (
    "GuildId" INTEGER NOT NULL,
    "RankId" INTEGER NOT NULL,
    "Name" TEXT NOT NULL,
    "Rights" INTEGER NOT NULL,
    CONSTRAINT "PK_guild_rank" PRIMARY KEY ("GuildId", "RankId")
);
CREATE TABLE "instance" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_instance" PRIMARY KEY,
    "MapId" INTEGER NOT NULL,
    "ResetTime" INTEGER NOT NULL
);
CREATE INDEX "IX_instance_MapId" ON "instance" ("MapId");
CREATE TABLE "instance_reset" (
    "MapId" INTEGER NOT NULL CONSTRAINT "PK_instance_reset" PRIMARY KEY,
    "ResetTime" INTEGER NOT NULL
);
CREATE TABLE "item_instance" (
    "guid" INTEGER NOT NULL CONSTRAINT "PK_item_instance" PRIMARY KEY,
    "owner_guid" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "creator_guid" INTEGER NOT NULL,
    "gift_creator_guid" INTEGER NOT NULL,
    "count" INTEGER NOT NULL,
    "duration" INTEGER NOT NULL,
    "charges" TEXT NOT NULL,
    "flags" INTEGER NOT NULL,
    "enchantments" TEXT NOT NULL,
    "random_property_id" INTEGER NOT NULL,
    "durability" INTEGER NOT NULL,
    "text" INTEGER NOT NULL
);
CREATE INDEX "IX_item_instance_owner_guid" ON "item_instance" ("owner_guid");
CREATE TABLE "item_loot" (
    "item_guid" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "amount" INTEGER NOT NULL,
    "quest" INTEGER NOT NULL,
    CONSTRAINT "PK_item_loot" PRIMARY KEY ("item_guid", "slot")
);
CREATE TABLE "item_loot_state" (
    "item_guid" INTEGER NOT NULL CONSTRAINT "PK_item_loot_state" PRIMARY KEY,
    "gold" INTEGER NOT NULL
);
CREATE TABLE "item_text" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_item_text" PRIMARY KEY,
    "text" TEXT NOT NULL
);
CREATE TABLE "loot_operation" (
    "id" TEXT NOT NULL CONSTRAINT "PK_loot_operation" PRIMARY KEY,
    "committed_at" INTEGER NOT NULL
);
CREATE TABLE "loot_state" (
    "instance_id" INTEGER NOT NULL,
    "spawn_guid" INTEGER NOT NULL,
    "source_entry" INTEGER NOT NULL,
    "loot_owner" INTEGER NOT NULL,
    "generation" INTEGER NOT NULL,
    "consumed" INTEGER NOT NULL,
    "respawn_at" INTEGER NOT NULL,
    CONSTRAINT "PK_loot_state" PRIMARY KEY ("instance_id", "spawn_guid")
);
CREATE TABLE "loot_state_item" (
    "instance_id" INTEGER NOT NULL,
    "spawn_guid" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "count" INTEGER NOT NULL,
    "is_quest" INTEGER NOT NULL,
    "is_per_player" INTEGER NOT NULL,
    "is_looted" INTEGER NOT NULL,
    CONSTRAINT "PK_loot_state_item" PRIMARY KEY ("instance_id", "spawn_guid", "slot")
);
CREATE TABLE "loot_state_player" (
    "instance_id" INTEGER NOT NULL,
    "spawn_guid" INTEGER NOT NULL,
    "slot" INTEGER NOT NULL,
    "character_id" INTEGER NOT NULL,
    "role" INTEGER NOT NULL,
    CONSTRAINT "PK_loot_state_player" PRIMARY KEY ("instance_id", "spawn_guid", "slot", "character_id", "role")
);
CREATE TABLE "mail" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_mail" PRIMARY KEY,
    "message_type" INTEGER NOT NULL,
    "stationery" INTEGER NOT NULL,
    "sender_guid" INTEGER NOT NULL,
    "receiver_guid" INTEGER NOT NULL,
    "subject" TEXT NOT NULL,
    "item_text_id" INTEGER NOT NULL,
    "item_guid" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "money" INTEGER NOT NULL,
    "cod" INTEGER NOT NULL,
    "checked" INTEGER NOT NULL,
    "deliver_time" INTEGER NOT NULL,
    "expire_time" INTEGER NOT NULL
);
CREATE INDEX "IX_mail_expire_time" ON "mail" ("expire_time");
CREATE INDEX "IX_mail_item_guid" ON "mail" ("item_guid");
CREATE INDEX "IX_mail_receiver_guid" ON "mail" ("receiver_guid");
CREATE TABLE "managed_playerbot" (
    "BotId" TEXT NOT NULL CONSTRAINT "PK_managed_playerbot" PRIMARY KEY,
    "AccountId" INTEGER NOT NULL,
    "CharacterId" INTEGER NOT NULL,
    "AccountName" TEXT NOT NULL,
    "DesiredEnabled" INTEGER NOT NULL,
    "State" INTEGER NOT NULL,
    "Goal" INTEGER NOT NULL,
    "TargetEntry" INTEGER NOT NULL,
    "QuestId" INTEGER NOT NULL,
    "Revision" INTEGER NOT NULL,
    "CreatedUnix" INTEGER NOT NULL,
    "UpdatedUnix" INTEGER NOT NULL,
    "ErrorCode" TEXT NULL
);
CREATE UNIQUE INDEX "IX_managed_playerbot_AccountId" ON "managed_playerbot" ("AccountId");
CREATE UNIQUE INDEX "IX_managed_playerbot_CharacterId" ON "managed_playerbot" ("CharacterId");
CREATE TABLE "petition" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_petition" PRIMARY KEY,
    "OwnerId" INTEGER NOT NULL,
    "CharterItemId" INTEGER NOT NULL,
    "Name" TEXT NOT NULL
);
CREATE UNIQUE INDEX "IX_petition_OwnerId" ON "petition" ("OwnerId");
CREATE TABLE "petition_sign" (
    "PetitionId" INTEGER NOT NULL,
    "PlayerId" INTEGER NOT NULL,
    "AccountId" INTEGER NOT NULL,
    CONSTRAINT "PK_petition_sign" PRIMARY KEY ("PetitionId", "PlayerId")
);
CREATE INDEX "IX_petition_sign_PlayerId" ON "petition_sign" ("PlayerId");
INSERT INTO "characters_schema" ("Id", "Version") VALUES (1, 25);
