<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ArcaneCore.Game.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ArcaneCore.Game\ArcaneCore.Game.csproj" />
    <ProjectReference Include="..\ThirdParty\DotRecast\DotRecast.Detour\DotRecast.Detour.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CreatureAi\validated-escort-waypoints.csv" CopyToOutputDirectory="PreserveNewest" TargetPath="validated-escort-waypoints.csv" />
  </ItemGroup>

</Project>
