using System.Runtime.CompilerServices;
using System.Text;
using ArcaneCore.Kernel.Accounts;
using ArcaneCore.Kernel.Configuration;
using ArcaneCore.World.Commands;
using ArcaneCore.World.Gm.Core;
using ArcaneCore.World.HotCode;
using ArcaneCore.World.HotCode.Modules;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace ArcaneCore.World.Tests.Docs;

/// <summary>One node (command or group) of the chat command tree.</summary>
internal sealed record CommandNode(string Path, int RequiredLevel, bool HasHandler, bool IsGroup, string Help, string LevelSource, bool DevOnly, string? RuntimeNote);

/// <summary>Builds and renders docs/reference/gm-commands.md from the live command table.</summary>
internal static class CommandReferenceRenderer
{
    /// <summary>Every node of the table the daemon builds, plus the roots registered at run time by the hot-code features.</summary>
    public static IReadOnlyList<CommandNode> Nodes(bool reloadEnabled, GmOptions? options = null)
    {
        options ??= new GmOptions();
        ServiceProvider services = new ServiceCollection()
            .AddSingleton<IOptions<HotReloadOptions>>(Options.Create(new HotReloadOptions { Commands = reloadEnabled }))
            .BuildServiceProvider();
        CommandTable table = ChatCommands.CreateTable(options, services);

        var nodes = new List<CommandNode>();
        foreach (ChatCommand root in table.Roots)
        {
            Walk(root, string.Empty, options, devOnly: root.Name.Equals("reload", StringComparison.OrdinalIgnoreCase), runtimeNote: null, nodes);
        }

        if (reloadEnabled)
        {
            // The runtime roots are added to the live table by CommandTableSource.TryAdd when their host starts; their
            // trees are built here from the same factories with placeholder (never invoked) collaborators.
            ChatCommand hotCode = HotCodeCommands.Create((HotCodeRefresh)RuntimeHelpers.GetUninitializedObject(typeof(HotCodeRefresh)), new HotCodeAudit(null));
            Walk(hotCode, string.Empty, options, devOnly: true, "added at start when `World:HotCode:Enabled` is true", nodes);
            ChatCommand hotModule = HotModuleCommands.Create((ModuleHost)RuntimeHelpers.GetUninitializedObject(typeof(ModuleHost)), new HotCodeAudit(null));
            Walk(hotModule, string.Empty, options, devOnly: true, "added at start when `World:HotCode:Modules:Enabled` is true", nodes);
        }

        return nodes;
    }

    private static void Walk(ChatCommand command, string prefix, GmOptions options, bool devOnly, string? runtimeNote, List<CommandNode> nodes)
    {
        string path = prefix.Length == 0 ? command.Name : prefix + " " + command.Name;
        string source = RetailCommandLevels.Of(path) is not null
            ? "retail table (RetailCommandLevels cites Chat.cpp)"
            : command.RetailLevel is not null ? "declared retail level" : "stored level through the map";
        nodes.Add(new CommandNode(path, command.RequiredLevel(options), command.Handler is not null, command.SubCommands.Count > 0, command.Help, source, devOnly, runtimeNote));
        foreach (ChatCommand child in command.SubCommands)
        {
            Walk(child, path, options, devOnly, runtimeNote, nodes);
        }
    }

    /// <summary>The lowest stored account that reaches a command of <paramref name="level"/>, or null when none does.</summary>
    public static AccountSecurity? MinimumAccount(int level, GmOptions options)
    {
        foreach (AccountSecurity security in Enum.GetValues<AccountSecurity>().OrderBy(s => (int)s))
        {
            if (options.LevelOf(security) >= level)
            {
                return security;
            }
        }

        return null;
    }

    public static string Render(IReadOnlyList<CommandNode> nodes, GmOptions options)
    {
        var sb = new StringBuilder();
        sb.Append("# GM command reference\n\n");
        sb.Append("<!-- GENERATED by tests/ArcaneCore.World.Tests/Docs (CommandReferenceRenderer) from the live command table. Do not edit by hand.\n");
        sb.Append("     Regenerate: ").Append(DocsGolden.RegenerateCommand).Append(" -->\n\n");
        sb.Append("Every chat command the world daemon registers, with the account level it needs. A message that starts with `.` or `!` is a command. ");
        sb.Append("A command word resolves to the first table entry it is a prefix of, then the account is checked, as vmangos does; `World:GmCommands:HideUnavailable` and `ExactNameFirst` (see the [configuration reference](configuration.md)) switch to the older ArcaneCore behaviour.\n\n");
        sb.Append("Coverage: ArcaneCore implements a subset of the vmangos command table (the vmangos wiki documents several hundred commands). Commands are only listed here when they exist in this tree; there is no console command sender, so commands that vmangos allows from the server console are reachable only from an in-game account.\n\n");

        sb.Append("## Account levels\n\n");
        sb.Append("ArcaneCore stores four account levels. The vmangos levels are 0-7 (player, moderator, ticket master, game master, basic admin, developer, administrator, console), so each stored level is mapped onto a retail level by `World:GmCommands:SecurityMap`. ");
        sb.Append("With the default map the retail levels 2, 4 and 5 are not the level of any stored account: a command at one of them needs the next stored level above it, ");
        sb.Append("unless an operator remaps a stored level onto it. The **Minimum account** column below is computed from the default map.\n\n");
        sb.Append("| Stored account | Retail level (default map) | Commands reachable |\n|---|---|---|\n");
        foreach (AccountSecurity security in Enum.GetValues<AccountSecurity>().OrderBy(s => (int)s))
        {
            int reachable = nodes.Count(n => n.HasHandler && options.LevelOf(security) >= n.RequiredLevel);
            sb.Append("| `").Append(security).Append("` | ").Append(options.LevelOf(security)).Append(" | ").Append(reachable).Append(" |\n");
        }

        sb.Append("\nThe counts include the development-only commands below, which exist only when `HotReload:Commands` (for `.reload`) or the `World:HotCode` switches (for `.hotcode` and `.hotmodule`) are on; all of those default to off.\n\n");

        sb.Append("## Commands\n\n");
        sb.Append("A group (`...`) may also have a handler of its own that serves arguments naming no sub-command. **Level source** says where the level comes from: the retail table recorded in `RetailCommandLevels` (each entry cites its line of vmangos `Chat.cpp`), a level declared on the command, or the command's stored level through the map.\n\n");
        sb.Append("| Command | Retail level | Minimum account | Level source | Help |\n|---|---|---|---|---|\n");
        foreach (CommandNode node in nodes)
        {
            string min = MinimumAccount(node.RequiredLevel, options)?.ToString() ?? "none";
            string flags = (node.DevOnly ? " (development only" + (node.RuntimeNote is null ? string.Empty : "; " + node.RuntimeNote) + ")" : string.Empty);
            sb.Append("| `.").Append(node.Path).Append('`').Append(node.IsGroup ? " ..." : string.Empty).Append(flags).Append(" | ")
                .Append(node.RequiredLevel).Append(" | ").Append(min).Append(" | ").Append(node.LevelSource).Append(" | ").Append(Cell(node.Help)).Append(" |\n");
        }

        return sb.ToString();
    }

    private static string Cell(string text) => text.Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal)
        .Replace("|", "\\|", StringComparison.Ordinal).Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal).Trim();
}
