using System.Text;
using ArcaneCore.World.Reload;

namespace ArcaneCore.World.Tests.Docs;

/// <summary>The production catalog (every options section of the four assemblies) and the page rendered from it.</summary>
internal static class ConfigProduction
{
    private static readonly Lazy<ConfigCatalogResult> Cached = new(BuildCatalog);

    public static ConfigCatalogResult Catalog => Cached.Value;

    /// <summary>The text of every .cs file under src and tools, excluding build output.</summary>
    public static IReadOnlyList<(string Path, string Text)> SourceFiles()
    {
        string root = RepoRoot.Find();
        var files = new List<(string, string)>();
        foreach (string top in new[] { "src", "tools" })
        {
            string dir = Path.Combine(root, top);
            foreach (string file in Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories))
            {
                string relative = Path.GetRelativePath(root, file).Replace('\\', '/');
                if (relative.Contains("/obj/", StringComparison.Ordinal) || relative.Contains("/bin/", StringComparison.Ordinal))
                {
                    continue;
                }

                files.Add((relative, File.ReadAllText(file)));
            }
        }

        return files;
    }

    private static ConfigCatalogResult BuildCatalog()
    {
        var summaries = new ConfigSourceSummaries(SourceFiles().Select(f => f.Text));
        Dictionary<string, string> reload = WorldConfigKeys.All.ToDictionary(k => k.Path, k => k.Live ? "live" : "restart", StringComparer.Ordinal);
        return ConfigCatalog.Build(
            ConfigExceptionTable.Sections(),
            summaries.Find,
            ConfigDocOverrides.Texts,
            ConfigExceptionTable.SkippedProperties,
            path => reload.GetValueOrDefault(path));
    }
}

/// <summary>Renders <c>docs/reference/configuration.md</c>.</summary>
internal static class ConfigReferenceRenderer
{
    public static string Render(IReadOnlyList<ConfigEntry> entries, IReadOnlyList<AdHocKey> adHoc, IReadOnlyDictionary<string, string> skipped)
    {
        var sb = new StringBuilder();
        sb.Append("# Configuration reference\n\n");
        sb.Append("<!-- GENERATED by tests/ArcaneCore.World.Tests/Docs (ConfigReferenceRenderer) from the options classes. Do not edit by hand.\n");
        sb.Append("     Regenerate: ").Append(DocsGolden.RegenerateCommand).Append(" -->\n\n");
        sb.Append("Both daemons build their configuration with the .NET generic host defaults: `appsettings.json` from the content root (the working directory the daemon starts in), then environment variables, then command-line arguments. ");
        sb.Append("The environment variable for a key is the key with each `:` replaced by `__` (a command-line argument uses `--Section:Key=value`), for example `World:GmCommands:LowerSecurity` is `World__GmCommands__LowerSecurity`. ");
        sb.Append("`ArcaneCore.World.exe check-config` validates the result and the daemon runs the same check at every start (exit code 78 when invalid).\n\n");
        sb.Append("How to read the tables:\n\n");
        sb.Append("- **Default** is the value of a freshly constructed options object, so it cannot disagree with the code. ");
        sb.Append("A section that is absent from the file simply keeps every default.\n");
        sb.Append("- **Reload** is what `.reload config` does with a `World` key: `live` is applied to the running server, `restart` keeps its value until the next start (and logs that it could not change). ");
        sb.Append("`-` means the key is not part of the `.reload config` set (see docs/areas/hot-reload.md).\n");
        sb.Append("- **Meaning** is the `///` summary of the property in the source, which also carries the retail (vmangos) reference where one exists. ");
        sb.Append("Where a property has no summary yet, the text comes from the documentation overrides in the docs tests, never from this page.\n");
        sb.Append("- A default that is not the retail behaviour is called out in its meaning where the source records it. The release caveats of the opt-in hardening switches are in docs/security/hardening.md.\n\n");

        string[] sections = [.. entries.Select(e => e.Section).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal)];
        sb.Append("## Sections\n\n");
        foreach (string section in sections)
        {
            sb.Append("- [`").Append(section).Append("`](#").Append(Anchor(section)).Append(")\n");
        }

        sb.Append("- [Keys read by name](#keys-read-by-name)\n- [Aliases and framework sections](#aliases-and-framework-sections)\n\n");

        foreach (string section in sections)
        {
            sb.Append("## `").Append(section).Append("`\n\n");
            sb.Append("| Key | Type | Default | Reload | Meaning |\n|---|---|---|---|---|\n");
            foreach (ConfigEntry entry in entries.Where(e => e.Section == section))
            {
                sb.Append("| `").Append(entry.Path).Append("` | `").Append(entry.TypeText).Append("` | ")
                    .Append(Code(entry.Default)).Append(" | ").Append(entry.Reload).Append(" | ").Append(entry.Meaning).Append(" |\n");
            }

            sb.Append('\n');
        }

        sb.Append("## Keys read by name\n\n");
        sb.Append("These keys are read directly rather than through an options class.\n\n| Key | Type | Default | Meaning |\n|---|---|---|---|\n");
        foreach (AdHocKey key in adHoc.OrderBy(k => k.Path, StringComparer.Ordinal))
        {
            sb.Append("| `").Append(key.Path).Append("` | `").Append(key.TypeText).Append("` | `").Append(key.Default).Append("` | ").Append(key.Meaning).Append(" |\n");
        }

        sb.Append("\n## Aliases and framework sections\n\n");
        foreach (KeyValuePair<string, string> alias in skipped.OrderBy(a => a.Key, StringComparer.Ordinal))
        {
            sb.Append("- `").Append(alias.Key).Append("`: ").Append(alias.Value).Append('\n');
        }

        sb.Append("- `Logging` and `HostOptions` (`ShutdownTimeout`) belong to the .NET host, not to ArcaneCore; see the .NET documentation for their keys.\n");
        return sb.ToString();
    }

    private static string Code(string value) => value.Contains('|', StringComparison.Ordinal) ? "`" + value.Replace("|", "\\|", StringComparison.Ordinal) + "`" : "`" + value + "`";

    /// <summary>The GitHub heading anchor of a heading made of one code span.</summary>
    internal static string Anchor(string heading)
    {
        var sb = new StringBuilder();
        foreach (char c in heading.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c) || c == '-' || c == '_')
            {
                sb.Append(c);
            }
            else if (c == ' ')
            {
                sb.Append('-');
            }
        }

        return sb.ToString();
    }
}
