using System.Text;

namespace ArcaneCore.World.Tests.Docs;

/// <summary>How a key's default relates to the retail (vmangos) behaviour.</summary>
internal enum Stance
{
    /// <summary>The default is the retail behaviour; the key only exists so an operator can opt into something stricter.</summary>
    OptIn,

    /// <summary>The default is NOT the retail behaviour: the retail value is what an operator sets for parity.</summary>
    NonRetailDefault,

    /// <summary>A development switch that is off by default.</summary>
    DevelopmentOnly,
}

/// <summary>One release-note entry: a key an operator should decide on before exposing a realm.</summary>
internal sealed record Deviation(string Key, string Default, Stance Stance, string Retail, string Advice);

/// <summary>
/// The release caveats of docs/guide/operations.md. <see cref="Deviation.Default"/> is asserted against the options default in a test, so flipping a
/// default in code fails until this register (and the guide) is reviewed. The retail text is authored: where it cites vmangos, the line was read in
/// D:\refs\vmangos at the time of writing and is not asserted by CI (hosted CI has no reference clones).
/// </summary>
internal static class DeviationRegister
{
    public const string Begin = "<!-- register:begin (generated by DeviationRegister; edit the register, not this table) -->";

    public const string End = "<!-- register:end -->";

    public static readonly IReadOnlyList<Deviation> All =
    [
        new("Auth:MaxConnections", "0", Stance.OptIn, "No vmangos equivalent; unlimited.", "Set a cap on an internet-facing realm."),
        new("Auth:MaxConnectionsPerIp", "0", Stance.OptIn, "No vmangos equivalent; unlimited.", "Set a per-address cap on an internet-facing realm."),
        new("World:MaxConnections", "0", Stance.OptIn, "No vmangos equivalent; unlimited.", "Set a cap on an internet-facing realm (restart to change)."),
        new("World:MaxConnectionsPerIp", "0", Stance.OptIn, "No vmangos equivalent; unlimited.", "Set a per-address cap on an internet-facing realm (restart to change)."),
        new("Auth:ReadTimeoutSeconds", "0", Stance.OptIn, "vmangos has none (slow-read clients are not cut off).", "A positive value cuts a client that trickles a logon packet."),
        new("Auth:StrictUsernameCharset", "false", Stance.OptIn, "Retail accepts any bytes in a name.", "True rejects names outside printable ASCII."),
        new("Auth:AutocreateAccounts", "false", Stance.OptIn, "vmangos has no auto-create; accounts are created with the account command.", "Leave off. When on, an unknown account is created on first login with the password equal to the name."),
        new("World:WriterDrainGrace", "00:00:00", Stance.OptIn, "vmangos has no bound: a closing session waits for a stalled client forever.", "Set for example 00:00:05 so a client that stopped reading cannot hold a connection."),
        new("World:PreAuthTimeout", "00:00:10", Stance.OptIn, "Retail rule: vmangos Network.TimeoutSecsIfNoAuth = 10 (WorldSocket.cpp:621-628).", "Leave at the retail value; 00:00:00 disables it."),
        new("World:MaxQueuedWorldPackets", "8192", Stance.NonRetailDefault, "vmangos queues without a bound (WorldSession.cpp:307).", "On by default as hardening; 0 restores the retail unbounded queue."),
        new("World:MaxQueuedWorldBytes", "8388608", Stance.NonRetailDefault, "vmangos queues without a bound.", "On by default as hardening (8 MiB); 0 restores the retail unbounded queue."),
        new("World:Social:MaxJoinedChannels", "0", Stance.OptIn, "vmangos has no channel cap.", "A positive value caps channels per player."),
        new("Auth:IpBanCacheSeconds", "60", Stance.NonRetailDefault, "vmangos realmd reads `ip_banned` on every logon challenge (AuthSocket.cpp:338-352); mangosd keeps the same list in memory, reloaded every 60 s.", "On by default so a reconnect flood does not cost one query per connection; a ban written elsewhere reaches the logon screen within the period (world login refuses it at once), and an unban written elsewhere also takes up to one period to let the address back in. If the list cannot be loaded, challenges fall back to the per-challenge row read for one period. Set 0 for the per-challenge read."),
        new("Bans:RecheckIntervalSeconds", "60", Stance.NonRetailDefault, "Retail: a ban row written by another process does not kick a connected account (mangosd only reloads its IP-ban cache every BanListReloadTimer = 60 s).", "On by default so `arcane-account` and SQL bans reach connected players within a minute; set 0 for exact retail."),
        new("Bans:RevokeSessionKeyOnBan", "false", Stance.OptIn, "Retail keeps the session key and relies on the ban check at world login.", "True also revokes the key, so a banned client's reconnect is refused earlier."),
        new("Bans:RejectUnparseableDuration", "false", Stance.OptIn, "Retail turns a malformed duration into a PERMANENT ban.", "True refuses a malformed duration instead; set it unless you want exact retail behaviour."),
        new("Bans:ProtectHigherSecurity", "true", Stance.NonRetailDefault, "Retail has no hierarchy guard on `.ban account` / `.ban character`.", "On by default; set false for exact retail."),
        new("World:GmCommands:LowerSecurity", "true", Stance.NonRetailDefault, "vmangos GM.LowerSecurity defaults to 0 (mangosd.conf.dist.in:2536), which lets staff act on a higher account.", "On by default (stricter); set false for exact retail."),
        new("HotReload:Commands", "false", Stance.DevelopmentOnly, "Retail always registers its reload commands.", "Leave off in production; it exposes `.reload` to administrators."),
        new("World:HotCode:Enabled", "false", Stance.DevelopmentOnly, "Not a retail feature.", "Accepted only in Development or Staging; the daemon refuses to start otherwise (exit code 78)."),
        new("World:HotCode:Modules:Enabled", "false", Stance.DevelopmentOnly, "Not a retail feature.", "Loads code from disk into the daemon; leave off in production."),
        new("World:ListenRangeSay", "25", Stance.OptIn, "vmangos code default 25 (World.cpp:556) but its shipped mangosd.conf.dist.in sets 40 (:1559); a stock vmangos realm therefore says 40.", "Set 40 to match a stock vmangos realm."),
        new("World:ListenRangeTextEmote", "25", Stance.OptIn, "vmangos code default 25 (World.cpp:558) but its shipped mangosd.conf.dist.in sets 40 (:1560).", "Set 40 to match a stock vmangos realm."),
        new("World:Maps:GridUnload", "true", Stance.OptIn, "vmangos code default true (World.cpp:582) but its shipped mangosd.conf.dist.in sets 0 (:399).", "Set false to keep grids loaded as the shipped vmangos configuration does."),
        new("Database:Upgrade:Policy", "Always", Stance.NonRetailDefault, "vmangos never creates or upgrades a database on start.", "Use `CreateOnly` or `Never` once the databases exist and upgrade with `arcane-db`."),
        new("Net:Protection:MaxConnectionsPerIp", "16", Stance.NonRetailDefault, "No vmangos equivalent; unlimited. The daemon caps `Auth:`/`World:MaxConnectionsPerIp` stay 0, this shared cap is what applies.", "On by default as hardening: 16 simultaneous connections per client address on each listener, so a LAN party or campus NAT with more players than that behind one address is cut off at the 17th. Set 0 to restore the retail unlimited behaviour (restart to change)."),
    ];

    /// <summary>The markdown table the guide embeds between <see cref="Begin"/> and <see cref="End"/>.</summary>
    public static string Block()
    {
        var sb = new StringBuilder();
        sb.Append(Begin).Append('\n');
        sb.Append("| Key | Default | Default is | Retail (vmangos) | What to do |\n|---|---|---|---|---|\n");
        foreach (Deviation d in All)
        {
            string stance = d.Stance switch
            {
                Stance.NonRetailDefault => "**not retail**",
                Stance.DevelopmentOnly => "development only",
                _ => "retail",
            };
            sb.Append("| `").Append(d.Key).Append("` | `").Append(d.Default).Append("` | ").Append(stance).Append(" | ").Append(d.Retail).Append(" | ").Append(d.Advice).Append(" |\n");
        }

        sb.Append(End);
        return sb.ToString();
    }

    /// <summary>The guide text with its register block replaced by <see cref="Block"/> (used when the docs are regenerated).</summary>
    public static string Replace(string guide)
    {
        string normalized = guide.Replace("\r\n", "\n", StringComparison.Ordinal);
        int begin = normalized.IndexOf(Begin, StringComparison.Ordinal);
        int end = normalized.IndexOf(End, StringComparison.Ordinal);
        if (begin < 0 || end < begin)
        {
            throw new InvalidOperationException("the guide has no register block markers");
        }

        return normalized[..begin] + Block() + normalized[(end + End.Length)..];
    }
}
