using System.Text;
using ArcaneCore.Data;
using ArcaneCore.Data.Auth;
using ArcaneCore.Data.Characters;
using ArcaneCore.Data.Content;
using ArcaneCore.Data.Schema;
using Microsoft.Extensions.DependencyInjection;
using HostExitCodes = ArcaneCore.Kernel.Ops.ExitCodes;
using ImporterExitCodes = ArcaneCore.Data.Content.Import.ExitCodes;

namespace ArcaneCore.World.Tests.Docs;

/// <summary>One schema version of one component.</summary>
internal sealed record SchemaRow(int Version, string Owner, string Changes, bool? HasCharacterCleanup);

/// <summary>The schema history of one component, built from the live definitions.</summary>
internal sealed record SchemaComponent(DatabaseComponent Component, string Name, int CurrentVersion, IReadOnlyList<string> Version1Tables, IReadOnlyList<SchemaRow> Rows);

/// <summary>Builds and renders docs/reference/schema.md and docs/reference/exit-codes.md.</summary>
internal static class SchemaReferenceRenderer
{
    public static IReadOnlyList<SchemaComponent> Components() =>
    [
        Build(DatabaseComponent.Auth, AuthDbContext.Schema),
        Build(DatabaseComponent.Characters, CharacterDbContext.Schema),
        Build(DatabaseComponent.World, WorldDbContext.Schema),
    ];

    public static SchemaComponent Build(DatabaseComponent component, SchemaDefinition schema, IEnumerable<IDataModule>? moduleSet = null)
    {
        IDataModule[] modules = [.. moduleSet ?? DataModules.For(component)];
        var rows = new List<SchemaRow>();
        foreach (SchemaStep step in schema.Steps.OrderBy(s => s.Version))
        {
            IDataModule[] owners = [.. modules.Where(m => m.SchemaVersion == step.Version)];
            string owner = owners.Length == 1 ? ModuleName(owners[0]) : "inline step of the database context";
            bool? cleanup = component == DatabaseComponent.Characters
                ? (owners.Length == 1 ? HasCleanup(owners[0]) : null)
                : null;
            rows.Add(new SchemaRow(step.Version, owner, DescribeChanges(step.Changes), cleanup));
        }

        return new SchemaComponent(component, schema.Component, schema.CurrentVersion, schema.Version1Tables, rows);
    }

    private static string ModuleName(IDataModule module)
    {
        string full = module.GetType().FullName ?? module.GetType().Name;
        const string prefix = "ArcaneCore.Data.";
        return full.StartsWith(prefix, StringComparison.Ordinal) ? full[prefix.Length..] : full;
    }

    /// <summary>True when the module implements, or registers, an <see cref="ICharacterDataCleanup"/> (it removes its rows when a character is deleted).</summary>
    public static bool HasCleanup(IDataModule module)
    {
        if (module is ICharacterDataCleanup)
        {
            return true;
        }

        var services = new ServiceCollection();
        module.AddServices(services);
        return services.Any(d => d.ServiceType == typeof(ICharacterDataCleanup));
    }

    private static string DescribeChanges(IReadOnlyList<SchemaChange> changes)
    {
        var parts = new List<string>();
        string[] tables = [.. changes.OfType<CreateTableChange>().Select(c => c.Table)];
        if (tables.Length > 0)
        {
            parts.Add("creates " + string.Join(", ", tables.Select(t => "`" + t + "`")));
        }

        string[] columns = [.. changes.OfType<AddColumnChange>().Select(c => c.Table + "." + c.Column)];
        if (columns.Length > 0)
        {
            parts.Add("adds columns " + string.Join(", ", columns.Select(c => "`" + c + "`")));
        }

        string[] indexes = [.. changes.OfType<EnsureIndexesChange>().Select(c => c.Table)];
        if (indexes.Length > 0)
        {
            parts.Add("repairs the model's indexes of " + string.Join(", ", indexes.Select(t => "`" + t + "`")));
        }

        if (changes.Any(c => c is not (CreateTableChange or AddColumnChange or EnsureIndexesChange)))
        {
            parts.Add("other changes (see the module)");
        }

        return parts.Count == 0 ? "no changes" : string.Join("; ", parts);
    }

    public static string RenderSchema(IReadOnlyList<SchemaComponent> components)
    {
        var sb = new StringBuilder();
        sb.Append("# Database schema reference\n\n");
        sb.Append("<!-- GENERATED by tests/ArcaneCore.World.Tests/Docs (SchemaReferenceRenderer) from DataModules and the context schema definitions. Do not edit by hand.\n");
        sb.Append("     Regenerate: ").Append(DocsGolden.RegenerateCommand).Append(" -->\n\n");
        sb.Append("ArcaneCore keeps three logical databases (auth, characters, world), each with its own schema version in a `<component>_schema` table. ");
        sb.Append("A feature adds its tables by implementing `IDataModule` (the seam table is in docs/integration/seams.md); a component's versions run 2, 3, ... without gaps or duplicates ");
        sb.Append("and a gap fails at start before any database is touched. The version numbers are allocated by the integrator and renumbered at merge time, so the tables below show this tree's numbering only.\n\n");
        sb.Append("Upgrading an existing database is described in the [database upgrade runbook](../ops/database-upgrade.md); ");
        sb.Append("how each engine behaves while a step runs (MariaDB DDL commits implicitly, PostgreSQL DDL is transactional) is in the runbook and in [schema index repair](../integration/schema-index-repair.md). ");
        sb.Append("This page is metadata only: it reads the definitions and does not prove any behaviour of a database engine.\n\n");

        sb.Append("| Component | Current version | Version-1 base tables |\n|---|---|---|\n");
        foreach (SchemaComponent c in components)
        {
            sb.Append("| `").Append(c.Name).Append("` | ").Append(c.CurrentVersion).Append(" | ").Append(string.Join(", ", c.Version1Tables.Select(t => "`" + t + "`"))).Append(" |\n");
        }

        foreach (SchemaComponent c in components)
        {
            sb.Append("\n## `").Append(c.Name).Append("`\n\n");
            bool characters = c.Component == DatabaseComponent.Characters;
            sb.Append(characters ? "| Version | Owner | Changes | Removes rows on character delete |\n|---|---|---|---|\n" : "| Version | Owner | Changes |\n|---|---|---|\n");
            foreach (SchemaRow row in c.Rows)
            {
                sb.Append("| ").Append(row.Version).Append(" | `").Append(row.Owner).Append("` | ").Append(row.Changes);
                if (characters)
                {
                    sb.Append(" | ").Append(row.HasCharacterCleanup switch { true => "yes", false => "no", null => "-" });
                }

                sb.Append(" |\n");
            }
        }

        sb.Append("\nThe last column is `yes` when the owning module implements or registers an `ICharacterDataCleanup` (it runs inside the character-deletion transaction); ");
        sb.Append("`no` means the module registers none; `-` is a step owned by the database context itself.\n");
        return sb.ToString();
    }

    public static string RenderExitCodes()
    {
        var sb = new StringBuilder();
        sb.Append("# Exit codes\n\n");
        sb.Append("<!-- GENERATED by tests/ArcaneCore.World.Tests/Docs (SchemaReferenceRenderer) from the exit-code classes. Do not edit by hand.\n");
        sb.Append("     Regenerate: ").Append(DocsGolden.RegenerateCommand).Append(" -->\n\n");
        sb.Append("## `ArcaneCore.World` and `ArcaneCore.Realm` daemons, and the operations verbs\n\n");
        sb.Append("0, 1 and 2 are the vmangos shutdown exit codes, so a supervisor that restarts on 2 reproduces the vmangos run-mangosd loop. ");
        sb.Append("Supervisors must not restart on 78 (systemd: `RestartPreventExitStatus=78`).\n\n");
        sb.Append(ConstantTable(typeof(HostExitCodes), "src/ArcaneCore.Kernel/Ops/ExitCodes.cs", excluded: ["MaxRequested"]));
        sb.Append("\nThe largest code a shutdown command may ask for is ").Append(HostExitCodes.MaxRequested).Append(" (126-255 belong to shells).\n\n");
        sb.Append("## `arcane-db`\n\nThe `arcane-db` codes (0-8) are documented in one place, the table of the [database upgrade runbook](../ops/database-upgrade.md); a test keeps that table complete.\n\n");
        sb.Append("## `arcane-content-importer`\n\n");
        sb.Append(ConstantTable(typeof(ImporterExitCodes), "src/ArcaneCore.Data/Content/Import/Cli/ExitCodes.cs", excluded: []));
        return sb.ToString();
    }

    private static string ConstantTable(Type type, string sourceFile, IReadOnlyCollection<string> excluded)
    {
        var summaries = new ConfigSourceSummaries([RepoRoot.ReadText(sourceFile)]);
        var sb = new StringBuilder("| Code | Name | Meaning |\n|---|---|---|\n");
        var fields = type.GetFields(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static)
            .Where(f => f.IsLiteral && f.FieldType == typeof(int) && !excluded.Contains(f.Name))
            .Select(f => (Value: (int)f.GetRawConstantValue()!, f.Name))
            .OrderBy(f => f.Value).ThenBy(f => f.Name, StringComparer.Ordinal);
        foreach ((int value, string name) in fields)
        {
            string meaning = summaries.Find(type, name) ?? throw new InvalidOperationException($"{type.Name}.{name} has no /// summary to document it with");
            sb.Append("| ").Append(value).Append(" | `").Append(name).Append("` | ").Append(meaning).Append(" |\n");
        }

        return sb.ToString();
    }
}
