<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ArcaneCore.ContentImporter</RootNamespace>
    <AssemblyName>arcane-content-importer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ArcaneCore.Data\ArcaneCore.Data.csproj" />
  </ItemGroup>

</Project>
